importScripts("shared.js");
shadow$provide[14]=function(d,h,b,l,a,m){d=function(a){function b(a,b,c){Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0});return a[b]}function c(a,b,c,d){b=Object.create((b&&b.prototype instanceof f?b:f).prototype);d=new e(d||[]);b._invoke=n(a,c,d);return b}function d(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(Q){return{type:"throw",arg:Q}}}function f(){}function q(){}function u(){}function v(a){["next","throw","return"].forEach(function(c){b(a,c,function(a){return this._invoke(c,
a)})})}function k(a,b){function c(f,g,p,e){f=d(a[f],a,g);if("throw"===f.type)e(f.arg);else{var q=f.arg;return(f=q.value)&&"object"===typeof f&&D.call(f,"__await")?b.resolve(f.__await).then(function(a){c("next",a,p,e)},function(a){c("throw",a,p,e)}):b.resolve(f).then(function(a){q.value=a;p(q)},function(a){return c("throw",a,p,e)})}}var f;this._invoke=function(a,d){function g(){return new b(function(b,f){c(a,d,b,f)})}return f=f?f.then(g,g):g()}}function n(a,b,c){var f=M;return function(g,e){if(f===
J)throw Error("Generator is already running");if(f===I){if("throw"===g)throw e;return z()}c.method=g;for(c.arg=e;;){if(g=c.delegate)if(g=p(g,c)){if(g===C)continue;return g}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(f===M)throw f=I,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);f=J;g=d(a,b,c);if("normal"===g.type){f=c.done?I:K;if(g.arg===C)continue;return{value:g.arg,done:c.done}}"throw"===g.type&&(f=I,c.method="throw",c.arg=g.arg)}}}
function p(a,b){var c=a.iterator[b.method];if(c===A){b.delegate=null;if("throw"===b.method){if(a.iterator["return"]&&(b.method="return",b.arg=A,p(a,b),"throw"===b.method))return C;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return C}c=d(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,b.delegate=null,C;c=c.arg;if(!c)return b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,C;if(c.done)b[a.resultName]=
c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=A);else return c;b.delegate=null;return C}function y(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function x(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function e(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(y,this);this.reset(!0)}function w(a){if(a){var b=a[m];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var c=
-1;b=function F(){for(;++c<a.length;)if(D.call(a,c))return F.value=a[c],F.done=!1,F;F.value=A;F.done=!0;return F};return b.next=b}}return{next:z}}function z(){return{value:A,done:!0}}var h=Object.prototype,D=h.hasOwnProperty,A,l="function"===typeof Symbol?Symbol:{},m=l.iterator||"@@iterator",H=l.asyncIterator||"@@asyncIterator",B=l.toStringTag||"@@toStringTag";try{b({},"")}catch(O){b=function(a,b,c){return a[b]=c}}a.wrap=c;var M="suspendedStart",K="suspendedYield",J="executing",I="completed",C={};
l={};b(l,m,function(){return this});var E=Object.getPrototypeOf;(E=E&&E(E(w([]))))&&E!==h&&D.call(E,m)&&(l=E);var G=u.prototype=f.prototype=Object.create(l);q.prototype=u;b(G,"constructor",u);b(u,"constructor",q);q.displayName=b(u,B,"GeneratorFunction");a.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===q||"GeneratorFunction"===(a.displayName||a.name):!1};a.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,u):(a.__proto__=u,b(a,B,"GeneratorFunction"));
a.prototype=Object.create(G);return a};a.awrap=function(a){return{__await:a}};v(k.prototype);b(k.prototype,H,function(){return this});a.AsyncIterator=k;a.async=function(b,f,g,d,p){void 0===p&&(p=Promise);var e=new k(c(b,f,g,d),p);return a.isGeneratorFunction(f)?e:e.next().then(function(a){return a.done?a.value:e.next()})};v(G);b(G,B,"Generator");b(G,m,function(){return this});b(G,"toString",function(){return"[object Generator]"});a.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function F(){for(;b.length;){var c=
b.pop();if(c in a)return F.value=c,F.done=!1,F}F.done=!0;return F}};a.values=w;e.prototype={constructor:e,reset:function(a){this.next=this.prev=0;this.sent=this._sent=A;this.done=!1;this.delegate=null;this.method="next";this.arg=A;this.tryEntries.forEach(x);if(!a)for(var b in this)"t"===b.charAt(0)&&D.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=A)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,
f){d.type="throw";d.arg=a;c.next=b;f&&(c.method="next",c.arg=A);return!!f}if(this.done)throw a;for(var c=this,f=this.tryEntries.length-1;0<=f;--f){var g=this.tryEntries[f],d=g.completion;if("root"===g.tryLoc)return b("end");if(g.tryLoc<=this.prev){var p=D.call(g,"catchLoc"),e=D.call(g,"finallyLoc");if(p&&e){if(this.prev<g.catchLoc)return b(g.catchLoc,!0);if(this.prev<g.finallyLoc)return b(g.finallyLoc)}else if(p){if(this.prev<g.catchLoc)return b(g.catchLoc,!0)}else if(e){if(this.prev<g.finallyLoc)return b(g.finallyLoc)}else throw Error("try statement without catch or finally");
}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var f=this.tryEntries[c];if(f.tryLoc<=this.prev&&D.call(f,"finallyLoc")&&this.prev<f.finallyLoc){var g=f;break}}g&&("break"===a||"continue"===a)&&g.tryLoc<=b&&b<=g.finallyLoc&&(g=null);c=g?g.completion:{};c.type=a;c.arg=b;return g?(this.method="next",this.next=g.finallyLoc,C):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=
this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b);return C},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),x(c),C}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var f=a.arg;x(c)}return f}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate=
{iterator:w(a),resultName:b,nextLoc:c};"next"===this.method&&(this.arg=A);return C}};return a}("object"===typeof l?l.exports:{});try{regeneratorRuntime=d}catch(c){"object"===typeof globalThis?globalThis.regeneratorRuntime=d:Function("r","regeneratorRuntime \x3d r")(d)}};
shadow$provide[15]=function(d,h,b,l,a,m){try{self["workbox:core:6.4.0"]&&_()}catch(c){}};
shadow$provide[16]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.logger=void 0;b(15);a.logger=null};
shadow$provide[17]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.messages=void 0;b(15);a.messages={"invalid-value":function(a){var b=a.paramName,c=a.validValueDescription;a=a.value;if(!b||!c)throw Error("Unexpected input to 'invalid-value' error.");return"The '"+b+"' parameter was given a value with an "+("unexpected value. "+c+" Received a value of ")+(JSON.stringify(a)+".")},"not-an-array":function(a){var b=a.moduleName,c=a.className,d=a.funcName;a=a.paramName;if(!(b&&
c&&d&&a))throw Error("Unexpected input to 'not-an-array' error.");return"The parameter '"+a+"' passed into "+("'"+b+"."+c+"."+d+"()' must be an array.")},"incorrect-type":function(a){var b=a.expectedType,c=a.paramName,d=a.moduleName,f=a.className;a=a.funcName;if(!(b&&c&&d&&a))throw Error("Unexpected input to 'incorrect-type' error.");return"The parameter '"+c+"' passed into "+("'"+d+"."+(f?f+".":""))+(a+"()' must be of type "+b+".")},"incorrect-class":function(a){var b=a.expectedClassName,c=a.paramName,
d=a.moduleName,f=a.className,q=a.funcName;a=a.isReturnValueProblem;if(!b||!d||!q)throw Error("Unexpected input to 'incorrect-class' error.");f=f?f+".":"";return a?"The return value from "+("'"+d+"."+f+q+"()' ")+("must be an instance of class "+b+"."):"The parameter '"+c+"' passed into "+("'"+d+"."+f+q+"()' ")+("must be an instance of class "+b+".")},"missing-a-method":function(a){var b=a.expectedMethod,c=a.paramName,d=a.moduleName,f=a.className;a=a.funcName;if(!(b&&c&&d&&f&&a))throw Error("Unexpected input to 'missing-a-method' error.");
return d+"."+f+"."+a+"() expected the "+("'"+c+"' parameter to expose a '"+b+"' method.")},"add-to-cache-list-unexpected-type":function(a){return"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+("'"+JSON.stringify(a.entry)+"' isn't supported. You must supply an array of ")+"strings with one or more characters, objects with a url property or Request objects."},"add-to-cache-list-conflicting-entries":function(a){var b=a.firstEntry;a=a.secondEntry;
if(!b||!a)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+(b+" but different revision details. Workbox is ")+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":function(a){a=a.thrownErrorMessage;if(!a)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+
("The thrown error message was: '"+a+"'.")},"invalid-cache-name":function(a){var b=a.cacheNameId;a=a.value;if(!b)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");return"You must provide a name containing at least one character for "+("setCacheDetails({"+b+": '...'}). Received a value of ")+("'"+JSON.stringify(a)+"'")},"unregister-route-but-not-found-with-method":function(a){a=a.method;if(!a)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");
return"The route you're trying to unregister was not  previously "+("registered for the method type '"+a+"'.")},"unregister-route-route-not-registered":function(){return"The route you're trying to unregister was not previously registered."},"queue-replay-failed":function(a){return"Replaying the background sync queue '"+a.name+"' failed."},"duplicate-queue-name":function(a){return"The Queue name '"+a.name+"' is already being used. All instances of backgroundSync.Queue must be given unique names."},
"expired-test-without-max-age":function(a){return"The '"+a.methodName+"()' method can only be used when the "+("'"+a.paramName+"' is used in the constructor.")},"unsupported-route-type":function(a){return"The supplied '"+a.paramName+"' parameter was an unsupported type. "+("Please check the docs for "+a.moduleName+"."+a.className+"."+a.funcName+" for ")+"valid input types."},"not-array-of-class":function(a){var b=a.moduleName,c=a.className,d=a.funcName;return"The supplied '"+a.paramName+"' parameter must be an array of "+
("'"+a.expectedClass+"' objects. Received '"+JSON.stringify(a.value)+",'. ")+("Please check the call to "+b+"."+c+"."+d+"() ")+"to fix the issue."},"max-entries-or-age-required":function(a){return"You must define either config.maxEntries or config.maxAgeSeconds"+("in "+a.moduleName+"."+a.className+"."+a.funcName)},"statuses-or-headers-required":function(a){return"You must define either config.statuses or config.headers"+("in "+a.moduleName+"."+a.className+"."+a.funcName)},"invalid-string":function(a){var b=
a.moduleName,c=a.funcName;a=a.paramName;if(!a||!b||!c)throw Error("Unexpected input to 'invalid-string' error.");return"When using strings, the '"+a+"' parameter must start with 'http' (for cross-origin matches) or '/' (for same-origin matches). "+("Please see the docs for "+b+"."+c+"() for ")+"more info."},"channel-name-required":function(){return"You must provide a channelName to construct a BroadcastCacheUpdate instance."},"invalid-responses-are-same-args":function(){return"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used."},
"expire-custom-caches-only":function(){return"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy."},"unit-must-be-bytes":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+('The Range header provided was "'+a+'"')},"single-range-only":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'single-range-only' error.");
return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+('"'+a+'"')},"invalid-range-values":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+('"'+a+'"')},"no-range-header":function(){return"No Range header was found in the Request provided."},
"range-not-satisfiable":function(a){return"The start ("+a.start+") and end ("+a.end+") values in the Range are "+("not satisfiable by the cached response, which is "+a.size+" bytes.")},"attempt-to-cache-non-get-request":function(a){return"Unable to cache '"+a.url+"' because it is a '"+a.method+"' request and only 'GET' requests can be cached."},"cache-put-with-no-response":function(a){return"There was an attempt to cache '"+a.url+"' but the response was not defined."},"no-response":function(a){var b=
a.error;a="The strategy could not generate a response for '"+a.url+"'.";b&&(a+=" The underlying error is "+b+".");return a},"bad-precaching-response":function(a){var b=a.status;return"The precaching request for '"+a.url+"' failed"+(b?" with an HTTP status of "+b+".":".")},"non-precached-url":function(a){return"createHandlerBoundToURL('"+a.url+"') was called, but that URL is not precached. Please pass in a URL that is precached instead."},"add-to-cache-list-conflicting-integrities":function(a){return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
(a.url+" with different integrity values. Please remove one of them.")},"missing-precache-entry":function(a){return"Unable to find a precached response in "+a.cacheName+" for "+a.url+"."},"cross-origin-copy-response":function(a){return"workbox-core.copyResponse() can only be used with same-origin "+("responses. It was passed a response with origin "+a.origin+".")}}};
shadow$provide[18]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.messageGenerator=void 0;b(17);b(15);a.messageGenerator=function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];b=a;0<c.length&&(b+=" :: "+JSON.stringify(c));return b}};
shadow$provide[19]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.WorkboxError=void 0;var c=b(18);b(15);h=function(a){function b(a,f){d.shadow.js.babel.classCallCheck(this,b);var g=(0,c.messageGenerator)(a,f);g=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,g));g.name=a;g.details=f;return g}d.shadow.js.babel.inherits(b,a);return b}(Error);a.WorkboxError=h};
shadow$provide[20]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.assert=void 0;b(19);b(15);a.assert=null};
shadow$provide[21]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.quotaErrorCallbacks=void 0;b(15);d=new Set;a.quotaErrorCallbacks=d};
shadow$provide[22]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.registerQuotaErrorCallback=void 0;b(16);b(20);var c=b(21);b(15);a.registerQuotaErrorCallback=function(a){c.quotaErrorCallbacks.add(a)}};
shadow$provide[23]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.cacheNames=void 0;b(15);var c={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},g=function(a){return[c.prefix,a,c.suffix].filter(function(a){return a&&0<a.length}).join("-")},r=function(a){var b=!0,d=!1,g=void 0;try{for(var v=Object.keys(c)[Symbol.iterator](),k;!(b=(k=v.next()).done);b=!0)a(k.value)}catch(n){d=
!0,g=n}finally{try{!b&&v.return&&v.return()}finally{if(d)throw g;}}};a.cacheNames={updateDetails:function(a){r(function(b){"string"===typeof a[b]&&(c[b]=a[b])})},getGoogleAnalyticsName:function(a){return a||g(c.googleAnalytics)},getPrecacheName:function(a){return a||g(c.precache)},getPrefix:function(){return c.prefix},getRuntimeName:function(a){return a||g(c.runtime)},getSuffix:function(){return c.suffix}}};
shadow$provide[24]=function(d,h,b,l,a,m){function c(a,b){a=new URL(a);var c=!0,f=!1,d=void 0;try{for(var g=b[Symbol.iterator](),v;!(c=(v=g.next()).done);c=!0)a.searchParams.delete(v.value)}catch(k){f=!0,d=k}finally{try{!c&&g.return&&g.return()}finally{if(f)throw d;}}return a.href}Object.defineProperty(a,"__esModule",{value:!0});a.cacheMatchIgnoreParams=void 0;h=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function v(a,b,d,g){var f,n,p,q,u,e,w,z,h,t;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=
k.next){case 0:f=c(b.url,d);if(b.url!==f){k.next=3;break}return k.abrupt("return",a.match(b,g));case 3:return n=Object.assign(Object.assign({},g),{ignoreSearch:!0}),k.next=6,a.keys(b,n);case 6:p=k.sent,q=!0,u=!1,e=void 0,k.prev=10,w=p[Symbol.iterator]();case 12:if(q=(z=w.next()).done){k.next=20;break}h=z.value;t=c(h.url,d);if(f!==t){k.next=17;break}return k.abrupt("return",a.match(h,g));case 17:q=!0;k.next=12;break;case 20:k.next=26;break;case 22:k.prev=22,k.t0=k["catch"](10),u=!0,e=k.t0;case 26:k.prev=
26,k.prev=27,!q&&w.return&&w.return();case 29:k.prev=29;if(!u){k.next=32;break}throw e;case 32:return k.finish(29);case 33:return k.finish(26);case 34:return k.abrupt("return");case 35:case "end":return k.stop()}},v,this,[[10,22,26,34],[27,,29,33]])}));return function(b,c,d,g){return a.apply(this,arguments)}}();b(15);a.cacheMatchIgnoreParams=h};
shadow$provide[25]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.canConstructReadableStream=void 0;b(15);var c=void 0;a.canConstructReadableStream=function(){if(void 0===c)try{new ReadableStream({start:function(){}}),c=!0}catch(g){c=!1}return c}};
shadow$provide[26]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.canConstructResponseFromBodyStream=void 0;b(15);var c=void 0;a.canConstructResponseFromBodyStream=function(){if(void 0===c){var a=new Response("");if("body"in a)try{new Response(a.body),c=!0}catch(r){c=!1}c=!1}return c}};
shadow$provide[27]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.dontWaitFor=function(a){void a.then(function(){})};b(15)};
shadow$provide[28]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.Deferred=void 0;b(15);a.Deferred=function g(){var a=this;d.shadow.js.babel.classCallCheck(this,g);this.promise=new Promise(function(b,f){a.resolve=b;a.reject=f})}};
shadow$provide[29]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.executeQuotaErrorCallbacks=void 0;h=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(){var a,b,d,g,k,n;return regeneratorRuntime.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:a=!0,b=!1,d=void 0,f.prev=4,g=c.quotaErrorCallbacks[Symbol.iterator]();case 6:if(a=(k=g.next()).done){f.next=14;break}n=k.value;f.next=10;return n();case 10:case 11:a=!0;f.next=6;break;case 14:f.next=
20;break;case 16:f.prev=16,f.t0=f["catch"](4),b=!0,d=f.t0;case 20:f.prev=20,f.prev=21,!a&&g.return&&g.return();case 23:f.prev=23;if(!b){f.next=26;break}throw d;case 26:return f.finish(23);case 27:return f.finish(20);case 28:case 29:case "end":return f.stop()}},t,this,[[4,16,20,28],[21,,23,27]])}));return function(){return a.apply(this,arguments)}}();b(16);var c=b(21);b(15);a.executeQuotaErrorCallbacks=h};
shadow$provide[30]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.getFriendlyURL=void 0;b(15);a.getFriendlyURL=function(a){return(new URL(String(a),location.href)).href.replace(new RegExp("^"+location.origin),"")}};
shadow$provide[31]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.timeout=function(a){return new Promise(function(b){return setTimeout(b,a)})};b(15)};
shadow$provide[32]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.resultingClientExists=void 0;a.resultingClientExists=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function q(a){var b,f,d,n;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:if(a){k.next=2;break}return k.abrupt("return");case 2:return k.next=4,self.clients.matchAll({type:"window"});case 4:b=k.sent,f=new Set(b.map(function(a){return a.id})),d=void 0,
n=performance.now();case 8:if(!(performance.now()-n<g)){k.next=19;break}k.next=11;return self.clients.matchAll({type:"window"});case 11:b=k.sent;d=b.find(function(b){return a?b.id===a:!f.has(b.id)});if(!d){k.next=15;break}return k.abrupt("break",19);case 15:return k.next=17,(0,c.timeout)(100);case 17:k.next=8;break;case 19:return k.abrupt("return",d);case 20:case "end":return k.stop()}},q,this)}));return function(b){return a.apply(this,arguments)}}();var c=b(31);b(15);var g=2E3};
shadow$provide[33]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.waitUntil=void 0;b(15);a.waitUntil=function(a,b){b=b();a.waitUntil(b);return b}};
shadow$provide[34]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.WorkboxError=a.waitUntil=a.timeout=a.resultingClientExists=a.logger=a.getFriendlyURL=a.executeQuotaErrorCallbacks=a.Deferred=a.dontWaitFor=a.canConstructResponseFromBodyStream=a.canConstructReadableStream=a.cacheNames=a.cacheMatchIgnoreParams=a.assert=void 0;d=b(20);h=b(23);l=b(24);m=b(25);var c=b(26),g=b(27),r=b(28),t=b(29),f=b(30),q=b(16),u=b(32),v=b(31),k=b(33),n=b(19);b(15);a.assert=d.assert;a.cacheMatchIgnoreParams=
l.cacheMatchIgnoreParams;a.cacheNames=h.cacheNames;a.canConstructReadableStream=m.canConstructReadableStream;a.canConstructResponseFromBodyStream=c.canConstructResponseFromBodyStream;a.dontWaitFor=g.dontWaitFor;a.Deferred=r.Deferred;a.executeQuotaErrorCallbacks=t.executeQuotaErrorCallbacks;a.getFriendlyURL=f.getFriendlyURL;a.logger=q.logger;a.resultingClientExists=u.resultingClientExists;a.timeout=v.timeout;a.waitUntil=k.waitUntil;a.WorkboxError=n.WorkboxError};
shadow$provide[35]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.cacheNames=void 0;var c=b(23);b(15);a.cacheNames={get googleAnalytics(){return c.cacheNames.getGoogleAnalyticsName()},get precache(){return c.cacheNames.getPrecacheName()},get prefix(){return c.cacheNames.getPrefix()},get runtime(){return c.cacheNames.getRuntimeName()},get suffix(){return c.cacheNames.getSuffix()}}};
shadow$provide[36]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.copyResponse=void 0;h=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function u(a,b){var f,d,n,p,q,h;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:f=null;a.url&&(d=new URL(a.url),f=d.origin);if(f===self.location.origin){k.next=4;break}throw new g.WorkboxError("cross-origin-copy-response",{origin:f});case 4:n=a.clone();p={headers:new Headers(n.headers),
status:n.status,statusText:n.statusText};q=b?b(p):p;if(!(0,c.canConstructResponseFromBodyStream)()){k.next=11;break}k.t0=n.body;k.next=14;break;case 11:return k.next=13,n.blob();case 13:k.t0=k.sent;case 14:return h=k.t0,k.abrupt("return",new Response(h,q));case 16:case "end":return k.stop()}},u,this)}));return function(b,c){return a.apply(this,arguments)}}();var c=b(26),g=b(19);b(15);a.copyResponse=h};
shadow$provide[37]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.clientsClaim=void 0;b(15);a.clientsClaim=function(){self.addEventListener("activate",function(){return self.clients.claim()})}};
shadow$provide[38]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.setCacheNameDetails=void 0;b(20);var c=b(23);b(19);b(15);a.setCacheNameDetails=function(a){c.cacheNames.updateDetails(a)}};
shadow$provide[39]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.skipWaiting=void 0;b(16);b(15);a.skipWaiting=function(){void self.skipWaiting()}};
shadow$provide[40]=function(d,h,b,l,a,m){b(15)};
shadow$provide[41]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.skipWaiting=a.setCacheNameDetails=a.registerQuotaErrorCallback=a.copyResponse=a.clientsClaim=a.cacheNames=a._private=void 0;var c=b(40);Object.keys(c).forEach(function(b){"default"!==b&&"__esModule"!==b&&Object.defineProperty(a,b,{enumerable:!0,get:function(){return c[b]}})});h=b(22);l=b(34);d=d.shadow.js.babel.interopRequireWildcard(l);l=b(35);m=b(36);var g=b(37),r=b(38),t=b(39);b(15);a._private=d;a.cacheNames=
l.cacheNames;a.clientsClaim=g.clientsClaim;a.copyResponse=m.copyResponse;a.registerQuotaErrorCallback=h.registerQuotaErrorCallback;a.setCacheNameDetails=r.setCacheNameDetails;a.skipWaiting=t.skipWaiting};
shadow$provide[42]=function(d,h,b,l,a,m){try{self["workbox:routing:6.4.0"]&&_()}catch(c){}};
shadow$provide[43]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.validMethods=a.defaultMethod=void 0;b(42);a.defaultMethod="GET";a.validMethods="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[44]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.normalizeHandler=void 0;b(20);b(42);a.normalizeHandler=function(a){return a&&"object"===("undefined"===typeof a?"undefined":d.shadow.js.babel.typeof(a))?a:{handle:a}}};
shadow$provide[45]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.Route=void 0;b(20);var c=b(43),g=b(44);b(42);h=function(){function a(b,f){var q=2<arguments.length&&void 0!==arguments[2]?arguments[2]:c.defaultMethod;d.shadow.js.babel.classCallCheck(this,a);this.handler=(0,g.normalizeHandler)(f);this.match=b;this.method=q}d.shadow.js.babel.createClass(a,[{key:"setCatchHandler",value:function(a){this.catchHandler=(0,g.normalizeHandler)(a)}}]);return a}();a.Route=h};
shadow$provide[46]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.NavigationRoute=void 0;b(20);b(16);h=b(45);b(42);b=function(a){function b(a){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{},f=c.allowlist;f=void 0===f?[/./]:f;c=c.denylist;c=void 0===c?[]:c;d.shadow.js.babel.classCallCheck(this,b);var g=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,function(a){return g._match(a)},a));g._allowlist=f;g._denylist=
c;return g}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_match",value:function(a){var b=a.url;if((a=a.request)&&"navigate"!==a.mode)return!1;var c=b.pathname+b.search;b=!0;a=!1;var d=void 0;try{for(var g=this._denylist[Symbol.iterator](),h;!(b=(h=g.next()).done);b=!0)if(h.value.test(c))return!1}catch(k){a=!0,d=k}finally{try{!b&&g.return&&g.return()}finally{if(a)throw d;}}return this._allowlist.some(function(a){return a.test(c)})?!0:!1}}]);return b}(h.Route);a.NavigationRoute=
b};
shadow$provide[47]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.RegExpRoute=void 0;b(20);b(16);h=b(45);b(42);b=function(a){function b(a,c,f){d.shadow.js.babel.classCallCheck(this,b);return d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,function(b){b=b.url;var c=a.exec(b.href);if(c&&(b.origin===location.origin||0===c.index))return c.slice(1)},c,f))}d.shadow.js.babel.inherits(b,a);return b}(h.Route);a.RegExpRoute=b};
shadow$provide[48]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.Router=void 0;b(20);b(30);var c=b(43);b(16);var g=b(44),r=b(19);b(42);h=function(){function a(){d.shadow.js.babel.classCallCheck(this,a);this._routes=new Map;this._defaultHandlerMap=new Map}d.shadow.js.babel.createClass(a,[{key:"addFetchListener",value:function(){var a=this;self.addEventListener("fetch",function(b){var c=a.handleRequest({request:b.request,event:b});c&&b.respondWith(c)})}},{key:"addCacheListener",
value:function(){var a=this;self.addEventListener("message",function(b){if(b.data&&"CACHE_URLS"===b.data.type){var c=Promise.all(b.data.payload.urlsToCache.map(function(c){"string"===typeof c&&(c=[c]);c=new (Function.prototype.bind.apply(Request,[null].concat(d.shadow.js.babel.toConsumableArray(c))));return a.handleRequest({request:c,event:b})}));b.waitUntil(c);b.ports&&b.ports[0]&&void c.then(function(){return b.ports[0].postMessage(!0)})}})}},{key:"handleRequest",value:function(a){var b=this,c=
a.request,f=a.event,k=new URL(c.url,location.href);if(k.protocol.startsWith("http")){a=this.findMatchingRoute({event:f,request:c,sameOrigin:k.origin===location.origin,url:k});var g=a.params,p=(a=a.route)&&a.handler,h=c.method;!p&&this._defaultHandlerMap.has(h)&&(p=this._defaultHandlerMap.get(h));if(p){h=void 0;try{h=p.handle({url:k,request:c,event:f,params:g})}catch(e){h=Promise.reject(e)}var x=a&&a.catchHandler;h instanceof Promise&&(this._catchHandler||x)&&(h=h.catch(function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function L(a){return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=
d.next){case 0:if(!x){d.next=11;break}d.prev=2;d.next=5;return x.handle({url:k,request:c,event:f,params:g});case 5:return d.abrupt("return",d.sent);case 8:d.prev=8,d.t0=d["catch"](2),d.t0 instanceof Error&&(a=d.t0);case 11:if(!b._catchHandler){d.next=14;break}return d.abrupt("return",b._catchHandler.handle({url:k,request:c,event:f}));case 14:throw a;case 15:case "end":return d.stop()}},L,b,[[2,8]])}));return function(b){return a.apply(this,arguments)}}()));return h}}}},{key:"findMatchingRoute",value:function(a){var b=
a.url,c=a.sameOrigin,f=a.request;a=a.event;var d=this._routes.get(f.method)||[],g=!0,p=!1,h=void 0;try{for(var x=d[Symbol.iterator](),e;!(g=(e=x.next()).done);g=!0){var w=e.value;d=void 0;var z=w.match({url:b,sameOrigin:c,request:f,event:a});if(z)return d=z,Array.isArray(d)&&0===d.length?d=void 0:z.constructor===Object&&0===Object.keys(z).length?d=void 0:"boolean"===typeof z&&(d=void 0),{route:w,params:d}}}catch(L){p=!0,h=L}finally{try{!g&&x.return&&x.return()}finally{if(p)throw h;}}return{}}},{key:"setDefaultHandler",
value:function(a){this._defaultHandlerMap.set(1<arguments.length&&void 0!==arguments[1]?arguments[1]:c.defaultMethod,(0,g.normalizeHandler)(a))}},{key:"setCatchHandler",value:function(a){this._catchHandler=(0,g.normalizeHandler)(a)}},{key:"registerRoute",value:function(a){this._routes.has(a.method)||this._routes.set(a.method,[]);this._routes.get(a.method).push(a)}},{key:"unregisterRoute",value:function(a){if(!this._routes.has(a.method))throw new r.WorkboxError("unregister-route-but-not-found-with-method",
{method:a.method});var b=this._routes.get(a.method).indexOf(a);if(-1<b)this._routes.get(a.method).splice(b,1);else throw new r.WorkboxError("unregister-route-route-not-registered");}},{key:"routes",get:function(){return this._routes}}]);return a}();a.Router=h};
shadow$provide[49]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.getOrCreateDefaultRouter=void 0;var c=b(48);b(42);var g=void 0;a.getOrCreateDefaultRouter=function(){g||(g=new c.Router,g.addFetchListener(),g.addCacheListener());return g}};
shadow$provide[50]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.registerRoute=void 0;b(16);var c=b(19),g=b(45),r=b(47),t=b(49);b(42);a.registerRoute=function(a,b,d){var f=void 0;if("string"===typeof a){var k=new URL(a,location.href);f=new g.Route(function(a){return a.url.href===k.href},b,d)}else if(a instanceof RegExp)f=new r.RegExpRoute(a,b,d);else if("function"===typeof a)f=new g.Route(a,b,d);else if(a instanceof g.Route)f=a;else throw new c.WorkboxError("unsupported-route-type",
{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,t.getOrCreateDefaultRouter)().registerRoute(f);return f}};
shadow$provide[51]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.setCatchHandler=void 0;var c=b(49);b(42);a.setCatchHandler=function(a){(0,c.getOrCreateDefaultRouter)().setCatchHandler(a)}};
shadow$provide[52]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.setDefaultHandler=void 0;var c=b(49);b(42);a.setDefaultHandler=function(a){(0,c.getOrCreateDefaultRouter)().setDefaultHandler(a)}};
shadow$provide[53]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.setDefaultHandler=a.setCatchHandler=a.Router=a.Route=a.registerRoute=a.RegExpRoute=a.NavigationRoute=void 0;d=b(46);h=b(47);l=b(50);m=b(45);var c=b(48),g=b(51),r=b(52);b(42);a.NavigationRoute=d.NavigationRoute;a.RegExpRoute=h.RegExpRoute;a.registerRoute=l.registerRoute;a.Route=m.Route;a.Router=c.Router;a.setCatchHandler=g.setCatchHandler;a.setDefaultHandler=r.setDefaultHandler};
shadow$provide[54]=function(d,h,b,l,a,m){try{self["workbox:precaching:6.4.0"]&&_()}catch(c){}};
shadow$provide[55]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.createCacheKey=function(a){if(!a)throw new c.WorkboxError("add-to-cache-list-unexpected-type",{entry:a});if("string"===typeof a){var b=new URL(a,location.href);return{cacheKey:b.href,url:b.href}}b=a.revision;var d=a.url;if(!d)throw new c.WorkboxError("add-to-cache-list-unexpected-type",{entry:a});if(!b)return b=new URL(d,location.href),{cacheKey:b.href,url:b.href};a=new URL(d,location.href);d=new URL(d,location.href);
a.searchParams.set(g,b);return{cacheKey:a.href,url:d.href}};var c=b(19);b(54);var g="__WB_REVISION__"};
shadow$provide[56]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheInstallReportPlugin=void 0;b(54);a.PrecacheInstallReportPlugin=function g(){var a=this;d.shadow.js.babel.classCallCheck(this,g);this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=function(){var b=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function u(b){var d=b.request,g=b.state;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:g&&(g.originalRequest=
d);case 1:case "end":return a.stop()}},u,a)}));return function(a){return b.apply(this,arguments)}}();this.cachedResponseWillBeUsed=function(){var b=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function u(b){var d=b.event,g=b.state,n=b.cachedResponse,p;return regeneratorRuntime.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return"install"===d.type&&g&&g.originalRequest&&g.originalRequest instanceof Request&&(p=g.originalRequest.url,n?a.notUpdatedURLs.push(p):a.updatedURLs.push(p)),
b.abrupt("return",n);case 2:case "end":return b.stop()}},u,a)}));return function(a){return b.apply(this,arguments)}}()}};
shadow$provide[57]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheCacheKeyPlugin=void 0;b(54);a.PrecacheCacheKeyPlugin=function r(a){var b=this;a=a.precacheController;d.shadow.js.babel.classCallCheck(this,r);this.cacheKeyWillBeUsed=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function v(a){var d=a.request,f=a.params,g;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return g=(null===f||void 0===f?void 0:
f.cacheKey)||b._precacheController.getCacheKeyForURL(d.url),a.abrupt("return",g?new Request(g,{headers:d.headers}):d);case 2:case "end":return a.stop()}},v,b)}));return function(b){return a.apply(this,arguments)}}();this._precacheController=a}};
shadow$provide[58]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.printCleanupDetails=function(a){var b=a.length;if(0<b){c.logger.groupCollapsed("During precaching cleanup, "+(b+" cached ")+("request"+(1===b?" was":"s were")+" deleted."));c.logger.groupCollapsed("Deleted Cache Requests");b=!0;var d=!1,f=void 0;try{for(var g=a[Symbol.iterator](),h;!(b=(h=g.next()).done);b=!0)c.logger.log(h.value)}catch(v){d=!0,f=v}finally{try{!b&&g.return&&g.return()}finally{if(d)throw f;
}}c.logger.groupEnd();c.logger.groupEnd()}};var c=b(16);b(54)};
shadow$provide[59]=function(d,h,b,l,a,m){function c(a,b){if(0!==b.length){g.logger.groupCollapsed(a);a=!0;var c=!1,d=void 0;try{for(var h=b[Symbol.iterator](),v;!(a=(v=h.next()).done);a=!0)g.logger.log(v.value)}catch(k){c=!0,d=k}finally{try{!a&&h.return&&h.return()}finally{if(c)throw d;}}g.logger.groupEnd()}}Object.defineProperty(a,"__esModule",{value:!0});a.printInstallDetails=function(a,b){var d=a.length,h=b.length;if(d||h)d="Precaching "+d+" file"+(1===d?"":"s")+".",0<h&&(d+=" "+h+" "+("file"+
(1===h?" is":"s are")+" already cached.")),g.logger.groupCollapsed(d),c("View newly precached URLs.",a),c("View previously precached URLs.",b),g.logger.groupEnd()};var g=b(16);b(54)};
shadow$provide[60]=function(d,h,b,l,a,m){try{self["workbox:strategies:6.4.0"]&&_()}catch(c){}};
shadow$provide[61]=function(d,h,b,l,a,m){function c(a){return"string"===typeof a?new Request(a):a}Object.defineProperty(a,"__esModule",{value:!0});a.StrategyHandler=void 0;b(20);var g=b(24),r=b(28),t=b(29),f=b(30),q=b(16),u=b(31),v=b(19);b(60);h=function(){function a(b,c){d.shadow.js.babel.classCallCheck(this,a);this._cacheKeys={};Object.assign(this,c);this.event=c.event;this._strategy=b;this._handlerDeferred=new r.Deferred;this._extendLifetimePromises=[];this._plugins=[].concat(d.shadow.js.babel.toConsumableArray(b.plugins));
this._pluginStateMap=new Map;b=!0;c=!1;var f=void 0;try{for(var g=this._plugins[Symbol.iterator](),k;!(b=(k=g.next()).done);b=!0)this._pluginStateMap.set(k.value,{})}catch(w){c=!0,f=w}finally{try{!b&&g.return&&g.return()}finally{if(c)throw f;}}this.event.waitUntil(this._handlerDeferred.promise)}d.shadow.js.babel.createClass(a,[{key:"fetch",value:function(a){function b(b){return a.apply(this,arguments)}b.toString=function(){return a.toString()};return b}(function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(a){var b,
d,f,g,k,h,n,q,l,B,m,u,y,r,t,E,G,O;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:b=this.event;d=c(a);if(!("navigate"===d.mode&&b instanceof FetchEvent&&b.preloadResponse)){e.next=9;break}e.next=5;return b.preloadResponse;case 5:f=e.sent;if(!f){e.next=9;break}return e.abrupt("return",f);case 9:g=this.hasCallback("fetchDidFail")?d.clone():null,e.prev=10,k=!0,h=!1,n=void 0,e.prev=14,q=this.iterateCallbacks("requestWillFetch")[Symbol.iterator]();case 16:if(k=(l=q.next()).done){e.next=
24;break}B=l.value;e.next=20;return B({request:d.clone(),event:b});case 20:d=e.sent;case 21:k=!0;e.next=16;break;case 24:e.next=30;break;case 26:e.prev=26,e.t0=e["catch"](14),h=!0,n=e.t0;case 30:e.prev=30,e.prev=31,!k&&q.return&&q.return();case 33:e.prev=33;if(!h){e.next=36;break}throw n;case 36:return e.finish(33);case 37:return e.finish(30);case 38:e.next=44;break;case 40:e.prev=40;e.t1=e["catch"](10);if(!(e.t1 instanceof Error)){e.next=44;break}throw new v.WorkboxError("plugin-error-request-will-fetch",
{thrownErrorMessage:e.t1.message});case 44:return m=d.clone(),e.prev=45,u=void 0,e.next=49,fetch(d,"navigate"===d.mode?void 0:this._strategy.fetchOptions);case 49:u=e.sent,y=!0,r=!1,t=void 0,e.prev=54,E=this.iterateCallbacks("fetchDidSucceed")[Symbol.iterator]();case 56:if(y=(G=E.next()).done){e.next=64;break}O=G.value;e.next=60;return O({event:b,request:m,response:u});case 60:u=e.sent;case 61:y=!0;e.next=56;break;case 64:e.next=70;break;case 66:e.prev=66,e.t2=e["catch"](54),r=!0,t=e.t2;case 70:e.prev=
70,e.prev=71,!y&&E.return&&E.return();case 73:e.prev=73;if(!r){e.next=76;break}throw t;case 76:return e.finish(73);case 77:return e.finish(70);case 78:return e.abrupt("return",u);case 81:e.prev=81;e.t3=e["catch"](45);if(!g){e.next=87;break}e.next=87;return this.runCallbacks("fetchDidFail",{error:e.t3,event:b,originalRequest:g.clone(),request:m.clone()});case 87:throw e.t3;case 88:case "end":return e.stop()}},x,this,[[10,40],[14,26,30,38],[31,,33,37],[45,81],[54,66,70,78],[71,,73,77]])}));return function(b){return a.apply(this,
arguments)}}())},{key:"fetchAndCachePut",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(a){var b,c;return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,this.fetch(a);case 2:return b=d.sent,c=b.clone(),void this.waitUntil(this.cachePut(a,c)),d.abrupt("return",b);case 6:case "end":return d.stop()}},x,this)}));return function(b){return a.apply(this,arguments)}}()},{key:"cacheMatch",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(a){var b,
d,f,g,k,h,n,q,v,B,l,u,m;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return b=c(a),d=void 0,f=this._strategy,g=f.cacheName,k=f.matchOptions,e.next=5,this.getCacheKey(b,"read");case 5:return h=e.sent,n=Object.assign(Object.assign({},k),{cacheName:g}),e.next=9,caches.match(h,n);case 9:d=e.sent,q=!0,v=!1,B=void 0,e.prev=14,l=this.iterateCallbacks("cachedResponseWillBeUsed")[Symbol.iterator]();case 16:if(q=(u=l.next()).done){e.next=27;break}m=u.value;e.next=20;return m({cacheName:g,
matchOptions:k,cachedResponse:d,request:h,event:this.event});case 20:e.t0=e.sent;if(e.t0){e.next=23;break}e.t0=void 0;case 23:d=e.t0;case 24:q=!0;e.next=16;break;case 27:e.next=33;break;case 29:e.prev=29,e.t1=e["catch"](14),v=!0,B=e.t1;case 33:e.prev=33,e.prev=34,!q&&l.return&&l.return();case 36:e.prev=36;if(!v){e.next=39;break}throw B;case 39:return e.finish(36);case 40:return e.finish(33);case 41:return e.abrupt("return",d);case 42:case "end":return e.stop()}},x,this,[[14,29,33,41],[34,,36,40]])}));
return function(b){return a.apply(this,arguments)}}()},{key:"cachePut",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function e(a,b){var d,k,h,n,x,l,m,r,B,y,K,J,I,C,E,G;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return d=c(a),e.next=3,(0,u.timeout)(0);case 3:return e.next=5,this.getCacheKey(d,"write");case 5:k=e.sent;e.next=11;break;case 9:(h=b.headers.get("Vary"))&&q.logger.debug("The response for "+(0,f.getFriendlyURL)(k.url)+
" "+("has a 'Vary: "+h+"' header. ")+"Consider setting the {ignoreVary: true} option on your strategy to ensure cache matching and deletion works as expected.");case 11:if(b){e.next=14;break}throw new v.WorkboxError("cache-put-with-no-response",{url:(0,f.getFriendlyURL)(k.url)});case 14:return e.next=16,this._ensureResponseSafeToCache(b);case 16:if(n=e.sent){e.next=20;break}return e.abrupt("return",!1);case 20:return x=this._strategy,l=x.cacheName,m=x.matchOptions,e.next=23,self.caches.open(l);case 23:r=
e.sent;B=this.hasCallback("cacheDidUpdate");if(!B){e.next=31;break}e.next=28;return(0,g.cacheMatchIgnoreParams)(r,k.clone(),["__WB_REVISION__"],m);case 28:e.t0=e.sent;e.next=32;break;case 31:e.t0=null;case 32:return y=e.t0,e.prev=34,e.next=37,r.put(k,B?n.clone():n);case 37:e.next=46;break;case 39:e.prev=39;e.t1=e["catch"](34);if(!(e.t1 instanceof Error)){e.next=46;break}if("QuotaExceededError"!==e.t1.name){e.next=45;break}e.next=45;return(0,t.executeQuotaErrorCallbacks)();case 45:throw e.t1;case 46:K=
!0,J=!1,I=void 0,e.prev=49,C=this.iterateCallbacks("cacheDidUpdate")[Symbol.iterator]();case 51:if(K=(E=C.next()).done){e.next=58;break}G=E.value;e.next=55;return G({cacheName:l,oldResponse:y,newResponse:n.clone(),request:k,event:this.event});case 55:K=!0;e.next=51;break;case 58:e.next=64;break;case 60:e.prev=60,e.t2=e["catch"](49),J=!0,I=e.t2;case 64:e.prev=64,e.prev=65,!K&&C.return&&C.return();case 67:e.prev=67;if(!J){e.next=70;break}throw I;case 70:return e.finish(67);case 71:return e.finish(64);
case 72:return e.abrupt("return",!0);case 73:case "end":return e.stop()}},e,this,[[34,39],[49,60,64,72],[65,,67,71]])}));return function(b,c){return a.apply(this,arguments)}}()},{key:"getCacheKey",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function e(a,b){var d,f,g,k,h,n,x,l;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:d=a.url+" | "+b;if(this._cacheKeys[d]){e.next=33;break}f=a;g=!0;k=!1;h=void 0;e.prev=6;n=this.iterateCallbacks("cacheKeyWillBeUsed")[Symbol.iterator]();
case 8:if(g=(x=n.next()).done){e.next=18;break}l=x.value;e.t0=c;e.next=13;return l({mode:b,request:f,event:this.event,params:this.params});case 13:e.t1=e.sent,f=(0,e.t0)(e.t1);case 15:g=!0;e.next=8;break;case 18:e.next=24;break;case 20:e.prev=20,e.t2=e["catch"](6),k=!0,h=e.t2;case 24:e.prev=24,e.prev=25,!g&&n.return&&n.return();case 27:e.prev=27;if(!k){e.next=30;break}throw h;case 30:return e.finish(27);case 31:return e.finish(24);case 32:this._cacheKeys[d]=f;case 33:return e.abrupt("return",this._cacheKeys[d]);
case 34:case "end":return e.stop()}},e,this,[[6,20,24,32],[25,,27,31]])}));return function(b,c){return a.apply(this,arguments)}}()},{key:"hasCallback",value:function(a){var b=!0,c=!1,d=void 0;try{for(var e=this._strategy.plugins[Symbol.iterator](),f;!(b=(f=e.next()).done);b=!0)if(a in f.value)return!0}catch(z){c=!0,d=z}finally{try{!b&&e.return&&e.return()}finally{if(c)throw d;}}return!1}},{key:"runCallbacks",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function e(a,
b){var c,d,f,g,k,h;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:c=!0,d=!1,f=void 0,e.prev=3,g=this.iterateCallbacks(a)[Symbol.iterator]();case 5:if(c=(k=g.next()).done){e.next=12;break}h=k.value;e.next=9;return h(b);case 9:c=!0;e.next=5;break;case 12:e.next=18;break;case 14:e.prev=14,e.t0=e["catch"](3),d=!0,f=e.t0;case 18:e.prev=18,e.prev=19,!c&&g.return&&g.return();case 21:e.prev=21;if(!d){e.next=24;break}throw f;case 24:return e.finish(21);case 25:return e.finish(18);
case 26:case "end":return e.stop()}},e,this,[[3,14,18,26],[19,,21,25]])}));return function(b,c){return a.apply(this,arguments)}}()},{key:"iterateCallbacks",value:regeneratorRuntime.mark(function y(a){var b=this,c,d,f,g,k,h,p;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:c=regeneratorRuntime.mark(function M(c){var d,e;return regeneratorRuntime.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:if("function"!==typeof c[a]){f.next=5;break}d=b._pluginStateMap.get(c);
e=function(b){b=Object.assign(Object.assign({},b),{state:d});return c[a](b)};f.next=5;return e;case 5:case "end":return f.stop()}},M,b)}),d=!0,f=!1,g=void 0,e.prev=4,k=this._strategy.plugins[Symbol.iterator]();case 6:if(d=(h=k.next()).done){e.next=12;break}p=h.value;return e.delegateYield(c(p),"t0",9);case 9:d=!0;e.next=6;break;case 12:e.next=18;break;case 14:e.prev=14,e.t1=e["catch"](4),f=!0,g=e.t1;case 18:e.prev=18,e.prev=19,!d&&k.return&&k.return();case 21:e.prev=21;if(!f){e.next=24;break}throw g;
case 24:return e.finish(21);case 25:return e.finish(18);case 26:case "end":return e.stop()}},y,this,[[4,14,18,26],[19,,21,25]])})},{key:"waitUntil",value:function(a){this._extendLifetimePromises.push(a);return a}},{key:"doneWaiting",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(){var a;return regeneratorRuntime.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:a=void 0;case 1:if(!(a=this._extendLifetimePromises.shift())){b.next=6;break}b.next=4;return a;
case 4:b.next=1;break;case 6:case "end":return b.stop()}},x,this)}));return function(){return a.apply(this,arguments)}}()},{key:"destroy",value:function(){this._handlerDeferred.resolve(null)}},{key:"_ensureResponseSafeToCache",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function e(a){var b,c,d,f,g,k,h,p;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:b=a,c=!1,d=!0,f=!1,g=void 0,e.prev=5,k=this.iterateCallbacks("cacheWillUpdate")[Symbol.iterator]();
case 7:if(d=(h=k.next()).done){e.next=21;break}p=h.value;e.next=11;return p({request:this.request,response:b,event:this.event});case 11:e.t0=e.sent;if(e.t0){e.next=14;break}e.t0=void 0;case 14:b=e.t0;c=!0;if(b){e.next=18;break}return e.abrupt("break",21);case 18:d=!0;e.next=7;break;case 21:e.next=27;break;case 23:e.prev=23,e.t1=e["catch"](5),f=!0,g=e.t1;case 27:e.prev=27,e.prev=28,!d&&k.return&&k.return();case 30:e.prev=30;if(!f){e.next=33;break}throw g;case 33:return e.finish(30);case 34:return e.finish(27);
case 35:return c||b&&200!==b.status&&(b=void 0),e.abrupt("return",b);case 37:case "end":return e.stop()}},e,this,[[5,23,27,35],[28,,30,34]])}));return function(b){return a.apply(this,arguments)}}()}]);return a}();a.StrategyHandler=h};
shadow$provide[62]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.Strategy=void 0;var c=b(23),g=b(19);b(16);b(30);var r=b(61);b(60);h=function(){function a(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};d.shadow.js.babel.classCallCheck(this,a);this.cacheName=c.cacheNames.getRuntimeName(b.cacheName);this.plugins=b.plugins||[];this.fetchOptions=b.fetchOptions;this.matchOptions=b.matchOptions}d.shadow.js.babel.createClass(a,[{key:"handle",value:function(a){a=
this.handleAll(a);return d.shadow.js.babel.slicedToArray(a,1)[0]}},{key:"handleAll",value:function(a){a instanceof FetchEvent&&(a={event:a,request:a.request});var b=a.event,c="string"===typeof a.request?new Request(a.request):a.request,d=new r.StrategyHandler(this,{event:b,request:c,params:"params"in a?a.params:void 0});a=this._getResponse(d,c,b);b=this._awaitComplete(a,d,c,b);return[a,b]}},{key:"_getResponse",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function n(a,
b,c){var d,f,k,e,h,l,m,v,u,r,t,H,B;return regeneratorRuntime.wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,a.runCallbacks("handlerWillStart",{event:c,request:b});case 2:return d=void 0,n.prev=3,n.next=6,this._handle(b,a);case 6:if((d=n.sent)&&"error"!==d.type){n.next=9;break}throw new g.WorkboxError("no-response",{url:b.url});case 9:n.next=48;break;case 11:n.prev=11;n.t0=n["catch"](3);if(!(n.t0 instanceof Error)){n.next=43;break}f=!0;k=!1;e=void 0;n.prev=17;h=a.iterateCallbacks("handlerDidError")[Symbol.iterator]();
case 19:if(f=(l=h.next()).done){n.next=29;break}m=l.value;n.next=23;return m({error:n.t0,event:c,request:b});case 23:d=n.sent;if(!d){n.next=26;break}return n.abrupt("break",29);case 26:f=!0;n.next=19;break;case 29:n.next=35;break;case 31:n.prev=31,n.t1=n["catch"](17),k=!0,e=n.t1;case 35:n.prev=35,n.prev=36,!f&&h.return&&h.return();case 38:n.prev=38;if(!k){n.next=41;break}throw e;case 41:return n.finish(38);case 42:return n.finish(35);case 43:if(d){n.next=47;break}throw n.t0;case 47:case 48:v=!0,u=
!1,r=void 0,n.prev=51,t=a.iterateCallbacks("handlerWillRespond")[Symbol.iterator]();case 53:if(v=(H=t.next()).done){n.next=61;break}B=H.value;n.next=57;return B({event:c,request:b,response:d});case 57:d=n.sent;case 58:v=!0;n.next=53;break;case 61:n.next=67;break;case 63:n.prev=63,n.t2=n["catch"](51),u=!0,r=n.t2;case 67:n.prev=67,n.prev=68,!v&&t.return&&t.return();case 70:n.prev=70;if(!u){n.next=73;break}throw r;case 73:return n.finish(70);case 74:return n.finish(67);case 75:return n.abrupt("return",
d);case 76:case "end":return n.stop()}},n,this,[[3,11],[17,31,35,43],[36,,38,42],[51,63,67,75],[68,,70,74]])}));return function(b,c,d){return a.apply(this,arguments)}}()},{key:"_awaitComplete",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function p(a,b,c,d){var f,g;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return g=f=void 0,e.prev=2,e.next=5,a;case 5:f=e.sent;e.next=10;break;case 8:e.prev=8,e.t0=e["catch"](2);case 10:return e.prev=
10,e.next=13,b.runCallbacks("handlerDidRespond",{event:d,request:c,response:f});case 13:return e.next=15,b.doneWaiting();case 15:e.next=20;break;case 17:e.prev=17,e.t1=e["catch"](10),e.t1 instanceof Error&&(g=e.t1);case 20:return e.next=22,b.runCallbacks("handlerDidComplete",{event:d,request:c,response:f,error:g});case 22:b.destroy();if(!g){e.next=25;break}throw g;case 25:case "end":return e.stop()}},p,this,[[2,8],[10,17]])}));return function(b,c,d,f){return a.apply(this,arguments)}}()}]);return a}();
a.Strategy=h};
shadow$provide[63]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheStrategy=void 0;var c=b(36),g=b(23),r=b(30),t=b(16),f=b(19);h=b(62);b(54);b=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};d.shadow.js.babel.classCallCheck(this,b);a.cacheName=g.cacheNames.getPrecacheName(a.cacheName);var c=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,a));c._fallbackToNetwork=!1===a.fallbackToNetwork?
!1:!0;c.plugins.push(b.copyRedirectedCacheableResponsesPlugin);return c}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(a,b){var c;return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.next=2,b.cacheMatch(a);case 2:c=d.sent;if(!c){d.next=5;break}return d.abrupt("return",c);case 5:if(!b.event||"install"!==b.event.type){d.next=9;break}d.next=
8;return this._handleInstall(a,b);case 8:return d.abrupt("return",d.sent);case 9:return d.next=11,this._handleFetch(a,b);case 11:return d.abrupt("return",d.sent);case 12:case "end":return d.stop()}},y,this)}));return function(b,c){return a.apply(this,arguments)}}()},{key:"_handleFetch",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(a,b){var c,d,g,h,n,p;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:c=void 0;d=b.params||
{};if(!this._fallbackToNetwork){e.next=18;break}g=d.integrity;h=a.integrity;n=!h||h===g;e.next=9;return b.fetch(new Request(a,{integrity:h||g}));case 9:c=e.sent;if(!g||!n){e.next=16;break}this._useDefaultCacheabilityPluginIfNeeded();e.next=14;return b.cachePut(a,c.clone());case 14:case 16:e.next=19;break;case 18:throw new f.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:a.url});case 19:e.next=35;break;case 24:e.t0=e.sent;case 25:p=e.t0,t.logger.groupCollapsed("Precaching is responding to: "+
(0,r.getFriendlyURL)(a.url)),t.logger.log("Serving the precached url: "+(0,r.getFriendlyURL)(p instanceof Request?p.url:p)),t.logger.groupCollapsed("View request details here."),t.logger.log(a),t.logger.groupEnd(),t.logger.groupCollapsed("View response details here."),t.logger.log(c),t.logger.groupEnd(),t.logger.groupEnd();case 35:return e.abrupt("return",c);case 36:case "end":return e.stop()}},y,this)}));return function(b,c){return a.apply(this,arguments)}}()},{key:"_handleInstall",value:function(){var a=
d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(a,b){var c,d;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return this._useDefaultCacheabilityPluginIfNeeded(),e.next=3,b.fetch(a);case 3:return c=e.sent,e.next=6,b.cachePut(a,c.clone());case 6:if(d=e.sent){e.next=9;break}throw new f.WorkboxError("bad-precaching-response",{url:a.url,status:c.status});case 9:return e.abrupt("return",c);case 10:case "end":return e.stop()}},y,this)}));return function(b,
c){return a.apply(this,arguments)}}()},{key:"_useDefaultCacheabilityPluginIfNeeded",value:function(){var a=null,c=0,f=!0,g=!1,h=void 0;try{for(var l=this.plugins.entries()[Symbol.iterator](),e;!(f=(e=l.next()).done);f=!0){var m=d.shadow.js.babel.slicedToArray(e.value,2),q=m[0],r=m[1];r!==b.copyRedirectedCacheableResponsesPlugin&&(r===b.defaultPrecacheCacheabilityPlugin&&(a=q),r.cacheWillUpdate&&c++)}}catch(D){g=!0,h=D}finally{try{!f&&l.return&&l.return()}finally{if(g)throw h;}}0===c?this.plugins.push(b.defaultPrecacheCacheabilityPlugin):
1<c&&null!==a&&this.plugins.splice(a,1)}}]);return b}(h.Strategy);b.defaultPrecacheCacheabilityPlugin={cacheWillUpdate:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function k(a){var b=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(b&&!(400<=b.status)){a.next=2;break}return a.abrupt("return",null);case 2:return a.abrupt("return",b);case 3:case "end":return a.stop()}},k,this)}));return function(b){return a.apply(this,arguments)}}()};
b.copyRedirectedCacheableResponsesPlugin={cacheWillUpdate:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function k(a){var b=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(!b.redirected){a.next=6;break}a.next=3;return(0,c.copyResponse)(b);case 3:a.t0=a.sent;a.next=7;break;case 6:a.t0=b;case 7:return a.abrupt("return",a.t0);case 8:case "end":return a.stop()}},k,this)}));return function(b){return a.apply(this,arguments)}}()};
a.PrecacheStrategy=b};
shadow$provide[64]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheController=void 0;b(20);var c=b(23);b(16);var g=b(19),r=b(33),t=b(55),f=b(56),q=b(57);b(58);b(59);var u=b(63);b(54);h=function(){function a(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{},f=b.cacheName,g=b.plugins;g=void 0===g?[]:g;b=b.fallbackToNetwork;b=void 0===b?!0:b;d.shadow.js.babel.classCallCheck(this,a);this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=
new Map;this._strategy=new u.PrecacheStrategy({cacheName:c.cacheNames.getPrecacheName(f),plugins:[].concat(d.shadow.js.babel.toConsumableArray(g),[new q.PrecacheCacheKeyPlugin({precacheController:this})]),fallbackToNetwork:b});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}d.shadow.js.babel.createClass(a,[{key:"precache",value:function(a){this.addToCacheList(a);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",
this.activate),this._installAndActiveListenersAdded=!0)}},{key:"addToCacheList",value:function(a){var b=[],c=!0,d=!1,f=void 0;try{for(var e=a[Symbol.iterator](),h;!(c=(h=e.next()).done);c=!0){var k=h.value;"string"===typeof k?b.push(k):k&&void 0===k.revision&&b.push(k.url);var l=(0,t.createCacheKey)(k),m=l.cacheKey,q=l.url,r="string"!==typeof k&&k.revision?"reload":"default";if(this._urlsToCacheKeys.has(q)&&this._urlsToCacheKeys.get(q)!==m)throw new g.WorkboxError("add-to-cache-list-conflicting-entries",
{firstEntry:this._urlsToCacheKeys.get(q),secondEntry:m});if("string"!==typeof k&&k.integrity){if(this._cacheKeysToIntegrities.has(m)&&this._cacheKeysToIntegrities.get(m)!==k.integrity)throw new g.WorkboxError("add-to-cache-list-conflicting-integrities",{url:q});this._cacheKeysToIntegrities.set(m,k.integrity)}this._urlsToCacheKeys.set(q,m);this._urlsToCacheModes.set(q,r);if(0<b.length){var u="Workbox is precaching URLs without revision "+("info: "+b.join(", ")+"\nThis is generally NOT safe. ")+"Learn more at https://bit.ly/wb-precache";
console.warn(u)}}}catch(H){d=!0,f=H}finally{try{!c&&e.return&&e.return()}finally{if(d)throw f;}}}},{key:"install",value:function(a){var b=this;return(0,r.waitUntil)(a,d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(){var c,e,g,h,k,n,l,m,q,r,u,t,v,J,I;return regeneratorRuntime.wrap(function(w){for(;;)switch(w.prev=w.next){case 0:c=new f.PrecacheInstallReportPlugin,b.strategy.plugins.push(c),e=!0,g=!1,h=void 0,w.prev=5,k=b._urlsToCacheKeys[Symbol.iterator]();case 7:if(e=(n=k.next()).done){w.next=
20;break}l=n.value;m=d.shadow.js.babel.slicedToArray(l,2);q=m[0];r=m[1];u=b._cacheKeysToIntegrities.get(r);t=b._urlsToCacheModes.get(q);v=new Request(q,{integrity:u,cache:t,credentials:"same-origin"});w.next=17;return Promise.all(b.strategy.handleAll({params:{cacheKey:r},request:v,event:a}));case 17:e=!0;w.next=7;break;case 20:w.next=26;break;case 22:w.prev=22,w.t0=w["catch"](5),g=!0,h=w.t0;case 26:w.prev=26,w.prev=27,!e&&k.return&&k.return();case 29:w.prev=29;if(!g){w.next=32;break}throw h;case 32:return w.finish(29);
case 33:return w.finish(26);case 34:return J=c.updatedURLs,I=c.notUpdatedURLs,w.abrupt("return",{updatedURLs:J,notUpdatedURLs:I});case 37:case "end":return w.stop()}},y,b,[[5,22,26,34],[27,,29,33]])})))}},{key:"activate",value:function(a){var b=this;return(0,r.waitUntil)(a,d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(){var a,c,d,f,g,h,k,n,l,m;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,self.caches.open(b.strategy.cacheName);
case 2:return a=e.sent,e.next=5,a.keys();case 5:c=e.sent,d=new Set(b._urlsToCacheKeys.values()),f=[],g=!0,h=!1,k=void 0,e.prev=11,n=c[Symbol.iterator]();case 13:if(g=(l=n.next()).done){e.next=22;break}m=l.value;if(d.has(m.url)){e.next=19;break}e.next=18;return a.delete(m);case 18:f.push(m.url);case 19:g=!0;e.next=13;break;case 22:e.next=28;break;case 24:e.prev=24,e.t0=e["catch"](11),h=!0,k=e.t0;case 28:e.prev=28,e.prev=29,!g&&n.return&&n.return();case 31:e.prev=31;if(!h){e.next=34;break}throw k;case 34:return e.finish(31);
case 35:return e.finish(28);case 36:return e.abrupt("return",{deletedURLs:f});case 38:case "end":return e.stop()}},y,b,[[11,24,28,36],[29,,31,35]])})))}},{key:"getURLsToCacheKeys",value:function(){return this._urlsToCacheKeys}},{key:"getCachedURLs",value:function(){return[].concat(d.shadow.js.babel.toConsumableArray(this._urlsToCacheKeys.keys()))}},{key:"getCacheKeyForURL",value:function(a){a=new URL(a,location.href);return this._urlsToCacheKeys.get(a.href)}},{key:"getIntegrityForCacheKey",value:function(a){return this._cacheKeysToIntegrities.get(a)}},
{key:"matchPrecache",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(a){var b,c,d;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:b=a instanceof Request?a.url:a;c=this.getCacheKeyForURL(b);if(!c){e.next=7;break}e.next=5;return self.caches.open(this.strategy.cacheName);case 5:return d=e.sent,e.abrupt("return",d.match(c));case 7:return e.abrupt("return",void 0);case 8:case "end":return e.stop()}},y,this)}));return function(b){return a.apply(this,
arguments)}}()},{key:"createHandlerBoundToURL",value:function(a){var b=this,c=this.getCacheKeyForURL(a);if(!c)throw new g.WorkboxError("non-precached-url",{url:a});return function(d){d.request=new Request(a);d.params=Object.assign({cacheKey:c},d.params);return b.strategy.handle(d)}}},{key:"strategy",get:function(){return this._strategy}}]);return a}();a.PrecacheController=h};
shadow$provide[65]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.getOrCreatePrecacheController=void 0;var c=b(64);b(54);var g=void 0;a.getOrCreatePrecacheController=function(){g||(g=new c.PrecacheController);return g}};
shadow$provide[66]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.addPlugins=void 0;var c=b(65);b(54);a.addPlugins=function(a){var b;(b=(0,c.getOrCreatePrecacheController)().strategy.plugins).push.apply(b,d.shadow.js.babel.toConsumableArray(a))}};
shadow$provide[67]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.removeIgnoredSearchParams=function(a){for(var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[],c=function(c){b.some(function(a){return a.test(c)})&&a.searchParams.delete(c)},h=[].concat(d.shadow.js.babel.toConsumableArray(a.searchParams.keys())),f=0;f<h.length;f++)c(h[f]);return a};b(54)};
shadow$provide[68]=function(d,h,b,l,a,m){function c(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{},c=b.ignoreURLParametersMatching,d=void 0===c?[/^utm_/,/^fbclid$/]:c;c=b.directoryIndex;var h=void 0===c?"index.html":c;c=b.cleanURLs;var k=void 0===c?!0:c,n=b.urlManipulation,l,m,t,e,w,z,L,D,A,P,N;return regeneratorRuntime.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return l=new URL(a,location.href),l.hash="",b.next=4,l.href;case 4:return m=(0,g.removeIgnoredSearchParams)(l,
d),b.next=7,m.href;case 7:if(!h||!m.pathname.endsWith("/")){b.next=12;break}t=new URL(m.href);t.pathname+=h;b.next=12;return t.href;case 12:if(!k){b.next=17;break}e=new URL(m.href);e.pathname+=".html";b.next=17;return e.href;case 17:if(!n){b.next=45;break}w=n({url:l});z=!0;L=!1;D=void 0;b.prev=22;A=w[Symbol.iterator]();case 24:if(z=(P=A.next()).done){b.next=31;break}N=P.value;b.next=28;return N.href;case 28:z=!0;b.next=24;break;case 31:b.next=37;break;case 33:b.prev=33,b.t0=b["catch"](22),L=!0,D=
b.t0;case 37:b.prev=37,b.prev=38,!z&&A.return&&A.return();case 40:b.prev=40;if(!L){b.next=43;break}throw D;case 43:return b.finish(40);case 44:return b.finish(37);case 45:case "end":return b.stop()}},r,this,[[22,33,37,45],[38,,40,44]])}Object.defineProperty(a,"__esModule",{value:!0});a.generateURLVariations=c;var g=b(67);b(54);var r=regeneratorRuntime.mark(c)};
shadow$provide[69]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheRoute=void 0;b(16);b(30);h=b(45);var c=b(68);b(54);b=function(a){function b(a,f){d.shadow.js.babel.classCallCheck(this,b);return d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,function(b){b=b.request;var d=a.getURLsToCacheKeys(),g=!0,h=!1,n=void 0;try{for(var l=(0,c.generateURLVariations)(b.url,f)[Symbol.iterator](),m;!(g=(m=l.next()).done);g=!0){var q=
d.get(m.value);if(q){var e=a.getIntegrityForCacheKey(q);return{cacheKey:q,integrity:e}}}}catch(w){h=!0,n=w}finally{try{!g&&l.return&&l.return()}finally{if(h)throw n;}}},a.strategy))}d.shadow.js.babel.inherits(b,a);return b}(h.Route);a.PrecacheRoute=b};
shadow$provide[70]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.addRoute=void 0;var c=b(50),g=b(65),r=b(69);b(54);a.addRoute=function(a){var b=(0,g.getOrCreatePrecacheController)();a=new r.PrecacheRoute(b,a);(0,c.registerRoute)(a)}};
shadow$provide[71]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.deleteOutdatedCaches=void 0;b(54);h=function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"-precache-",c,d;return regeneratorRuntime.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return f.next=2,self.caches.keys();case 2:return c=f.sent,d=c.filter(function(c){return c.includes(b)&&c.includes(self.registration.scope)&&
c!==a}),f.next=6,Promise.all(d.map(function(a){return self.caches.delete(a)}));case 6:return f.abrupt("return",d);case 7:case "end":return f.stop()}},t,void 0)}));return function(b){return a.apply(this,arguments)}}();a.deleteOutdatedCaches=h};
shadow$provide[72]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.cleanupOutdatedCaches=void 0;var c=b(23);b(16);var g=b(71);b(54);a.cleanupOutdatedCaches=function(){self.addEventListener("activate",function(a){var b=c.cacheNames.getPrecacheName();a.waitUntil((0,g.deleteOutdatedCaches)(b).then(function(a){}))})}};
shadow$provide[73]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.createHandlerBoundToURL=void 0;var c=b(65);b(54);a.createHandlerBoundToURL=function(a){return(0,c.getOrCreatePrecacheController)().createHandlerBoundToURL(a)}};
shadow$provide[74]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.getCacheKeyForURL=void 0;var c=b(65);b(54);a.getCacheKeyForURL=function(a){return(0,c.getOrCreatePrecacheController)().getCacheKeyForURL(a)}};
shadow$provide[75]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.matchPrecache=void 0;var c=b(65);b(54);a.matchPrecache=function(a){return(0,c.getOrCreatePrecacheController)().matchPrecache(a)}};
shadow$provide[76]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.precache=void 0;var c=b(65);b(54);a.precache=function(a){(0,c.getOrCreatePrecacheController)().precache(a)}};
shadow$provide[77]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.precacheAndRoute=void 0;var c=b(70),g=b(76);b(54);a.precacheAndRoute=function(a,b){(0,g.precache)(a);(0,c.addRoute)(b)}};
shadow$provide[78]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheFallbackPlugin=void 0;var c=b(65);b(54);a.PrecacheFallbackPlugin=function t(a){var b=this,h=a.fallbackURL;a=a.precacheController;d.shadow.js.babel.classCallCheck(this,t);this.handlerDidError=function(){return b._precacheController.matchPrecache(b._fallbackURL)};this._fallbackURL=h;this._precacheController=a||(0,c.getOrCreatePrecacheController)()}};
shadow$provide[79]=function(d,h,b,l,a,m){b(54)};
shadow$provide[80]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheFallbackPlugin=a.PrecacheStrategy=a.PrecacheRoute=a.PrecacheController=a.precacheAndRoute=a.precache=a.matchPrecache=a.getCacheKeyForURL=a.createHandlerBoundToURL=a.cleanupOutdatedCaches=a.addRoute=a.addPlugins=void 0;var c=b(79);Object.keys(c).forEach(function(b){"default"!==b&&"__esModule"!==b&&Object.defineProperty(a,b,{enumerable:!0,get:function(){return c[b]}})});d=b(66);h=b(70);l=b(72);m=b(73);
var g=b(74),r=b(75),t=b(76),f=b(77),q=b(64),u=b(69),v=b(63),k=b(78);b(54);a.addPlugins=d.addPlugins;a.addRoute=h.addRoute;a.cleanupOutdatedCaches=l.cleanupOutdatedCaches;a.createHandlerBoundToURL=m.createHandlerBoundToURL;a.getCacheKeyForURL=g.getCacheKeyForURL;a.matchPrecache=r.matchPrecache;a.precache=t.precache;a.precacheAndRoute=f.precacheAndRoute;a.PrecacheController=q.PrecacheController;a.PrecacheRoute=u.PrecacheRoute;a.PrecacheStrategy=v.PrecacheStrategy;a.PrecacheFallbackPlugin=k.PrecacheFallbackPlugin};
shadow$provide[81]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.messages=void 0;var c=b(16),g=b(30);b(60);a.messages={strategyStart:function(a,b){return"Using "+a+" to respond to '"+(0,g.getFriendlyURL)(b.url)+"'"},printFinalResponse:function(a){a&&(c.logger.groupCollapsed("View the final response here."),c.logger.log(a||"[No response returned]"),c.logger.groupEnd())}}};
shadow$provide[82]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.CacheFirst=void 0;b(20);var c=b(16),g=b(19);h=b(62);var r=b(81);b(60);b=function(a){function b(){d.shadow.js.babel.classCallCheck(this,b);return d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).apply(this,arguments))}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function n(a,
b){var d,f,h,e;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:return k.next=4,b.cacheMatch(a);case 4:d=k.sent;f=void 0;if(d){k.next=20;break}k.prev=8;k.next=11;return b.fetchAndCachePut(a);case 11:d=k.sent;k.next=17;break;case 14:k.prev=14,k.t0=k["catch"](8),k.t0 instanceof Error&&(f=k.t0);case 17:k.next=21;break;case 20:case 21:k.next=44;break;case 30:k.prev=30,k.t1=k["catch"](26),h=!0,e=k.t1;case 34:k.prev=34,k.prev=35,(void 0).return&&(void 0).return();case 37:k.prev=
37;if(!h){k.next=40;break}throw e;case 40:return k.finish(37);case 41:return k.finish(34);case 42:r.messages.printFinalResponse(d),c.logger.groupEnd();case 44:if(d){k.next=46;break}throw new g.WorkboxError("no-response",{url:a.url,error:f});case 46:return k.abrupt("return",d);case 47:case "end":return k.stop()}},n,this,[[8,14],[26,30,34,42],[35,,37,41]])}));return function(b,c){return a.apply(this,arguments)}}()}]);return b}(h.Strategy);a.CacheFirst=b};
shadow$provide[83]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.CacheOnly=void 0;b(20);b(16);var c=b(19);h=b(62);b(81);b(60);b=function(a){function b(){d.shadow.js.babel.classCallCheck(this,b);return d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).apply(this,arguments))}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function v(a,
b){var d;return regeneratorRuntime.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return g.next=3,b.cacheMatch(a);case 3:if(d=g.sent){g.next=7;break}throw new c.WorkboxError("no-response",{url:a.url});case 7:return g.abrupt("return",d);case 8:case "end":return g.stop()}},v,this)}));return function(b,c){return a.apply(this,arguments)}}()}]);return b}(h.Strategy);a.CacheOnly=b};
shadow$provide[84]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.cacheOkAndOpaquePlugin=void 0;b(60);a.cacheOkAndOpaquePlugin={cacheWillUpdate:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(a){var b=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(200!==b.status&&0!==b.status){a.next=2;break}return a.abrupt("return",b);case 2:return a.abrupt("return",null);case 3:case "end":return a.stop()}},
t,void 0)}));return function(b){return a.apply(this,arguments)}}()}};
shadow$provide[85]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.NetworkFirst=void 0;b(20);var c=b(16),g=b(19),r=b(84);h=b(62);var t=b(81);b(60);b=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};d.shadow.js.babel.classCallCheck(this,b);var c=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,a));c.plugins.some(function(a){return"cacheWillUpdate"in a})||c.plugins.unshift(r.cacheOkAndOpaquePlugin);
c._networkTimeoutSeconds=a.networkTimeoutSeconds||0;return c}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function p(a,b){var f=this,h,e,k,l,n,m,q,u,r,H;return regeneratorRuntime.wrap(function(p){for(;;)switch(p.prev=p.next){case 0:return h=[],e=[],k=void 0,this._networkTimeoutSeconds&&(l=this._getTimeoutPromise({request:a,logs:h,handler:b}),n=l.id,m=l.promise,k=n,e.push(m)),q=this._getNetworkPromise({timeoutId:k,
request:a,logs:h,handler:b}),e.push(q),p.next=9,b.waitUntil(d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function K(){return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,b.waitUntil(Promise.race(e));case 2:a.t0=a.sent;if(a.t0){a.next=7;break}a.next=6;return q;case 6:a.t0=a.sent;case 7:return a.abrupt("return",a.t0);case 8:case "end":return a.stop()}},K,f)}))());case 9:u=p.sent;p.next=33;break;case 19:p.prev=19,p.t0=p["catch"](15),r=!0,H=p.t0;
case 23:p.prev=23,p.prev=24,(void 0).return&&(void 0).return();case 26:p.prev=26;if(!r){p.next=29;break}throw H;case 29:return p.finish(26);case 30:return p.finish(23);case 31:t.messages.printFinalResponse(u),c.logger.groupEnd();case 33:if(u){p.next=35;break}throw new g.WorkboxError("no-response",{url:a.url});case 35:return p.abrupt("return",u);case 36:case "end":return p.stop()}},p,this,[[15,19,23,31],[24,,26,30]])}));return function(b,c){return a.apply(this,arguments)}}()},{key:"_getTimeoutPromise",
value:function(a){var b=this,c=a.request,f=a.handler,g=void 0;return{promise:new Promise(function(a){var h=function(){var e=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function z(){return regeneratorRuntime.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return b.t0=a,b.next=4,f.cacheMatch(c);case 4:b.t1=b.sent,(0,b.t0)(b.t1);case 6:case "end":return b.stop()}},z,b)}));return function(){return e.apply(this,arguments)}}();g=setTimeout(h,1E3*b._networkTimeoutSeconds)}),id:g}}},{key:"_getNetworkPromise",
value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function n(a){var b=a.timeoutId,c=a.request,d=a.handler,e,f;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return f=e=void 0,a.prev=2,a.next=5,d.fetchAndCachePut(c);case 5:f=a.sent;a.next=11;break;case 8:a.prev=8,a.t0=a["catch"](2),a.t0 instanceof Error&&(e=a.t0);case 11:b&&clearTimeout(b);if(!e&&f){a.next=18;break}a.next=16;return d.cacheMatch(c);case 16:f=a.sent;case 18:return a.abrupt("return",
f);case 19:case "end":return a.stop()}},n,this,[[2,8]])}));return function(b){return a.apply(this,arguments)}}()}]);return b}(h.Strategy);a.NetworkFirst=b};
shadow$provide[86]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.NetworkOnly=void 0;b(20);b(16);var c=b(31),g=b(19);h=b(62);b(81);b(60);b=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};d.shadow.js.babel.classCallCheck(this,b);var c=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,a));c._networkTimeoutSeconds=a.networkTimeoutSeconds||0;return c}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,
[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function k(a,b){var d,f,h,l;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=d=void 0,e.prev=3,h=[b.fetch(a)],this._networkTimeoutSeconds&&(l=(0,c.timeout)(1E3*this._networkTimeoutSeconds),h.push(l)),e.next=8,Promise.race(h);case 8:if(f=e.sent){e.next=11;break}throw Error("Timed out the network response after "+(this._networkTimeoutSeconds+" seconds."));case 11:e.next=
16;break;case 13:e.prev=13,e.t0=e["catch"](3),e.t0 instanceof Error&&(d=e.t0);case 16:if(f){e.next=19;break}throw new g.WorkboxError("no-response",{url:a.url,error:d});case 19:return e.abrupt("return",f);case 20:case "end":return e.stop()}},k,this,[[3,13]])}));return function(b,c){return a.apply(this,arguments)}}()}]);return b}(h.Strategy);a.NetworkOnly=b};
shadow$provide[87]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.StaleWhileRevalidate=void 0;b(20);var c=b(16),g=b(19),r=b(84);h=b(62);var t=b(81);b(60);b=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};d.shadow.js.babel.classCallCheck(this,b);a=d.shadow.js.babel.possibleConstructorReturn(this,(b.__proto__||Object.getPrototypeOf(b)).call(this,a));a.plugins.some(function(a){return"cacheWillUpdate"in a})||a.plugins.unshift(r.cacheOkAndOpaquePlugin);
return a}d.shadow.js.babel.inherits(b,a);d.shadow.js.babel.createClass(b,[{key:"_handle",value:function(){var a=d.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function p(a,b){var d,f,e,h,k;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return d=b.fetchAndCachePut(a).catch(function(){}),l.next=5,b.cacheMatch(a);case 5:f=l.sent;e=void 0;if(!f){l.next=11;break}l.next=21;break;case 11:return l.prev=12,l.next=15,d;case 15:f=l.sent;l.next=21;break;case 18:l.prev=
18,l.t0=l["catch"](12),l.t0 instanceof Error&&(e=l.t0);case 21:l.next=44;break;case 30:l.prev=30,l.t1=l["catch"](26),h=!0,k=l.t1;case 34:l.prev=34,l.prev=35,(void 0).return&&(void 0).return();case 37:l.prev=37;if(!h){l.next=40;break}throw k;case 40:return l.finish(37);case 41:return l.finish(34);case 42:t.messages.printFinalResponse(f),c.logger.groupEnd();case 44:if(f){l.next=46;break}throw new g.WorkboxError("no-response",{url:a.url,error:e});case 46:return l.abrupt("return",f);case 47:case "end":return l.stop()}},
p,this,[[12,18],[26,30,34,42],[35,,37,41]])}));return function(b,c){return a.apply(this,arguments)}}()}]);return b}(h.Strategy);a.StaleWhileRevalidate=b};
shadow$provide[88]=function(d,h,b,l,a,m){Object.defineProperty(a,"__esModule",{value:!0});a.StrategyHandler=a.Strategy=a.StaleWhileRevalidate=a.NetworkOnly=a.NetworkFirst=a.CacheOnly=a.CacheFirst=void 0;d=b(82);h=b(83);l=b(85);m=b(86);var c=b(87),g=b(62),r=b(61);b(60);a.CacheFirst=d.CacheFirst;a.CacheOnly=h.CacheOnly;a.NetworkFirst=l.NetworkFirst;a.NetworkOnly=m.NetworkOnly;a.StaleWhileRevalidate=c.StaleWhileRevalidate;a.Strategy=g.Strategy;a.StrategyHandler=r.StrategyHandler};
'use strict';ir(14,{});var jL={};jL["typeof"]="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};jL.asyncIterator=function(a){if("function"===typeof Symbol){if(Symbol.asyncIterator){var b=a[Symbol.asyncIterator];if(null!=b)return b.call(a)}if(Symbol.iterator)return a[Symbol.iterator]()}throw new TypeError("Object is not async iterable");};
jL.asyncGenerator=function(){function a(a){this.value=a}function b(b){function c(d,f){try{var g=b[d](f),h=g.value;h instanceof a?Promise.resolve(h.value).then(function(a){c("next",a)},function(a){c("throw",a)}):e(g.done?"return":"normal",g.value)}catch(v){e("throw",v)}}function e(a,b){switch(a){case "return":f.resolve({value:b,done:!0});break;case "throw":f.reject(b);break;default:f.resolve({value:b,done:!1})}(f=f.next)?c(f.key,f.arg):g=null}var f,g;this._invoke=function(a,b){return new Promise(function(d,
e){d={key:a,arg:b,resolve:d,reject:e,next:null};g?g=g.next=d:(f=g=d,c(a,b))})};"function"!==typeof b["return"]&&(this["return"]=void 0)}"function"===typeof Symbol&&Symbol.asyncIterator&&(b.prototype[Symbol.asyncIterator]=function(){return this});b.prototype.next=function(a){return this._invoke("next",a)};b.prototype["throw"]=function(a){return this._invoke("throw",a)};b.prototype["return"]=function(a){return this._invoke("return",a)};return{wrap:function(a){return function(){return new b(a.apply(this,
arguments))}},Yh:function(b){return new a(b)}}}();
jL.asyncGeneratorDelegate=function(a,b){function c(c,d){e=!0;d=new Promise(function(b){b(a[c](d))});return{done:!1,value:b(d)}}var d={},e=!1;"function"===typeof Symbol&&Symbol.iterator&&(d[Symbol.iterator]=function(){return this});d.next=function(a){return e?(e=!1,a):c("next",a)};"function"===typeof a["throw"]&&(d["throw"]=function(a){if(e)throw e=!1,a;return c("throw",a)});"function"===typeof a["return"]&&(d["return"]=function(a){return c("return",a)});return d};
jL.asyncToGenerator=function(a){return function(){var b=a.apply(this,arguments);return new Promise(function(a,d){function c(e,g){try{var f=b[e](g),l=f.value}catch(m){d(m);return}if(f.done)a(l);else return Promise.resolve(l).then(function(a){c("next",a)},function(a){c("throw",a)})}return c("next")})}};jL.classCallCheck=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");};
jL.createClass=function(){function a(a,c){for(var b=0;b<c.length;b++){var e=c[b];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(a,e.key,e)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}();jL.defineEnumerableProperties=function(a,b){for(var c in b){var d=b[c];d.configurable=d.enumerable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,c,d)}return a};
jL.defaults=function(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f&&f.configurable&&void 0===a[e]&&Object.defineProperty(a,e,f)}return a};jL.defineProperty=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a};
jL["extends"]=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};jL.get=function kL(a,b,c){null===a&&(a=Function.prototype);var e=Object.getOwnPropertyDescriptor(a,b);if(void 0===e){if(a=Object.getPrototypeOf(a),null!==a)return kL(a,b,c)}else{if("value"in e)return e.value;b=e.get;return void 0===b?void 0:b.call(c)}};
jL.inherits=function(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)};jL["instanceof"]=function(a,b){return null!=b&&"undefined"!==typeof Symbol&&b[Symbol.Xh]?b[Symbol.Xh](a):a instanceof b};
jL.interopRequireDefault=function(a){return a&&a.__esModule?a:{"default":a}};jL.interopRequireWildcard=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);b["default"]=a;return b};jL.newArrowCheck=function(a,b){if(a!==b)throw new TypeError("Cannot instantiate an arrow function");};jL.objectDestructuringEmpty=function(a){if(null==a)throw new TypeError("Cannot destructure undefined");};
jL.objectWithoutProperties=function(a,b){var c={},d;for(d in a)0<=b.indexOf(d)||Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=a[d]);return c};jL.possibleConstructorReturn=function(a,b){if(!a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?a:b};jL.selfGlobal="undefined"===typeof global?self:global;
jL.set=function lL(a,b,c,d){var f=Object.getOwnPropertyDescriptor(a,b);void 0===f?(a=Object.getPrototypeOf(a),null!==a&&lL(a,b,c,d)):"value"in f&&f.writable?f.value=c:(b=f.set,void 0!==b&&b.call(d,c));return c};
jL.slicedToArray=function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var c=[],d=!0,e=!1,f=void 0;try{for(var g=a[Symbol.iterator](),h;!(d=(h=g.next()).done)&&(c.push(h.value),!b||c.length!==b);d=!0);}catch(l){e=!0,f=l}finally{try{if(!d&&g["return"])g["return"]()}finally{if(e)throw f;}}return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");};
jL.slicedToArrayLoose=function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var c=[];a=a[Symbol.iterator]();for(var d;!(d=a.next()).done&&(c.push(d.value),!b||c.length!==b););return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");};jL.taggedTemplateLiteral=function(a,b){return Object.freeze(Object.defineProperties(a,{raw:{value:Object.freeze(b)}}))};jL.taggedTemplateLiteralLoose=function(a,b){a.raw=b;return a};
jL.temporalRef=function(a,b,c){if(a===c)throw new ReferenceError(b+" is not defined - temporal dead zone");return a};jL.temporalUndefined={};jL.toArray=function(a){return Array.isArray(a)?a:Array.from(a)};jL.toConsumableArray=function(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)};Di("shadow.js.babel",jL);var rL=ir(41,{});var pL=ir(53,{});var sL=ir(80,{});var qL=ir(88,{});var tL=Xi(re.se(function(a){return["/solitaire",u.ga(a)].join("")},new X(null,22,5,Y,"/ /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /assets/images/back.jpeg /assets/images/clubs.svg /assets/images/diamonds.svg /assets/images/hearts.svg /assets/images/spades.svg /assets/images/icon192.png /assets/images/icon512.png /shared.js /app.js".split(" "),
null)));(function(){self.addEventListener("install",function(a){var b=rL.cacheNames.runtime;return a.waitUntil(caches.open(b).then(function(){return function(a){return a.addAll(tL)}}(b)))});self.addEventListener("message",function(a){a=null==a?null:a.data;return I.se(null==a?null:a.type,"SKIP_WAITING")?self.skipWaiting():null});var a=new qL.CacheFirst;pL.registerRoute(function(a){return I.se(a.request.destination,"image")},a);a=new qL.StaleWhileRevalidate;pL.setDefaultHandler(a);sL.precacheAndRoute([{url:"/solitaire/",
revision:"0c19b17e60f5789da9f21f5671e9bcdc073c77d35c544ffe5da7bfabb8cfd4be"}]);a=new pL.NavigationRoute(sL.createHandlerBoundToURL("/solitaire/"));return pL.registerRoute(a)})();