importScripts("shared.js");
shadow$provide[13]=function(g,p,d,r,a,u){g=function(a){function d(a,d,f){Object.defineProperty(a,d,{value:f,enumerable:!0,configurable:!0,writable:!0});return a[d]}function f(a,d,f,g){d=Object.create((d&&d.prototype instanceof k?d:k).prototype);g=new h(g||[]);d._invoke=G(a,f,g);return d}function g(a,d,f){try{return{type:"normal",arg:a.call(d,f)}}catch(Wa){return{type:"throw",arg:Wa}}}function k(){}function C(){}function x(){}function D(a){["next","throw","return"].forEach(function(f){d(a,f,function(a){return this._invoke(f,
a)})})}function w(a,d){function f(k,l,n,h){k=g(a[k],a,l);if("throw"===k.type)h(k.arg);else{var q=k.arg;return(k=q.value)&&"object"===typeof k&&r.call(k,"__await")?d.resolve(k.__await).then(function(a){f("next",a,n,h)},function(a){f("throw",a,n,h)}):d.resolve(k).then(function(a){q.value=a;n(q)},function(a){return f("throw",a,n,h)})}}var k;this._invoke=function(a,g){function l(){return new d(function(d,k){f(a,g,d,k)})}return k=k?k.then(l,l):l()}}function G(a,d,f){var k=qa;return function(n,h){if(k===
O)throw Error("Generator is already running");if(k===ba){if("throw"===n)throw h;return y()}f.method=n;for(f.arg=h;;){if(n=f.delegate)if(n=l(n,f)){if(n===M)continue;return n}if("next"===f.method)f.sent=f._sent=f.arg;else if("throw"===f.method){if(k===qa)throw k=ba,f.arg;f.dispatchException(f.arg)}else"return"===f.method&&f.abrupt("return",f.arg);k=O;n=g(a,d,f);if("normal"===n.type){k=f.done?ba:R;if(n.arg===M)continue;return{value:n.arg,done:f.done}}"throw"===n.type&&(k=ba,f.method="throw",f.arg=n.arg)}}}
function l(a,d){var f=a.iterator[d.method];if(f===P){d.delegate=null;if("throw"===d.method){if(a.iterator["return"]&&(d.method="return",d.arg=P,l(a,d),"throw"===d.method))return M;d.method="throw";d.arg=new TypeError("The iterator does not provide a 'throw' method")}return M}f=g(f,a.iterator,d.arg);if("throw"===f.type)return d.method="throw",d.arg=f.arg,d.delegate=null,M;f=f.arg;if(!f)return d.method="throw",d.arg=new TypeError("iterator result is not an object"),d.delegate=null,M;if(f.done)d[a.resultName]=
f.value,d.next=a.nextLoc,"return"!==d.method&&(d.method="next",d.arg=P);else return f;d.delegate=null;return M}function I(a){var d={tryLoc:a[0]};1 in a&&(d.catchLoc=a[1]);2 in a&&(d.finallyLoc=a[2],d.afterLoc=a[3]);this.tryEntries.push(d)}function p(a){var d=a.completion||{};d.type="normal";delete d.arg;a.completion=d}function h(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(I,this);this.reset(!0)}function K(a){if(a){var d=a[ca];if(d)return d.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var f=
-1;d=function la(){for(;++f<a.length;)if(r.call(a,f))return la.value=a[f],la.done=!1,la;la.value=P;la.done=!0;return la};return d.next=d}}return{next:y}}function y(){return{value:P,done:!0}}var ha=Object.prototype,r=ha.hasOwnProperty,P,u="function"===typeof Symbol?Symbol:{},ca=u.iterator||"@@iterator",da=u.asyncIterator||"@@asyncIterator",V=u.toStringTag||"@@toStringTag";try{d({},"")}catch(E){d=function(a,d,f){return a[d]=f}}a.wrap=f;var qa="suspendedStart",R="suspendedYield",O="executing",ba="completed",
M={};u={};d(u,ca,function(){return this});var L=Object.getPrototypeOf;(L=L&&L(L(K([]))))&&L!==ha&&r.call(L,ca)&&(u=L);var W=x.prototype=k.prototype=Object.create(u);C.prototype=x;d(W,"constructor",x);d(x,"constructor",C);C.displayName=d(x,V,"GeneratorFunction");a.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===C||"GeneratorFunction"===(a.displayName||a.name):!1};a.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,x):(a.__proto__=x,d(a,V,"GeneratorFunction"));
a.prototype=Object.create(W);return a};a.awrap=function(a){return{__await:a}};D(w.prototype);d(w.prototype,da,function(){return this});a.AsyncIterator=w;a.async=function(d,g,k,l,n){void 0===n&&(n=Promise);var h=new w(f(d,g,k,l),n);return a.isGeneratorFunction(g)?h:h.next().then(function(a){return a.done?a.value:h.next()})};D(W);d(W,V,"Generator");d(W,ca,function(){return this});d(W,"toString",function(){return"[object Generator]"});a.keys=function(a){var d=[],f;for(f in a)d.push(f);d.reverse();return function la(){for(;d.length;){var f=
d.pop();if(f in a)return la.value=f,la.done=!1,la}la.done=!0;return la}};a.values=K;h.prototype={constructor:h,reset:function(a){this.next=this.prev=0;this.sent=this._sent=P;this.done=!1;this.delegate=null;this.method="next";this.arg=P;this.tryEntries.forEach(p);if(!a)for(var d in this)"t"===d.charAt(0)&&r.call(this,d)&&!isNaN(+d.slice(1))&&(this[d]=P)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function d(d,
g){l.type="throw";l.arg=a;f.next=d;g&&(f.method="next",f.arg=P);return!!g}if(this.done)throw a;for(var f=this,g=this.tryEntries.length-1;0<=g;--g){var k=this.tryEntries[g],l=k.completion;if("root"===k.tryLoc)return d("end");if(k.tryLoc<=this.prev){var n=r.call(k,"catchLoc"),h=r.call(k,"finallyLoc");if(n&&h){if(this.prev<k.catchLoc)return d(k.catchLoc,!0);if(this.prev<k.finallyLoc)return d(k.finallyLoc)}else if(n){if(this.prev<k.catchLoc)return d(k.catchLoc,!0)}else if(h){if(this.prev<k.finallyLoc)return d(k.finallyLoc)}else throw Error("try statement without catch or finally");
}}},abrupt:function(a,d){for(var f=this.tryEntries.length-1;0<=f;--f){var g=this.tryEntries[f];if(g.tryLoc<=this.prev&&r.call(g,"finallyLoc")&&this.prev<g.finallyLoc){var k=g;break}}k&&("break"===a||"continue"===a)&&k.tryLoc<=d&&d<=k.finallyLoc&&(k=null);f=k?k.completion:{};f.type=a;f.arg=d;return k?(this.method="next",this.next=k.finallyLoc,M):this.complete(f)},complete:function(a,d){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=
this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&d&&(this.next=d);return M},finish:function(a){for(var d=this.tryEntries.length-1;0<=d;--d){var f=this.tryEntries[d];if(f.finallyLoc===a)return this.complete(f.completion,f.afterLoc),p(f),M}},"catch":function(a){for(var d=this.tryEntries.length-1;0<=d;--d){var f=this.tryEntries[d];if(f.tryLoc===a){a=f.completion;if("throw"===a.type){var g=a.arg;p(f)}return g}}throw Error("illegal catch attempt");},delegateYield:function(a,d,f){this.delegate=
{iterator:K(a),resultName:d,nextLoc:f};"next"===this.method&&(this.arg=P);return M}};return a}("object"===typeof r?r.exports:{});try{regeneratorRuntime=g}catch(f){"object"===typeof globalThis?globalThis.regeneratorRuntime=g:Function("r","regeneratorRuntime \x3d r")(g)}};
shadow$provide[14]=function(g,p,d,r,a,u){try{self["workbox:core:6.4.0"]&&_()}catch(f){}};
shadow$provide[15]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.logger=void 0;d(14);a.logger=null};
shadow$provide[16]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.messages=void 0;d(14);a.messages={"invalid-value":function(a){var d=a.paramName,f=a.validValueDescription;a=a.value;if(!d||!f)throw Error("Unexpected input to 'invalid-value' error.");return"The '"+d+"' parameter was given a value with an "+("unexpected value. "+f+" Received a value of ")+(JSON.stringify(a)+".")},"not-an-array":function(a){var d=a.moduleName,f=a.className,g=a.funcName;a=a.paramName;if(!(d&&
f&&g&&a))throw Error("Unexpected input to 'not-an-array' error.");return"The parameter '"+a+"' passed into "+("'"+d+"."+f+"."+g+"()' must be an array.")},"incorrect-type":function(a){var d=a.expectedType,f=a.paramName,g=a.moduleName,k=a.className;a=a.funcName;if(!(d&&f&&g&&a))throw Error("Unexpected input to 'incorrect-type' error.");return"The parameter '"+f+"' passed into "+("'"+g+"."+(k?k+".":""))+(a+"()' must be of type "+d+".")},"incorrect-class":function(a){var d=a.expectedClassName,f=a.paramName,
g=a.moduleName,k=a.className,C=a.funcName;a=a.isReturnValueProblem;if(!d||!g||!C)throw Error("Unexpected input to 'incorrect-class' error.");k=k?k+".":"";return a?"The return value from "+("'"+g+"."+k+C+"()' ")+("must be an instance of class "+d+"."):"The parameter '"+f+"' passed into "+("'"+g+"."+k+C+"()' ")+("must be an instance of class "+d+".")},"missing-a-method":function(a){var d=a.expectedMethod,f=a.paramName,g=a.moduleName,k=a.className;a=a.funcName;if(!(d&&f&&g&&k&&a))throw Error("Unexpected input to 'missing-a-method' error.");
return g+"."+k+"."+a+"() expected the "+("'"+f+"' parameter to expose a '"+d+"' method.")},"add-to-cache-list-unexpected-type":function(a){return"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+("'"+JSON.stringify(a.entry)+"' isn't supported. You must supply an array of ")+"strings with one or more characters, objects with a url property or Request objects."},"add-to-cache-list-conflicting-entries":function(a){var d=a.firstEntry;a=a.secondEntry;
if(!d||!a)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+(d+" but different revision details. Workbox is ")+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":function(a){a=a.thrownErrorMessage;if(!a)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+
("The thrown error message was: '"+a+"'.")},"invalid-cache-name":function(a){var d=a.cacheNameId;a=a.value;if(!d)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");return"You must provide a name containing at least one character for "+("setCacheDetails({"+d+": '...'}). Received a value of ")+("'"+JSON.stringify(a)+"'")},"unregister-route-but-not-found-with-method":function(a){a=a.method;if(!a)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");
return"The route you're trying to unregister was not  previously "+("registered for the method type '"+a+"'.")},"unregister-route-route-not-registered":function(){return"The route you're trying to unregister was not previously registered."},"queue-replay-failed":function(a){return"Replaying the background sync queue '"+a.name+"' failed."},"duplicate-queue-name":function(a){return"The Queue name '"+a.name+"' is already being used. All instances of backgroundSync.Queue must be given unique names."},
"expired-test-without-max-age":function(a){return"The '"+a.methodName+"()' method can only be used when the "+("'"+a.paramName+"' is used in the constructor.")},"unsupported-route-type":function(a){return"The supplied '"+a.paramName+"' parameter was an unsupported type. "+("Please check the docs for "+a.moduleName+"."+a.className+"."+a.funcName+" for ")+"valid input types."},"not-array-of-class":function(a){var d=a.moduleName,f=a.className,g=a.funcName;return"The supplied '"+a.paramName+"' parameter must be an array of "+
("'"+a.expectedClass+"' objects. Received '"+JSON.stringify(a.value)+",'. ")+("Please check the call to "+d+"."+f+"."+g+"() ")+"to fix the issue."},"max-entries-or-age-required":function(a){return"You must define either config.maxEntries or config.maxAgeSeconds"+("in "+a.moduleName+"."+a.className+"."+a.funcName)},"statuses-or-headers-required":function(a){return"You must define either config.statuses or config.headers"+("in "+a.moduleName+"."+a.className+"."+a.funcName)},"invalid-string":function(a){var d=
a.moduleName,f=a.funcName;a=a.paramName;if(!a||!d||!f)throw Error("Unexpected input to 'invalid-string' error.");return"When using strings, the '"+a+"' parameter must start with 'http' (for cross-origin matches) or '/' (for same-origin matches). "+("Please see the docs for "+d+"."+f+"() for ")+"more info."},"channel-name-required":function(){return"You must provide a channelName to construct a BroadcastCacheUpdate instance."},"invalid-responses-are-same-args":function(){return"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used."},
"expire-custom-caches-only":function(){return"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy."},"unit-must-be-bytes":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+('The Range header provided was "'+a+'"')},"single-range-only":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'single-range-only' error.");
return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+('"'+a+'"')},"invalid-range-values":function(a){a=a.normalizedRangeHeader;if(!a)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+('"'+a+'"')},"no-range-header":function(){return"No Range header was found in the Request provided."},
"range-not-satisfiable":function(a){return"The start ("+a.start+") and end ("+a.end+") values in the Range are "+("not satisfiable by the cached response, which is "+a.size+" bytes.")},"attempt-to-cache-non-get-request":function(a){return"Unable to cache '"+a.url+"' because it is a '"+a.method+"' request and only 'GET' requests can be cached."},"cache-put-with-no-response":function(a){return"There was an attempt to cache '"+a.url+"' but the response was not defined."},"no-response":function(a){var d=
a.error;a="The strategy could not generate a response for '"+a.url+"'.";d&&(a+=" The underlying error is "+d+".");return a},"bad-precaching-response":function(a){var d=a.status;return"The precaching request for '"+a.url+"' failed"+(d?" with an HTTP status of "+d+".":".")},"non-precached-url":function(a){return"createHandlerBoundToURL('"+a.url+"') was called, but that URL is not precached. Please pass in a URL that is precached instead."},"add-to-cache-list-conflicting-integrities":function(a){return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
(a.url+" with different integrity values. Please remove one of them.")},"missing-precache-entry":function(a){return"Unable to find a precached response in "+a.cacheName+" for "+a.url+"."},"cross-origin-copy-response":function(a){return"workbox-core.copyResponse() can only be used with same-origin "+("responses. It was passed a response with origin "+a.origin+".")}}};
shadow$provide[17]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.messageGenerator=void 0;d(16);d(14);a.messageGenerator=function(a){for(var d=arguments.length,f=Array(1<d?d-1:0),g=1;g<d;g++)f[g-1]=arguments[g];d=a;0<f.length&&(d+=" :: "+JSON.stringify(f));return d}};
shadow$provide[18]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.WorkboxError=void 0;var f=d(17);d(14);p=function(a){function d(a,k){g.shadow.js.babel.classCallCheck(this,d);var n=(0,f.messageGenerator)(a,k);n=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,n));n.name=a;n.details=k;return n}g.shadow.js.babel.inherits(d,a);return d}(Error);a.WorkboxError=p};
shadow$provide[19]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.assert=void 0;d(18);d(14);a.assert=null};
shadow$provide[20]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.quotaErrorCallbacks=void 0;d(14);g=new Set;a.quotaErrorCallbacks=g};
shadow$provide[21]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.registerQuotaErrorCallback=void 0;d(15);d(19);var f=d(20);d(14);a.registerQuotaErrorCallback=function(a){f.quotaErrorCallbacks.add(a)}};
shadow$provide[22]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.cacheNames=void 0;d(14);var f={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},n=function(a){return[f.prefix,a,f.suffix].filter(function(a){return a&&0<a.length}).join("-")},q=function(a){var d=!0,g=!1,n=void 0;try{for(var q=Object.keys(f)[Symbol.iterator](),t;!(d=(t=q.next()).done);d=!0)a(t.value)}catch(G){g=
!0,n=G}finally{try{!d&&q.return&&q.return()}finally{if(g)throw n;}}};a.cacheNames={updateDetails:function(a){q(function(d){"string"===typeof a[d]&&(f[d]=a[d])})},getGoogleAnalyticsName:function(a){return a||n(f.googleAnalytics)},getPrecacheName:function(a){return a||n(f.precache)},getPrefix:function(){return f.prefix},getRuntimeName:function(a){return a||n(f.runtime)},getSuffix:function(){return f.suffix}}};
shadow$provide[23]=function(g,p,d,r,a,u){function f(a,d){a=new URL(a);var f=!0,g=!1,n=void 0;try{for(var q=d[Symbol.iterator](),D;!(f=(D=q.next()).done);f=!0)a.searchParams.delete(D.value)}catch(w){g=!0,n=w}finally{try{!f&&q.return&&q.return()}finally{if(g)throw n;}}return a.href}Object.defineProperty(a,"__esModule",{value:!0});a.cacheMatchIgnoreParams=void 0;p=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function D(a,d,g,n){var k,t,l,x,C,h,K,y,p,r;return regeneratorRuntime.wrap(function(w){for(;;)switch(w.prev=
w.next){case 0:k=f(d.url,g);if(d.url!==k){w.next=3;break}return w.abrupt("return",a.match(d,n));case 3:return t=Object.assign(Object.assign({},n),{ignoreSearch:!0}),w.next=6,a.keys(d,t);case 6:l=w.sent,x=!0,C=!1,h=void 0,w.prev=10,K=l[Symbol.iterator]();case 12:if(x=(y=K.next()).done){w.next=20;break}p=y.value;r=f(p.url,g);if(k!==r){w.next=17;break}return w.abrupt("return",a.match(p,n));case 17:x=!0;w.next=12;break;case 20:w.next=26;break;case 22:w.prev=22,w.t0=w["catch"](10),C=!0,h=w.t0;case 26:w.prev=
26,w.prev=27,!x&&K.return&&K.return();case 29:w.prev=29;if(!C){w.next=32;break}throw h;case 32:return w.finish(29);case 33:return w.finish(26);case 34:return w.abrupt("return");case 35:case "end":return w.stop()}},D,this,[[10,22,26,34],[27,,29,33]])}));return function(d,f,g,n){return a.apply(this,arguments)}}();d(14);a.cacheMatchIgnoreParams=p};
shadow$provide[24]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.canConstructReadableStream=void 0;d(14);var f=void 0;a.canConstructReadableStream=function(){if(void 0===f)try{new ReadableStream({start:function(){}}),f=!0}catch(n){f=!1}return f}};
shadow$provide[25]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.canConstructResponseFromBodyStream=void 0;d(14);var f=void 0;a.canConstructResponseFromBodyStream=function(){if(void 0===f){var a=new Response("");if("body"in a)try{new Response(a.body),f=!0}catch(q){f=!1}f=!1}return f}};
shadow$provide[26]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.dontWaitFor=function(a){void a.then(function(){})};d(14)};
shadow$provide[27]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.Deferred=void 0;d(14);a.Deferred=function n(){var a=this;g.shadow.js.babel.classCallCheck(this,n);this.promise=new Promise(function(d,g){a.resolve=d;a.reject=g})}};
shadow$provide[28]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.executeQuotaErrorCallbacks=void 0;p=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(){var a,d,g,n,w,G;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:a=!0,d=!1,g=void 0,k.prev=4,n=f.quotaErrorCallbacks[Symbol.iterator]();case 6:if(a=(w=n.next()).done){k.next=14;break}G=w.value;k.next=10;return G();case 10:case 11:a=!0;k.next=6;break;case 14:k.next=
20;break;case 16:k.prev=16,k.t0=k["catch"](4),d=!0,g=k.t0;case 20:k.prev=20,k.prev=21,!a&&n.return&&n.return();case 23:k.prev=23;if(!d){k.next=26;break}throw g;case 26:return k.finish(23);case 27:return k.finish(20);case 28:case 29:case "end":return k.stop()}},t,this,[[4,16,20,28],[21,,23,27]])}));return function(){return a.apply(this,arguments)}}();d(15);var f=d(20);d(14);a.executeQuotaErrorCallbacks=p};
shadow$provide[29]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.getFriendlyURL=void 0;d(14);a.getFriendlyURL=function(a){return(new URL(String(a),location.href)).href.replace(new RegExp("^"+location.origin),"")}};
shadow$provide[30]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.timeout=function(a){return new Promise(function(d){return setTimeout(d,a)})};d(14)};
shadow$provide[31]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.resultingClientExists=void 0;a.resultingClientExists=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function C(a){var d,g,k,q;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:if(a){l.next=2;break}return l.abrupt("return");case 2:return l.next=4,self.clients.matchAll({type:"window"});case 4:d=l.sent,g=new Set(d.map(function(a){return a.id})),k=void 0,
q=performance.now();case 8:if(!(performance.now()-q<n)){l.next=19;break}l.next=11;return self.clients.matchAll({type:"window"});case 11:d=l.sent;k=d.find(function(d){return a?d.id===a:!g.has(d.id)});if(!k){l.next=15;break}return l.abrupt("break",19);case 15:return l.next=17,(0,f.timeout)(100);case 17:l.next=8;break;case 19:return l.abrupt("return",k);case 20:case "end":return l.stop()}},C,this)}));return function(d){return a.apply(this,arguments)}}();var f=d(30);d(14);var n=2E3};
shadow$provide[32]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.waitUntil=void 0;d(14);a.waitUntil=function(a,d){d=d();a.waitUntil(d);return d}};
shadow$provide[33]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.WorkboxError=a.waitUntil=a.timeout=a.resultingClientExists=a.logger=a.getFriendlyURL=a.executeQuotaErrorCallbacks=a.Deferred=a.dontWaitFor=a.canConstructResponseFromBodyStream=a.canConstructReadableStream=a.cacheNames=a.cacheMatchIgnoreParams=a.assert=void 0;g=d(19);p=d(22);r=d(23);u=d(24);var f=d(25),n=d(26),q=d(27),t=d(28),k=d(29),C=d(15),x=d(31),D=d(30),w=d(32),G=d(18);d(14);a.assert=g.assert;a.cacheMatchIgnoreParams=
r.cacheMatchIgnoreParams;a.cacheNames=p.cacheNames;a.canConstructReadableStream=u.canConstructReadableStream;a.canConstructResponseFromBodyStream=f.canConstructResponseFromBodyStream;a.dontWaitFor=n.dontWaitFor;a.Deferred=q.Deferred;a.executeQuotaErrorCallbacks=t.executeQuotaErrorCallbacks;a.getFriendlyURL=k.getFriendlyURL;a.logger=C.logger;a.resultingClientExists=x.resultingClientExists;a.timeout=D.timeout;a.waitUntil=w.waitUntil;a.WorkboxError=G.WorkboxError};
shadow$provide[34]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.cacheNames=void 0;var f=d(22);d(14);a.cacheNames={get googleAnalytics(){return f.cacheNames.getGoogleAnalyticsName()},get precache(){return f.cacheNames.getPrecacheName()},get prefix(){return f.cacheNames.getPrefix()},get runtime(){return f.cacheNames.getRuntimeName()},get suffix(){return f.cacheNames.getSuffix()}}};
shadow$provide[35]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.copyResponse=void 0;p=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(a,d){var g,k,q,l,C,p;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:g=null;a.url&&(k=new URL(a.url),g=k.origin);if(g===self.location.origin){h.next=4;break}throw new n.WorkboxError("cross-origin-copy-response",{origin:g});case 4:q=a.clone();l={headers:new Headers(q.headers),
status:q.status,statusText:q.statusText};C=d?d(l):l;if(!(0,f.canConstructResponseFromBodyStream)()){h.next=11;break}h.t0=q.body;h.next=14;break;case 11:return h.next=13,q.blob();case 13:h.t0=h.sent;case 14:return p=h.t0,h.abrupt("return",new Response(p,C));case 16:case "end":return h.stop()}},x,this)}));return function(d,f){return a.apply(this,arguments)}}();var f=d(25),n=d(18);d(14);a.copyResponse=p};
shadow$provide[36]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.clientsClaim=void 0;d(14);a.clientsClaim=function(){self.addEventListener("activate",function(){return self.clients.claim()})}};
shadow$provide[37]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.setCacheNameDetails=void 0;d(19);var f=d(22);d(18);d(14);a.setCacheNameDetails=function(a){f.cacheNames.updateDetails(a)}};
shadow$provide[38]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.skipWaiting=void 0;d(15);d(14);a.skipWaiting=function(){void self.skipWaiting()}};
shadow$provide[39]=function(g,p,d,r,a,u){d(14)};
shadow$provide[40]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.skipWaiting=a.setCacheNameDetails=a.registerQuotaErrorCallback=a.copyResponse=a.clientsClaim=a.cacheNames=a._private=void 0;var f=d(39);Object.keys(f).forEach(function(d){"default"!==d&&"__esModule"!==d&&Object.defineProperty(a,d,{enumerable:!0,get:function(){return f[d]}})});p=d(21);r=d(33);g=g.shadow.js.babel.interopRequireWildcard(r);r=d(34);u=d(35);var n=d(36),q=d(37),t=d(38);d(14);a._private=g;a.cacheNames=
r.cacheNames;a.clientsClaim=n.clientsClaim;a.copyResponse=u.copyResponse;a.registerQuotaErrorCallback=p.registerQuotaErrorCallback;a.setCacheNameDetails=q.setCacheNameDetails;a.skipWaiting=t.skipWaiting};
shadow$provide[41]=function(g,p,d,r,a,u){try{self["workbox:routing:6.4.0"]&&_()}catch(f){}};
shadow$provide[42]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.validMethods=a.defaultMethod=void 0;d(41);a.defaultMethod="GET";a.validMethods="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[43]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.normalizeHandler=void 0;d(19);d(41);a.normalizeHandler=function(a){return a&&"object"===("undefined"===typeof a?"undefined":g.shadow.js.babel.typeof(a))?a:{handle:a}}};
shadow$provide[44]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.Route=void 0;d(19);var f=d(42),n=d(43);d(41);p=function(){function a(d,k){var q=2<arguments.length&&void 0!==arguments[2]?arguments[2]:f.defaultMethod;g.shadow.js.babel.classCallCheck(this,a);this.handler=(0,n.normalizeHandler)(k);this.match=d;this.method=q}g.shadow.js.babel.createClass(a,[{key:"setCatchHandler",value:function(a){this.catchHandler=(0,n.normalizeHandler)(a)}}]);return a}();a.Route=p};
shadow$provide[45]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.NavigationRoute=void 0;d(19);d(15);p=d(44);d(41);d=function(a){function d(a){var f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{},k=f.allowlist;k=void 0===k?[/./]:k;f=f.denylist;f=void 0===f?[]:f;g.shadow.js.babel.classCallCheck(this,d);var n=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,function(a){return n._match(a)},a));n._allowlist=k;n._denylist=
f;return n}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_match",value:function(a){var d=a.url;if((a=a.request)&&"navigate"!==a.mode)return!1;var f=d.pathname+d.search;d=!0;a=!1;var g=void 0;try{for(var n=this._denylist[Symbol.iterator](),q;!(d=(q=n.next()).done);d=!0)if(q.value.test(f))return!1}catch(w){a=!0,g=w}finally{try{!d&&n.return&&n.return()}finally{if(a)throw g;}}return this._allowlist.some(function(a){return a.test(f)})?!0:!1}}]);return d}(p.Route);a.NavigationRoute=
d};
shadow$provide[46]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.RegExpRoute=void 0;d(19);d(15);p=d(44);d(41);d=function(a){function d(a,f,k){g.shadow.js.babel.classCallCheck(this,d);return g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,function(d){d=d.url;var f=a.exec(d.href);if(f&&(d.origin===location.origin||0===f.index))return f.slice(1)},f,k))}g.shadow.js.babel.inherits(d,a);return d}(p.Route);a.RegExpRoute=d};
shadow$provide[47]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.Router=void 0;d(19);d(29);var f=d(42);d(15);var n=d(43),q=d(18);d(41);p=function(){function a(){g.shadow.js.babel.classCallCheck(this,a);this._routes=new Map;this._defaultHandlerMap=new Map}g.shadow.js.babel.createClass(a,[{key:"addFetchListener",value:function(){var a=this;self.addEventListener("fetch",function(d){var f=a.handleRequest({request:d.request,event:d});f&&d.respondWith(f)})}},{key:"addCacheListener",
value:function(){var a=this;self.addEventListener("message",function(d){if(d.data&&"CACHE_URLS"===d.data.type){var f=Promise.all(d.data.payload.urlsToCache.map(function(f){"string"===typeof f&&(f=[f]);f=new (Function.prototype.bind.apply(Request,[null].concat(g.shadow.js.babel.toConsumableArray(f))));return a.handleRequest({request:f,event:d})}));d.waitUntil(f);d.ports&&d.ports[0]&&void f.then(function(){return d.ports[0].postMessage(!0)})}})}},{key:"handleRequest",value:function(a){var d=this,f=
a.request,k=a.event,n=new URL(f.url,location.href);if(n.protocol.startsWith("http")){a=this.findMatchingRoute({event:k,request:f,sameOrigin:n.origin===location.origin,url:n});var q=a.params,l=(a=a.route)&&a.handler,t=f.method;!l&&this._defaultHandlerMap.has(t)&&(l=this._defaultHandlerMap.get(t));if(l){t=void 0;try{t=l.handle({url:n,request:f,event:k,params:q})}catch(h){t=Promise.reject(h)}var p=a&&a.catchHandler;t instanceof Promise&&(this._catchHandler||p)&&(t=t.catch(function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function ha(a){return regeneratorRuntime.wrap(function(g){for(;;)switch(g.prev=
g.next){case 0:if(!p){g.next=11;break}g.prev=2;g.next=5;return p.handle({url:n,request:f,event:k,params:q});case 5:return g.abrupt("return",g.sent);case 8:g.prev=8,g.t0=g["catch"](2),g.t0 instanceof Error&&(a=g.t0);case 11:if(!d._catchHandler){g.next=14;break}return g.abrupt("return",d._catchHandler.handle({url:n,request:f,event:k}));case 14:throw a;case 15:case "end":return g.stop()}},ha,d,[[2,8]])}));return function(d){return a.apply(this,arguments)}}()));return t}}}},{key:"findMatchingRoute",value:function(a){var d=
a.url,f=a.sameOrigin,g=a.request;a=a.event;var k=this._routes.get(g.method)||[],n=!0,l=!1,q=void 0;try{for(var t=k[Symbol.iterator](),h;!(n=(h=t.next()).done);n=!0){var K=h.value;k=void 0;var y=K.match({url:d,sameOrigin:f,request:g,event:a});if(y)return k=y,Array.isArray(k)&&0===k.length?k=void 0:y.constructor===Object&&0===Object.keys(y).length?k=void 0:"boolean"===typeof y&&(k=void 0),{route:K,params:k}}}catch(ha){l=!0,q=ha}finally{try{!n&&t.return&&t.return()}finally{if(l)throw q;}}return{}}},
{key:"setDefaultHandler",value:function(a){this._defaultHandlerMap.set(1<arguments.length&&void 0!==arguments[1]?arguments[1]:f.defaultMethod,(0,n.normalizeHandler)(a))}},{key:"setCatchHandler",value:function(a){this._catchHandler=(0,n.normalizeHandler)(a)}},{key:"registerRoute",value:function(a){this._routes.has(a.method)||this._routes.set(a.method,[]);this._routes.get(a.method).push(a)}},{key:"unregisterRoute",value:function(a){if(!this._routes.has(a.method))throw new q.WorkboxError("unregister-route-but-not-found-with-method",
{method:a.method});var d=this._routes.get(a.method).indexOf(a);if(-1<d)this._routes.get(a.method).splice(d,1);else throw new q.WorkboxError("unregister-route-route-not-registered");}},{key:"routes",get:function(){return this._routes}}]);return a}();a.Router=p};
shadow$provide[48]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.getOrCreateDefaultRouter=void 0;var f=d(47);d(41);var n=void 0;a.getOrCreateDefaultRouter=function(){n||(n=new f.Router,n.addFetchListener(),n.addCacheListener());return n}};
shadow$provide[49]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.registerRoute=void 0;d(15);var f=d(18),n=d(44),q=d(46),t=d(48);d(41);a.registerRoute=function(a,d,g){var k=void 0;if("string"===typeof a){var w=new URL(a,location.href);k=new n.Route(function(a){return a.url.href===w.href},d,g)}else if(a instanceof RegExp)k=new q.RegExpRoute(a,d,g);else if("function"===typeof a)k=new n.Route(a,d,g);else if(a instanceof n.Route)k=a;else throw new f.WorkboxError("unsupported-route-type",
{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,t.getOrCreateDefaultRouter)().registerRoute(k);return k}};
shadow$provide[50]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.setCatchHandler=void 0;var f=d(48);d(41);a.setCatchHandler=function(a){(0,f.getOrCreateDefaultRouter)().setCatchHandler(a)}};
shadow$provide[51]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.setDefaultHandler=void 0;var f=d(48);d(41);a.setDefaultHandler=function(a){(0,f.getOrCreateDefaultRouter)().setDefaultHandler(a)}};
shadow$provide[52]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.setDefaultHandler=a.setCatchHandler=a.Router=a.Route=a.registerRoute=a.RegExpRoute=a.NavigationRoute=void 0;g=d(45);p=d(46);r=d(49);u=d(44);var f=d(47),n=d(50),q=d(51);d(41);a.NavigationRoute=g.NavigationRoute;a.RegExpRoute=p.RegExpRoute;a.registerRoute=r.registerRoute;a.Route=u.Route;a.Router=f.Router;a.setCatchHandler=n.setCatchHandler;a.setDefaultHandler=q.setDefaultHandler};
shadow$provide[53]=function(g,p,d,r,a,u){try{self["workbox:precaching:6.4.0"]&&_()}catch(f){}};
shadow$provide[54]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.createCacheKey=function(a){if(!a)throw new f.WorkboxError("add-to-cache-list-unexpected-type",{entry:a});if("string"===typeof a){var d=new URL(a,location.href);return{cacheKey:d.href,url:d.href}}d=a.revision;var g=a.url;if(!g)throw new f.WorkboxError("add-to-cache-list-unexpected-type",{entry:a});if(!d)return d=new URL(g,location.href),{cacheKey:d.href,url:d.href};a=new URL(g,location.href);g=new URL(g,location.href);
a.searchParams.set(n,d);return{cacheKey:a.href,url:g.href}};var f=d(18);d(53);var n="__WB_REVISION__"};
shadow$provide[55]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheInstallReportPlugin=void 0;d(53);a.PrecacheInstallReportPlugin=function n(){var a=this;g.shadow.js.babel.classCallCheck(this,n);this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=function(){var d=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(d){var g=d.request,n=d.state;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:n&&(n.originalRequest=
g);case 1:case "end":return a.stop()}},x,a)}));return function(a){return d.apply(this,arguments)}}();this.cachedResponseWillBeUsed=function(){var d=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function x(d){var g=d.event,n=d.state,q=d.cachedResponse,l;return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return"install"===g.type&&n&&n.originalRequest&&n.originalRequest instanceof Request&&(l=n.originalRequest.url,q?a.notUpdatedURLs.push(l):a.updatedURLs.push(l)),
d.abrupt("return",q);case 2:case "end":return d.stop()}},x,a)}));return function(a){return d.apply(this,arguments)}}()}};
shadow$provide[56]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheCacheKeyPlugin=void 0;d(53);a.PrecacheCacheKeyPlugin=function q(a){var d=this;a=a.precacheController;g.shadow.js.babel.classCallCheck(this,q);this.cacheKeyWillBeUsed=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function D(a){var g=a.request,k=a.params,l;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return l=(null===k||void 0===k?void 0:
k.cacheKey)||d._precacheController.getCacheKeyForURL(g.url),a.abrupt("return",l?new Request(l,{headers:g.headers}):g);case 2:case "end":return a.stop()}},D,d)}));return function(d){return a.apply(this,arguments)}}();this._precacheController=a}};
shadow$provide[57]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.printCleanupDetails=function(a){var d=a.length;if(0<d){f.logger.groupCollapsed("During precaching cleanup, "+(d+" cached ")+("request"+(1===d?" was":"s were")+" deleted."));f.logger.groupCollapsed("Deleted Cache Requests");d=!0;var g=!1,k=void 0;try{for(var n=a[Symbol.iterator](),p;!(d=(p=n.next()).done);d=!0)f.logger.log(p.value)}catch(D){g=!0,k=D}finally{try{!d&&n.return&&n.return()}finally{if(g)throw k;
}}f.logger.groupEnd();f.logger.groupEnd()}};var f=d(15);d(53)};
shadow$provide[58]=function(g,p,d,r,a,u){function f(a,d){if(0!==d.length){n.logger.groupCollapsed(a);a=!0;var f=!1,g=void 0;try{for(var q=d[Symbol.iterator](),p;!(a=(p=q.next()).done);a=!0)n.logger.log(p.value)}catch(w){f=!0,g=w}finally{try{!a&&q.return&&q.return()}finally{if(f)throw g;}}n.logger.groupEnd()}}Object.defineProperty(a,"__esModule",{value:!0});a.printInstallDetails=function(a,d){var g=a.length,q=d.length;if(g||q)g="Precaching "+g+" file"+(1===g?"":"s")+".",0<q&&(g+=" "+q+" "+("file"+
(1===q?" is":"s are")+" already cached.")),n.logger.groupCollapsed(g),f("View newly precached URLs.",a),f("View previously precached URLs.",d),n.logger.groupEnd()};var n=d(15);d(53)};
shadow$provide[59]=function(g,p,d,r,a,u){try{self["workbox:strategies:6.4.0"]&&_()}catch(f){}};
shadow$provide[60]=function(g,p,d,r,a,u){function f(a){return"string"===typeof a?new Request(a):a}Object.defineProperty(a,"__esModule",{value:!0});a.StrategyHandler=void 0;d(19);var n=d(23),q=d(27),t=d(28),k=d(29),C=d(15),x=d(30),D=d(18);d(59);p=function(){function a(d,f){g.shadow.js.babel.classCallCheck(this,a);this._cacheKeys={};Object.assign(this,f);this.event=f.event;this._strategy=d;this._handlerDeferred=new q.Deferred;this._extendLifetimePromises=[];this._plugins=[].concat(g.shadow.js.babel.toConsumableArray(d.plugins));
this._pluginStateMap=new Map;d=!0;f=!1;var k=void 0;try{for(var l=this._plugins[Symbol.iterator](),n;!(d=(n=l.next()).done);d=!0)this._pluginStateMap.set(n.value,{})}catch(K){f=!0,k=K}finally{try{!d&&l.return&&l.return()}finally{if(f)throw k;}}this.event.waitUntil(this._handlerDeferred.promise)}g.shadow.js.babel.createClass(a,[{key:"fetch",value:function(a){function d(d){return a.apply(this,arguments)}d.toString=function(){return a.toString()};return d}(function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function N(a){var d,
g,k,n,q,p,w,t,G,x,r,C,I,u,M,L,W,E;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:d=this.event;g=f(a);if(!("navigate"===g.mode&&d instanceof FetchEvent&&d.preloadResponse)){h.next=9;break}h.next=5;return d.preloadResponse;case 5:k=h.sent;if(!k){h.next=9;break}return h.abrupt("return",k);case 9:n=this.hasCallback("fetchDidFail")?g.clone():null,h.prev=10,q=!0,p=!1,w=void 0,h.prev=14,t=this.iterateCallbacks("requestWillFetch")[Symbol.iterator]();case 16:if(q=(G=t.next()).done){h.next=
24;break}x=G.value;h.next=20;return x({request:g.clone(),event:d});case 20:g=h.sent;case 21:q=!0;h.next=16;break;case 24:h.next=30;break;case 26:h.prev=26,h.t0=h["catch"](14),p=!0,w=h.t0;case 30:h.prev=30,h.prev=31,!q&&t.return&&t.return();case 33:h.prev=33;if(!p){h.next=36;break}throw w;case 36:return h.finish(33);case 37:return h.finish(30);case 38:h.next=44;break;case 40:h.prev=40;h.t1=h["catch"](10);if(!(h.t1 instanceof Error)){h.next=44;break}throw new D.WorkboxError("plugin-error-request-will-fetch",
{thrownErrorMessage:h.t1.message});case 44:return r=g.clone(),h.prev=45,C=void 0,h.next=49,fetch(g,"navigate"===g.mode?void 0:this._strategy.fetchOptions);case 49:C=h.sent,I=!0,u=!1,M=void 0,h.prev=54,L=this.iterateCallbacks("fetchDidSucceed")[Symbol.iterator]();case 56:if(I=(W=L.next()).done){h.next=64;break}E=W.value;h.next=60;return E({event:d,request:r,response:C});case 60:C=h.sent;case 61:I=!0;h.next=56;break;case 64:h.next=70;break;case 66:h.prev=66,h.t2=h["catch"](54),u=!0,M=h.t2;case 70:h.prev=
70,h.prev=71,!I&&L.return&&L.return();case 73:h.prev=73;if(!u){h.next=76;break}throw M;case 76:return h.finish(73);case 77:return h.finish(70);case 78:return h.abrupt("return",C);case 81:h.prev=81;h.t3=h["catch"](45);if(!n){h.next=87;break}h.next=87;return this.runCallbacks("fetchDidFail",{error:h.t3,event:d,originalRequest:n.clone(),request:r.clone()});case 87:throw h.t3;case 88:case "end":return h.stop()}},N,this,[[10,40],[14,26,30,38],[31,,33,37],[45,81],[54,66,70,78],[71,,73,77]])}));return function(d){return a.apply(this,
arguments)}}())},{key:"fetchAndCachePut",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function N(a){var d,f;return regeneratorRuntime.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return g.next=2,this.fetch(a);case 2:return d=g.sent,f=d.clone(),void this.waitUntil(this.cachePut(a,f)),g.abrupt("return",d);case 6:case "end":return g.stop()}},N,this)}));return function(d){return a.apply(this,arguments)}}()},{key:"cacheMatch",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function N(a){var d,
g,k,n,q,p,w,t,x,G,D,C,r;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return d=f(a),g=void 0,k=this._strategy,n=k.cacheName,q=k.matchOptions,h.next=5,this.getCacheKey(d,"read");case 5:return p=h.sent,w=Object.assign(Object.assign({},q),{cacheName:n}),h.next=9,caches.match(p,w);case 9:g=h.sent,t=!0,x=!1,G=void 0,h.prev=14,D=this.iterateCallbacks("cachedResponseWillBeUsed")[Symbol.iterator]();case 16:if(t=(C=D.next()).done){h.next=27;break}r=C.value;h.next=20;return r({cacheName:n,
matchOptions:q,cachedResponse:g,request:p,event:this.event});case 20:h.t0=h.sent;if(h.t0){h.next=23;break}h.t0=void 0;case 23:g=h.t0;case 24:t=!0;h.next=16;break;case 27:h.next=33;break;case 29:h.prev=29,h.t1=h["catch"](14),x=!0,G=h.t1;case 33:h.prev=33,h.prev=34,!t&&D.return&&D.return();case 36:h.prev=36;if(!x){h.next=39;break}throw G;case 39:return h.finish(36);case 40:return h.finish(33);case 41:return h.abrupt("return",g);case 42:case "end":return h.stop()}},N,this,[[14,29,33,41],[34,,36,40]])}));
return function(d){return a.apply(this,arguments)}}()},{key:"cachePut",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function h(a,d){var g,q,p,w,G,r,N,u,V,I,R,O,ba,M,L,W;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return g=f(a),h.next=3,(0,x.timeout)(0);case 3:return h.next=5,this.getCacheKey(g,"write");case 5:q=h.sent;h.next=11;break;case 9:(p=d.headers.get("Vary"))&&C.logger.debug("The response for "+(0,k.getFriendlyURL)(q.url)+
" "+("has a 'Vary: "+p+"' header. ")+"Consider setting the {ignoreVary: true} option on your strategy to ensure cache matching and deletion works as expected.");case 11:if(d){h.next=14;break}throw new D.WorkboxError("cache-put-with-no-response",{url:(0,k.getFriendlyURL)(q.url)});case 14:return h.next=16,this._ensureResponseSafeToCache(d);case 16:if(w=h.sent){h.next=20;break}return h.abrupt("return",!1);case 20:return G=this._strategy,r=G.cacheName,N=G.matchOptions,h.next=23,self.caches.open(r);case 23:u=
h.sent;V=this.hasCallback("cacheDidUpdate");if(!V){h.next=31;break}h.next=28;return(0,n.cacheMatchIgnoreParams)(u,q.clone(),["__WB_REVISION__"],N);case 28:h.t0=h.sent;h.next=32;break;case 31:h.t0=null;case 32:return I=h.t0,h.prev=34,h.next=37,u.put(q,V?w.clone():w);case 37:h.next=46;break;case 39:h.prev=39;h.t1=h["catch"](34);if(!(h.t1 instanceof Error)){h.next=46;break}if("QuotaExceededError"!==h.t1.name){h.next=45;break}h.next=45;return(0,t.executeQuotaErrorCallbacks)();case 45:throw h.t1;case 46:R=
!0,O=!1,ba=void 0,h.prev=49,M=this.iterateCallbacks("cacheDidUpdate")[Symbol.iterator]();case 51:if(R=(L=M.next()).done){h.next=58;break}W=L.value;h.next=55;return W({cacheName:r,oldResponse:I,newResponse:w.clone(),request:q,event:this.event});case 55:R=!0;h.next=51;break;case 58:h.next=64;break;case 60:h.prev=60,h.t2=h["catch"](49),O=!0,ba=h.t2;case 64:h.prev=64,h.prev=65,!R&&M.return&&M.return();case 67:h.prev=67;if(!O){h.next=70;break}throw ba;case 70:return h.finish(67);case 71:return h.finish(64);
case 72:return h.abrupt("return",!0);case 73:case "end":return h.stop()}},h,this,[[34,39],[49,60,64,72],[65,,67,71]])}));return function(d,f){return a.apply(this,arguments)}}()},{key:"getCacheKey",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function h(a,d){var g,k,n,q,p,w,t,x;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:g=a.url+" | "+d;if(this._cacheKeys[g]){h.next=33;break}k=a;n=!0;q=!1;p=void 0;h.prev=6;w=this.iterateCallbacks("cacheKeyWillBeUsed")[Symbol.iterator]();
case 8:if(n=(t=w.next()).done){h.next=18;break}x=t.value;h.t0=f;h.next=13;return x({mode:d,request:k,event:this.event,params:this.params});case 13:h.t1=h.sent,k=(0,h.t0)(h.t1);case 15:n=!0;h.next=8;break;case 18:h.next=24;break;case 20:h.prev=20,h.t2=h["catch"](6),q=!0,p=h.t2;case 24:h.prev=24,h.prev=25,!n&&w.return&&w.return();case 27:h.prev=27;if(!q){h.next=30;break}throw p;case 30:return h.finish(27);case 31:return h.finish(24);case 32:this._cacheKeys[g]=k;case 33:return h.abrupt("return",this._cacheKeys[g]);
case 34:case "end":return h.stop()}},h,this,[[6,20,24,32],[25,,27,31]])}));return function(d,f){return a.apply(this,arguments)}}()},{key:"hasCallback",value:function(a){var d=!0,f=!1,g=void 0;try{for(var k=this._strategy.plugins[Symbol.iterator](),n;!(d=(n=k.next()).done);d=!0)if(a in n.value)return!0}catch(y){f=!0,g=y}finally{try{!d&&k.return&&k.return()}finally{if(f)throw g;}}return!1}},{key:"runCallbacks",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function h(a,
d){var f,g,k,n,q,p;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:f=!0,g=!1,k=void 0,h.prev=3,n=this.iterateCallbacks(a)[Symbol.iterator]();case 5:if(f=(q=n.next()).done){h.next=12;break}p=q.value;h.next=9;return p(d);case 9:f=!0;h.next=5;break;case 12:h.next=18;break;case 14:h.prev=14,h.t0=h["catch"](3),g=!0,k=h.t0;case 18:h.prev=18,h.prev=19,!f&&n.return&&n.return();case 21:h.prev=21;if(!g){h.next=24;break}throw k;case 24:return h.finish(21);case 25:return h.finish(18);
case 26:case "end":return h.stop()}},h,this,[[3,14,18,26],[19,,21,25]])}));return function(d,f){return a.apply(this,arguments)}}()},{key:"iterateCallbacks",value:regeneratorRuntime.mark(function I(a){var d=this,f,g,k,l,n,q,p;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:f=regeneratorRuntime.mark(function qa(f){var g,k;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:if("function"!==typeof f[a]){h.next=5;break}g=d._pluginStateMap.get(f);
k=function(d){d=Object.assign(Object.assign({},d),{state:g});return f[a](d)};h.next=5;return k;case 5:case "end":return h.stop()}},qa,d)}),g=!0,k=!1,l=void 0,h.prev=4,n=this._strategy.plugins[Symbol.iterator]();case 6:if(g=(q=n.next()).done){h.next=12;break}p=q.value;return h.delegateYield(f(p),"t0",9);case 9:g=!0;h.next=6;break;case 12:h.next=18;break;case 14:h.prev=14,h.t1=h["catch"](4),k=!0,l=h.t1;case 18:h.prev=18,h.prev=19,!g&&n.return&&n.return();case 21:h.prev=21;if(!k){h.next=24;break}throw l;
case 24:return h.finish(21);case 25:return h.finish(18);case 26:case "end":return h.stop()}},I,this,[[4,14,18,26],[19,,21,25]])})},{key:"waitUntil",value:function(a){this._extendLifetimePromises.push(a);return a}},{key:"doneWaiting",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function N(){var a;return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:a=void 0;case 1:if(!(a=this._extendLifetimePromises.shift())){d.next=6;break}d.next=4;return a;
case 4:d.next=1;break;case 6:case "end":return d.stop()}},N,this)}));return function(){return a.apply(this,arguments)}}()},{key:"destroy",value:function(){this._handlerDeferred.resolve(null)}},{key:"_ensureResponseSafeToCache",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function h(a){var d,f,g,k,l,n,q,p;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:d=a,f=!1,g=!0,k=!1,l=void 0,h.prev=5,n=this.iterateCallbacks("cacheWillUpdate")[Symbol.iterator]();
case 7:if(g=(q=n.next()).done){h.next=21;break}p=q.value;h.next=11;return p({request:this.request,response:d,event:this.event});case 11:h.t0=h.sent;if(h.t0){h.next=14;break}h.t0=void 0;case 14:d=h.t0;f=!0;if(d){h.next=18;break}return h.abrupt("break",21);case 18:g=!0;h.next=7;break;case 21:h.next=27;break;case 23:h.prev=23,h.t1=h["catch"](5),k=!0,l=h.t1;case 27:h.prev=27,h.prev=28,!g&&n.return&&n.return();case 30:h.prev=30;if(!k){h.next=33;break}throw l;case 33:return h.finish(30);case 34:return h.finish(27);
case 35:return f||d&&200!==d.status&&(d=void 0),h.abrupt("return",d);case 37:case "end":return h.stop()}},h,this,[[5,23,27,35],[28,,30,34]])}));return function(d){return a.apply(this,arguments)}}()}]);return a}();a.StrategyHandler=p};
shadow$provide[61]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.Strategy=void 0;var f=d(22),n=d(18);d(15);d(29);var q=d(60);d(59);p=function(){function a(){var d=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};g.shadow.js.babel.classCallCheck(this,a);this.cacheName=f.cacheNames.getRuntimeName(d.cacheName);this.plugins=d.plugins||[];this.fetchOptions=d.fetchOptions;this.matchOptions=d.matchOptions}g.shadow.js.babel.createClass(a,[{key:"handle",value:function(a){a=
this.handleAll(a);return g.shadow.js.babel.slicedToArray(a,1)[0]}},{key:"handleAll",value:function(a){a instanceof FetchEvent&&(a={event:a,request:a.request});var d=a.event,f="string"===typeof a.request?new Request(a.request):a.request,g=new q.StrategyHandler(this,{event:d,request:f,params:"params"in a?a.params:void 0});a=this._getResponse(g,f,d);d=this._awaitComplete(a,g,f,d);return[a,d]}},{key:"_getResponse",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function G(a,
d,f){var g,k,q,h,p,w,t,x,D,r,u,da,V;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return l.next=2,a.runCallbacks("handlerWillStart",{event:f,request:d});case 2:return g=void 0,l.prev=3,l.next=6,this._handle(d,a);case 6:if((g=l.sent)&&"error"!==g.type){l.next=9;break}throw new n.WorkboxError("no-response",{url:d.url});case 9:l.next=48;break;case 11:l.prev=11;l.t0=l["catch"](3);if(!(l.t0 instanceof Error)){l.next=43;break}k=!0;q=!1;h=void 0;l.prev=17;p=a.iterateCallbacks("handlerDidError")[Symbol.iterator]();
case 19:if(k=(w=p.next()).done){l.next=29;break}t=w.value;l.next=23;return t({error:l.t0,event:f,request:d});case 23:g=l.sent;if(!g){l.next=26;break}return l.abrupt("break",29);case 26:k=!0;l.next=19;break;case 29:l.next=35;break;case 31:l.prev=31,l.t1=l["catch"](17),q=!0,h=l.t1;case 35:l.prev=35,l.prev=36,!k&&p.return&&p.return();case 38:l.prev=38;if(!q){l.next=41;break}throw h;case 41:return l.finish(38);case 42:return l.finish(35);case 43:if(g){l.next=47;break}throw l.t0;case 47:case 48:x=!0,D=
!1,r=void 0,l.prev=51,u=a.iterateCallbacks("handlerWillRespond")[Symbol.iterator]();case 53:if(x=(da=u.next()).done){l.next=61;break}V=da.value;l.next=57;return V({event:f,request:d,response:g});case 57:g=l.sent;case 58:x=!0;l.next=53;break;case 61:l.next=67;break;case 63:l.prev=63,l.t2=l["catch"](51),D=!0,r=l.t2;case 67:l.prev=67,l.prev=68,!x&&u.return&&u.return();case 70:l.prev=70;if(!D){l.next=73;break}throw r;case 73:return l.finish(70);case 74:return l.finish(67);case 75:return l.abrupt("return",
g);case 76:case "end":return l.stop()}},G,this,[[3,11],[17,31,35,43],[36,,38,42],[51,63,67,75],[68,,70,74]])}));return function(d,f,g){return a.apply(this,arguments)}}()},{key:"_awaitComplete",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function l(a,d,f,g){var k,n;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return n=k=void 0,h.prev=2,h.next=5,a;case 5:k=h.sent;h.next=10;break;case 8:h.prev=8,h.t0=h["catch"](2);case 10:return h.prev=
10,h.next=13,d.runCallbacks("handlerDidRespond",{event:g,request:f,response:k});case 13:return h.next=15,d.doneWaiting();case 15:h.next=20;break;case 17:h.prev=17,h.t1=h["catch"](10),h.t1 instanceof Error&&(n=h.t1);case 20:return h.next=22,d.runCallbacks("handlerDidComplete",{event:g,request:f,response:k,error:n});case 22:d.destroy();if(!n){h.next=25;break}throw n;case 25:case "end":return h.stop()}},l,this,[[2,8],[10,17]])}));return function(d,f,g,k){return a.apply(this,arguments)}}()}]);return a}();
a.Strategy=p};
shadow$provide[62]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheStrategy=void 0;var f=d(35),n=d(22),q=d(29),t=d(15),k=d(18);p=d(61);d(53);d=function(a){function d(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};g.shadow.js.babel.classCallCheck(this,d);a.cacheName=n.cacheNames.getPrecacheName(a.cacheName);var f=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,a));f._fallbackToNetwork=!1===a.fallbackToNetwork?
!1:!0;f.plugins.push(d.copyRedirectedCacheableResponsesPlugin);return f}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(a,d){var f;return regeneratorRuntime.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return g.next=2,d.cacheMatch(a);case 2:f=g.sent;if(!f){g.next=5;break}return g.abrupt("return",f);case 5:if(!d.event||"install"!==d.event.type){g.next=9;break}g.next=
8;return this._handleInstall(a,d);case 8:return g.abrupt("return",g.sent);case 9:return g.next=11,this._handleFetch(a,d);case 11:return g.abrupt("return",g.sent);case 12:case "end":return g.stop()}},I,this)}));return function(d,f){return a.apply(this,arguments)}}()},{key:"_handleFetch",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(a,d){var f,g,l,n,p,r;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:f=void 0;g=d.params||
{};if(!this._fallbackToNetwork){h.next=18;break}l=g.integrity;n=a.integrity;p=!n||n===l;h.next=9;return d.fetch(new Request(a,{integrity:n||l}));case 9:f=h.sent;if(!l||!p){h.next=16;break}this._useDefaultCacheabilityPluginIfNeeded();h.next=14;return d.cachePut(a,f.clone());case 14:case 16:h.next=19;break;case 18:throw new k.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:a.url});case 19:h.next=35;break;case 24:h.t0=h.sent;case 25:r=h.t0,t.logger.groupCollapsed("Precaching is responding to: "+
(0,q.getFriendlyURL)(a.url)),t.logger.log("Serving the precached url: "+(0,q.getFriendlyURL)(r instanceof Request?r.url:r)),t.logger.groupCollapsed("View request details here."),t.logger.log(a),t.logger.groupEnd(),t.logger.groupCollapsed("View response details here."),t.logger.log(f),t.logger.groupEnd(),t.logger.groupEnd();case 35:return h.abrupt("return",f);case 36:case "end":return h.stop()}},I,this)}));return function(d,f){return a.apply(this,arguments)}}()},{key:"_handleInstall",value:function(){var a=
g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(a,d){var f,g;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return this._useDefaultCacheabilityPluginIfNeeded(),h.next=3,d.fetch(a);case 3:return f=h.sent,h.next=6,d.cachePut(a,f.clone());case 6:if(g=h.sent){h.next=9;break}throw new k.WorkboxError("bad-precaching-response",{url:a.url,status:f.status});case 9:return h.abrupt("return",f);case 10:case "end":return h.stop()}},I,this)}));return function(d,
f){return a.apply(this,arguments)}}()},{key:"_useDefaultCacheabilityPluginIfNeeded",value:function(){var a=null,f=0,k=!0,l=!1,n=void 0;try{for(var q=this.plugins.entries()[Symbol.iterator](),h;!(k=(h=q.next()).done);k=!0){var p=g.shadow.js.babel.slicedToArray(h.value,2),t=p[0],r=p[1];r!==d.copyRedirectedCacheableResponsesPlugin&&(r===d.defaultPrecacheCacheabilityPlugin&&(a=t),r.cacheWillUpdate&&f++)}}catch(ra){l=!0,n=ra}finally{try{!k&&q.return&&q.return()}finally{if(l)throw n;}}0===f?this.plugins.push(d.defaultPrecacheCacheabilityPlugin):
1<f&&null!==a&&this.plugins.splice(a,1)}}]);return d}(p.Strategy);d.defaultPrecacheCacheabilityPlugin={cacheWillUpdate:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function w(a){var d=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(d&&!(400<=d.status)){a.next=2;break}return a.abrupt("return",null);case 2:return a.abrupt("return",d);case 3:case "end":return a.stop()}},w,this)}));return function(d){return a.apply(this,arguments)}}()};
d.copyRedirectedCacheableResponsesPlugin={cacheWillUpdate:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function w(a){var d=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(!d.redirected){a.next=6;break}a.next=3;return(0,f.copyResponse)(d);case 3:a.t0=a.sent;a.next=7;break;case 6:a.t0=d;case 7:return a.abrupt("return",a.t0);case 8:case "end":return a.stop()}},w,this)}));return function(d){return a.apply(this,arguments)}}()};
a.PrecacheStrategy=d};
shadow$provide[63]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheController=void 0;d(19);var f=d(22);d(15);var n=d(18),q=d(32),t=d(54),k=d(55),C=d(56);d(57);d(58);var x=d(62);d(53);p=function(){function a(){var d=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{},k=d.cacheName,l=d.plugins;l=void 0===l?[]:l;d=d.fallbackToNetwork;d=void 0===d?!0:d;g.shadow.js.babel.classCallCheck(this,a);this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=
new Map;this._strategy=new x.PrecacheStrategy({cacheName:f.cacheNames.getPrecacheName(k),plugins:[].concat(g.shadow.js.babel.toConsumableArray(l),[new C.PrecacheCacheKeyPlugin({precacheController:this})]),fallbackToNetwork:d});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}g.shadow.js.babel.createClass(a,[{key:"precache",value:function(a){this.addToCacheList(a);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",
this.activate),this._installAndActiveListenersAdded=!0)}},{key:"addToCacheList",value:function(a){var d=[],f=!0,g=!1,k=void 0;try{for(var h=a[Symbol.iterator](),q;!(f=(q=h.next()).done);f=!0){var p=q.value;"string"===typeof p?d.push(p):p&&void 0===p.revision&&d.push(p.url);var w=(0,t.createCacheKey)(p),r=w.cacheKey,x=w.url,u="string"!==typeof p&&p.revision?"reload":"default";if(this._urlsToCacheKeys.has(x)&&this._urlsToCacheKeys.get(x)!==r)throw new n.WorkboxError("add-to-cache-list-conflicting-entries",
{firstEntry:this._urlsToCacheKeys.get(x),secondEntry:r});if("string"!==typeof p&&p.integrity){if(this._cacheKeysToIntegrities.has(r)&&this._cacheKeysToIntegrities.get(r)!==p.integrity)throw new n.WorkboxError("add-to-cache-list-conflicting-integrities",{url:x});this._cacheKeysToIntegrities.set(r,p.integrity)}this._urlsToCacheKeys.set(x,r);this._urlsToCacheModes.set(x,u);if(0<d.length){var C="Workbox is precaching URLs without revision "+("info: "+d.join(", ")+"\nThis is generally NOT safe. ")+"Learn more at https://bit.ly/wb-precache";
console.warn(C)}}}catch(da){g=!0,k=da}finally{try{!f&&h.return&&h.return()}finally{if(g)throw k;}}}},{key:"install",value:function(a){var d=this;return(0,q.waitUntil)(a,g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(){var f,h,n,q,p,t,w,r,x,u,C,D,G,O,ba;return regeneratorRuntime.wrap(function(y){for(;;)switch(y.prev=y.next){case 0:f=new k.PrecacheInstallReportPlugin,d.strategy.plugins.push(f),h=!0,n=!1,q=void 0,y.prev=5,p=d._urlsToCacheKeys[Symbol.iterator]();case 7:if(h=(t=
p.next()).done){y.next=20;break}w=t.value;r=g.shadow.js.babel.slicedToArray(w,2);x=r[0];u=r[1];C=d._cacheKeysToIntegrities.get(u);D=d._urlsToCacheModes.get(x);G=new Request(x,{integrity:C,cache:D,credentials:"same-origin"});y.next=17;return Promise.all(d.strategy.handleAll({params:{cacheKey:u},request:G,event:a}));case 17:h=!0;y.next=7;break;case 20:y.next=26;break;case 22:y.prev=22,y.t0=y["catch"](5),n=!0,q=y.t0;case 26:y.prev=26,y.prev=27,!h&&p.return&&p.return();case 29:y.prev=29;if(!n){y.next=
32;break}throw q;case 32:return y.finish(29);case 33:return y.finish(26);case 34:return O=f.updatedURLs,ba=f.notUpdatedURLs,y.abrupt("return",{updatedURLs:O,notUpdatedURLs:ba});case 37:case "end":return y.stop()}},I,d,[[5,22,26,34],[27,,29,33]])})))}},{key:"activate",value:function(a){var d=this;return(0,q.waitUntil)(a,g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(){var a,f,g,k,n,q,p,t,w,r;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return h.next=
2,self.caches.open(d.strategy.cacheName);case 2:return a=h.sent,h.next=5,a.keys();case 5:f=h.sent,g=new Set(d._urlsToCacheKeys.values()),k=[],n=!0,q=!1,p=void 0,h.prev=11,t=f[Symbol.iterator]();case 13:if(n=(w=t.next()).done){h.next=22;break}r=w.value;if(g.has(r.url)){h.next=19;break}h.next=18;return a.delete(r);case 18:k.push(r.url);case 19:n=!0;h.next=13;break;case 22:h.next=28;break;case 24:h.prev=24,h.t0=h["catch"](11),q=!0,p=h.t0;case 28:h.prev=28,h.prev=29,!n&&t.return&&t.return();case 31:h.prev=
31;if(!q){h.next=34;break}throw p;case 34:return h.finish(31);case 35:return h.finish(28);case 36:return h.abrupt("return",{deletedURLs:k});case 38:case "end":return h.stop()}},I,d,[[11,24,28,36],[29,,31,35]])})))}},{key:"getURLsToCacheKeys",value:function(){return this._urlsToCacheKeys}},{key:"getCachedURLs",value:function(){return[].concat(g.shadow.js.babel.toConsumableArray(this._urlsToCacheKeys.keys()))}},{key:"getCacheKeyForURL",value:function(a){a=new URL(a,location.href);return this._urlsToCacheKeys.get(a.href)}},
{key:"getIntegrityForCacheKey",value:function(a){return this._cacheKeysToIntegrities.get(a)}},{key:"matchPrecache",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function I(a){var d,f,g;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:d=a instanceof Request?a.url:a;f=this.getCacheKeyForURL(d);if(!f){h.next=7;break}h.next=5;return self.caches.open(this.strategy.cacheName);case 5:return g=h.sent,h.abrupt("return",g.match(f));case 7:return h.abrupt("return",
void 0);case 8:case "end":return h.stop()}},I,this)}));return function(d){return a.apply(this,arguments)}}()},{key:"createHandlerBoundToURL",value:function(a){var d=this,f=this.getCacheKeyForURL(a);if(!f)throw new n.WorkboxError("non-precached-url",{url:a});return function(g){g.request=new Request(a);g.params=Object.assign({cacheKey:f},g.params);return d.strategy.handle(g)}}},{key:"strategy",get:function(){return this._strategy}}]);return a}();a.PrecacheController=p};
shadow$provide[64]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.getOrCreatePrecacheController=void 0;var f=d(63);d(53);var n=void 0;a.getOrCreatePrecacheController=function(){n||(n=new f.PrecacheController);return n}};
shadow$provide[65]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.addPlugins=void 0;var f=d(64);d(53);a.addPlugins=function(a){var d;(d=(0,f.getOrCreatePrecacheController)().strategy.plugins).push.apply(d,g.shadow.js.babel.toConsumableArray(a))}};
shadow$provide[66]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.removeIgnoredSearchParams=function(a){for(var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[],f=function(f){d.some(function(a){return a.test(f)})&&a.searchParams.delete(f)},p=[].concat(g.shadow.js.babel.toConsumableArray(a.searchParams.keys())),k=0;k<p.length;k++)f(p[k]);return a};d(53)};
shadow$provide[67]=function(g,p,d,r,a,u){function f(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{},f=d.ignoreURLParametersMatching,g=void 0===f?[/^utm_/,/^fbclid$/]:f;f=d.directoryIndex;var p=void 0===f?"index.html":f;f=d.cleanURLs;var t=void 0===f?!0:f,r=d.urlManipulation,l,u,N,h,K,y,ha,ra,P,sa,ca;return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=new URL(a,location.href),l.hash="",d.next=4,l.href;case 4:return u=(0,n.removeIgnoredSearchParams)(l,
g),d.next=7,u.href;case 7:if(!p||!u.pathname.endsWith("/")){d.next=12;break}N=new URL(u.href);N.pathname+=p;d.next=12;return N.href;case 12:if(!t){d.next=17;break}h=new URL(u.href);h.pathname+=".html";d.next=17;return h.href;case 17:if(!r){d.next=45;break}K=r({url:l});y=!0;ha=!1;ra=void 0;d.prev=22;P=K[Symbol.iterator]();case 24:if(y=(sa=P.next()).done){d.next=31;break}ca=sa.value;d.next=28;return ca.href;case 28:y=!0;d.next=24;break;case 31:d.next=37;break;case 33:d.prev=33,d.t0=d["catch"](22),ha=
!0,ra=d.t0;case 37:d.prev=37,d.prev=38,!y&&P.return&&P.return();case 40:d.prev=40;if(!ha){d.next=43;break}throw ra;case 43:return d.finish(40);case 44:return d.finish(37);case 45:case "end":return d.stop()}},q,this,[[22,33,37,45],[38,,40,44]])}Object.defineProperty(a,"__esModule",{value:!0});a.generateURLVariations=f;var n=d(66);d(53);var q=regeneratorRuntime.mark(f)};
shadow$provide[68]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheRoute=void 0;d(15);d(29);p=d(44);var f=d(67);d(53);d=function(a){function d(a,k){g.shadow.js.babel.classCallCheck(this,d);return g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,function(d){d=d.request;var g=a.getURLsToCacheKeys(),n=!0,q=!1,p=void 0;try{for(var l=(0,f.generateURLVariations)(d.url,k)[Symbol.iterator](),t;!(n=(t=l.next()).done);n=!0){var r=
g.get(t.value);if(r){var h=a.getIntegrityForCacheKey(r);return{cacheKey:r,integrity:h}}}}catch(K){q=!0,p=K}finally{try{!n&&l.return&&l.return()}finally{if(q)throw p;}}},a.strategy))}g.shadow.js.babel.inherits(d,a);return d}(p.Route);a.PrecacheRoute=d};
shadow$provide[69]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.addRoute=void 0;var f=d(49),n=d(64),q=d(68);d(53);a.addRoute=function(a){var d=(0,n.getOrCreatePrecacheController)();a=new q.PrecacheRoute(d,a);(0,f.registerRoute)(a)}};
shadow$provide[70]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.deleteOutdatedCaches=void 0;d(53);p=function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"-precache-",f,g;return regeneratorRuntime.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:return k.next=2,self.caches.keys();case 2:return f=k.sent,g=f.filter(function(f){return f.includes(d)&&f.includes(self.registration.scope)&&
f!==a}),k.next=6,Promise.all(g.map(function(a){return self.caches.delete(a)}));case 6:return k.abrupt("return",g);case 7:case "end":return k.stop()}},t,void 0)}));return function(d){return a.apply(this,arguments)}}();a.deleteOutdatedCaches=p};
shadow$provide[71]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.cleanupOutdatedCaches=void 0;var f=d(22);d(15);var n=d(70);d(53);a.cleanupOutdatedCaches=function(){self.addEventListener("activate",function(a){var d=f.cacheNames.getPrecacheName();a.waitUntil((0,n.deleteOutdatedCaches)(d).then(function(a){}))})}};
shadow$provide[72]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.createHandlerBoundToURL=void 0;var f=d(64);d(53);a.createHandlerBoundToURL=function(a){return(0,f.getOrCreatePrecacheController)().createHandlerBoundToURL(a)}};
shadow$provide[73]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.getCacheKeyForURL=void 0;var f=d(64);d(53);a.getCacheKeyForURL=function(a){return(0,f.getOrCreatePrecacheController)().getCacheKeyForURL(a)}};
shadow$provide[74]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.matchPrecache=void 0;var f=d(64);d(53);a.matchPrecache=function(a){return(0,f.getOrCreatePrecacheController)().matchPrecache(a)}};
shadow$provide[75]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.precache=void 0;var f=d(64);d(53);a.precache=function(a){(0,f.getOrCreatePrecacheController)().precache(a)}};
shadow$provide[76]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.precacheAndRoute=void 0;var f=d(69),n=d(75);d(53);a.precacheAndRoute=function(a,d){(0,n.precache)(a);(0,f.addRoute)(d)}};
shadow$provide[77]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheFallbackPlugin=void 0;var f=d(64);d(53);a.PrecacheFallbackPlugin=function t(a){var d=this,q=a.fallbackURL;a=a.precacheController;g.shadow.js.babel.classCallCheck(this,t);this.handlerDidError=function(){return d._precacheController.matchPrecache(d._fallbackURL)};this._fallbackURL=q;this._precacheController=a||(0,f.getOrCreatePrecacheController)()}};
shadow$provide[78]=function(g,p,d,r,a,u){d(53)};
shadow$provide[79]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.PrecacheFallbackPlugin=a.PrecacheStrategy=a.PrecacheRoute=a.PrecacheController=a.precacheAndRoute=a.precache=a.matchPrecache=a.getCacheKeyForURL=a.createHandlerBoundToURL=a.cleanupOutdatedCaches=a.addRoute=a.addPlugins=void 0;var f=d(78);Object.keys(f).forEach(function(d){"default"!==d&&"__esModule"!==d&&Object.defineProperty(a,d,{enumerable:!0,get:function(){return f[d]}})});g=d(65);p=d(69);r=d(71);u=d(72);
var n=d(73),q=d(74),t=d(75),k=d(76),C=d(63),x=d(68),D=d(62),w=d(77);d(53);a.addPlugins=g.addPlugins;a.addRoute=p.addRoute;a.cleanupOutdatedCaches=r.cleanupOutdatedCaches;a.createHandlerBoundToURL=u.createHandlerBoundToURL;a.getCacheKeyForURL=n.getCacheKeyForURL;a.matchPrecache=q.matchPrecache;a.precache=t.precache;a.precacheAndRoute=k.precacheAndRoute;a.PrecacheController=C.PrecacheController;a.PrecacheRoute=x.PrecacheRoute;a.PrecacheStrategy=D.PrecacheStrategy;a.PrecacheFallbackPlugin=w.PrecacheFallbackPlugin};
shadow$provide[80]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.messages=void 0;var f=d(15),n=d(29);d(59);a.messages={strategyStart:function(a,d){return"Using "+a+" to respond to '"+(0,n.getFriendlyURL)(d.url)+"'"},printFinalResponse:function(a){a&&(f.logger.groupCollapsed("View the final response here."),f.logger.log(a||"[No response returned]"),f.logger.groupEnd())}}};
shadow$provide[81]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.CacheFirst=void 0;d(19);var f=d(15),n=d(18);p=d(61);var q=d(80);d(59);d=function(a){function d(){g.shadow.js.babel.classCallCheck(this,d);return g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).apply(this,arguments))}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function G(a,
d){var g,k,p,h;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return l.next=4,d.cacheMatch(a);case 4:g=l.sent;k=void 0;if(g){l.next=20;break}l.prev=8;l.next=11;return d.fetchAndCachePut(a);case 11:g=l.sent;l.next=17;break;case 14:l.prev=14,l.t0=l["catch"](8),l.t0 instanceof Error&&(k=l.t0);case 17:l.next=21;break;case 20:case 21:l.next=44;break;case 30:l.prev=30,l.t1=l["catch"](26),p=!0,h=l.t1;case 34:l.prev=34,l.prev=35,(void 0).return&&(void 0).return();case 37:l.prev=
37;if(!p){l.next=40;break}throw h;case 40:return l.finish(37);case 41:return l.finish(34);case 42:q.messages.printFinalResponse(g),f.logger.groupEnd();case 44:if(g){l.next=46;break}throw new n.WorkboxError("no-response",{url:a.url,error:k});case 46:return l.abrupt("return",g);case 47:case "end":return l.stop()}},G,this,[[8,14],[26,30,34,42],[35,,37,41]])}));return function(d,f){return a.apply(this,arguments)}}()}]);return d}(p.Strategy);a.CacheFirst=d};
shadow$provide[82]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.CacheOnly=void 0;d(19);d(15);var f=d(18);p=d(61);d(80);d(59);d=function(a){function d(){g.shadow.js.babel.classCallCheck(this,d);return g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).apply(this,arguments))}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function D(a,
d){var g;return regeneratorRuntime.wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=3,d.cacheMatch(a);case 3:if(g=n.sent){n.next=7;break}throw new f.WorkboxError("no-response",{url:a.url});case 7:return n.abrupt("return",g);case 8:case "end":return n.stop()}},D,this)}));return function(d,f){return a.apply(this,arguments)}}()}]);return d}(p.Strategy);a.CacheOnly=d};
shadow$provide[83]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.cacheOkAndOpaquePlugin=void 0;d(59);a.cacheOkAndOpaquePlugin={cacheWillUpdate:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function t(a){var d=a.response;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:if(200!==d.status&&0!==d.status){a.next=2;break}return a.abrupt("return",d);case 2:return a.abrupt("return",null);case 3:case "end":return a.stop()}},
t,void 0)}));return function(d){return a.apply(this,arguments)}}()}};
shadow$provide[84]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.NetworkFirst=void 0;d(19);var f=d(15),n=d(18),q=d(83);p=d(61);var t=d(80);d(59);d=function(a){function d(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};g.shadow.js.babel.classCallCheck(this,d);var f=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,a));f.plugins.some(function(a){return"cacheWillUpdate"in a})||f.plugins.unshift(q.cacheOkAndOpaquePlugin);
f._networkTimeoutSeconds=a.networkTimeoutSeconds||0;return f}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function l(a,d){var k=this,q,h,p,r,u,x,w,C,G,da;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return q=[],h=[],p=void 0,this._networkTimeoutSeconds&&(r=this._getTimeoutPromise({request:a,logs:q,handler:d}),u=r.id,x=r.promise,p=u,h.push(x)),w=this._getNetworkPromise({timeoutId:p,
request:a,logs:q,handler:d}),h.push(w),l.next=9,d.waitUntil(g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function R(){return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,d.waitUntil(Promise.race(h));case 2:a.t0=a.sent;if(a.t0){a.next=7;break}a.next=6;return w;case 6:a.t0=a.sent;case 7:return a.abrupt("return",a.t0);case 8:case "end":return a.stop()}},R,k)}))());case 9:C=l.sent;l.next=33;break;case 19:l.prev=19,l.t0=l["catch"](15),G=!0,da=l.t0;
case 23:l.prev=23,l.prev=24,(void 0).return&&(void 0).return();case 26:l.prev=26;if(!G){l.next=29;break}throw da;case 29:return l.finish(26);case 30:return l.finish(23);case 31:t.messages.printFinalResponse(C),f.logger.groupEnd();case 33:if(C){l.next=35;break}throw new n.WorkboxError("no-response",{url:a.url});case 35:return l.abrupt("return",C);case 36:case "end":return l.stop()}},l,this,[[15,19,23,31],[24,,26,30]])}));return function(d,f){return a.apply(this,arguments)}}()},{key:"_getTimeoutPromise",
value:function(a){var d=this,f=a.request,k=a.handler,l=void 0;return{promise:new Promise(function(a){var n=function(){var h=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function y(){return regeneratorRuntime.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return d.t0=a,d.next=4,k.cacheMatch(f);case 4:d.t1=d.sent,(0,d.t0)(d.t1);case 6:case "end":return d.stop()}},y,d)}));return function(){return h.apply(this,arguments)}}();l=setTimeout(n,1E3*d._networkTimeoutSeconds)}),id:l}}},{key:"_getNetworkPromise",
value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function G(a){var d=a.timeoutId,f=a.request,g=a.handler,h,k;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return k=h=void 0,a.prev=2,a.next=5,g.fetchAndCachePut(f);case 5:k=a.sent;a.next=11;break;case 8:a.prev=8,a.t0=a["catch"](2),a.t0 instanceof Error&&(h=a.t0);case 11:d&&clearTimeout(d);if(!h&&k){a.next=18;break}a.next=16;return g.cacheMatch(f);case 16:k=a.sent;case 18:return a.abrupt("return",
k);case 19:case "end":return a.stop()}},G,this,[[2,8]])}));return function(d){return a.apply(this,arguments)}}()}]);return d}(p.Strategy);a.NetworkFirst=d};
shadow$provide[85]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.NetworkOnly=void 0;d(19);d(15);var f=d(30),n=d(18);p=d(61);d(80);d(59);d=function(a){function d(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};g.shadow.js.babel.classCallCheck(this,d);var f=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,a));f._networkTimeoutSeconds=a.networkTimeoutSeconds||0;return f}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,
[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function w(a,d){var g,k,p,q;return regeneratorRuntime.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return k=g=void 0,h.prev=3,p=[d.fetch(a)],this._networkTimeoutSeconds&&(q=(0,f.timeout)(1E3*this._networkTimeoutSeconds),p.push(q)),h.next=8,Promise.race(p);case 8:if(k=h.sent){h.next=11;break}throw Error("Timed out the network response after "+(this._networkTimeoutSeconds+" seconds."));case 11:h.next=
16;break;case 13:h.prev=13,h.t0=h["catch"](3),h.t0 instanceof Error&&(g=h.t0);case 16:if(k){h.next=19;break}throw new n.WorkboxError("no-response",{url:a.url,error:g});case 19:return h.abrupt("return",k);case 20:case "end":return h.stop()}},w,this,[[3,13]])}));return function(d,f){return a.apply(this,arguments)}}()}]);return d}(p.Strategy);a.NetworkOnly=d};
shadow$provide[86]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.StaleWhileRevalidate=void 0;d(19);var f=d(15),n=d(18),q=d(83);p=d(61);var t=d(80);d(59);d=function(a){function d(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};g.shadow.js.babel.classCallCheck(this,d);a=g.shadow.js.babel.possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,a));a.plugins.some(function(a){return"cacheWillUpdate"in a})||a.plugins.unshift(q.cacheOkAndOpaquePlugin);
return a}g.shadow.js.babel.inherits(d,a);g.shadow.js.babel.createClass(d,[{key:"_handle",value:function(){var a=g.shadow.js.babel.asyncToGenerator(regeneratorRuntime.mark(function l(a,d){var g,k,h,p,q;return regeneratorRuntime.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return g=d.fetchAndCachePut(a).catch(function(){}),l.next=5,d.cacheMatch(a);case 5:k=l.sent;h=void 0;if(!k){l.next=11;break}l.next=21;break;case 11:return l.prev=12,l.next=15,g;case 15:k=l.sent;l.next=21;break;case 18:l.prev=
18,l.t0=l["catch"](12),l.t0 instanceof Error&&(h=l.t0);case 21:l.next=44;break;case 30:l.prev=30,l.t1=l["catch"](26),p=!0,q=l.t1;case 34:l.prev=34,l.prev=35,(void 0).return&&(void 0).return();case 37:l.prev=37;if(!p){l.next=40;break}throw q;case 40:return l.finish(37);case 41:return l.finish(34);case 42:t.messages.printFinalResponse(k),f.logger.groupEnd();case 44:if(k){l.next=46;break}throw new n.WorkboxError("no-response",{url:a.url,error:h});case 46:return l.abrupt("return",k);case 47:case "end":return l.stop()}},
l,this,[[12,18],[26,30,34,42],[35,,37,41]])}));return function(d,f){return a.apply(this,arguments)}}()}]);return d}(p.Strategy);a.StaleWhileRevalidate=d};
shadow$provide[87]=function(g,p,d,r,a,u){Object.defineProperty(a,"__esModule",{value:!0});a.StrategyHandler=a.Strategy=a.StaleWhileRevalidate=a.NetworkOnly=a.NetworkFirst=a.CacheOnly=a.CacheFirst=void 0;g=d(81);p=d(82);r=d(84);u=d(85);var f=d(86),n=d(61),q=d(60);d(59);a.CacheFirst=g.CacheFirst;a.CacheOnly=p.CacheOnly;a.NetworkFirst=r.NetworkFirst;a.NetworkOnly=u.NetworkOnly;a.StaleWhileRevalidate=f.StaleWhileRevalidate;a.Strategy=n.Strategy;a.StrategyHandler=q.StrategyHandler};
'use strict';ir(13,{});var jL={};jL["typeof"]="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};jL.asyncIterator=function(a){if("function"===typeof Symbol){if(Symbol.asyncIterator){var b=a[Symbol.asyncIterator];if(null!=b)return b.call(a)}if(Symbol.iterator)return a[Symbol.iterator]()}throw new TypeError("Object is not async iterable");};
jL.asyncGenerator=function(){function a(a){this.value=a}function b(b){function c(d,f){try{var g=b[d](f),h=g.value;h instanceof a?Promise.resolve(h.value).then(function(a){c("next",a)},function(a){c("throw",a)}):e(g.done?"return":"normal",g.value)}catch(v){e("throw",v)}}function e(a,b){switch(a){case "return":f.resolve({value:b,done:!0});break;case "throw":f.reject(b);break;default:f.resolve({value:b,done:!1})}(f=f.next)?c(f.key,f.arg):g=null}var f,g;this._invoke=function(a,b){return new Promise(function(d,
e){d={key:a,arg:b,resolve:d,reject:e,next:null};g?g=g.next=d:(f=g=d,c(a,b))})};"function"!==typeof b["return"]&&(this["return"]=void 0)}"function"===typeof Symbol&&Symbol.asyncIterator&&(b.prototype[Symbol.asyncIterator]=function(){return this});b.prototype.next=function(a){return this._invoke("next",a)};b.prototype["throw"]=function(a){return this._invoke("throw",a)};b.prototype["return"]=function(a){return this._invoke("return",a)};return{wrap:function(a){return function(){return new b(a.apply(this,
arguments))}},Yh:function(b){return new a(b)}}}();
jL.asyncGeneratorDelegate=function(a,b){function c(c,d){e=!0;d=new Promise(function(b){b(a[c](d))});return{done:!1,value:b(d)}}var d={},e=!1;"function"===typeof Symbol&&Symbol.iterator&&(d[Symbol.iterator]=function(){return this});d.next=function(a){return e?(e=!1,a):c("next",a)};"function"===typeof a["throw"]&&(d["throw"]=function(a){if(e)throw e=!1,a;return c("throw",a)});"function"===typeof a["return"]&&(d["return"]=function(a){return c("return",a)});return d};
jL.asyncToGenerator=function(a){return function(){var b=a.apply(this,arguments);return new Promise(function(a,d){function c(e,g){try{var f=b[e](g),l=f.value}catch(m){d(m);return}if(f.done)a(l);else return Promise.resolve(l).then(function(a){c("next",a)},function(a){c("throw",a)})}return c("next")})}};jL.classCallCheck=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");};
jL.createClass=function(){function a(a,c){for(var b=0;b<c.length;b++){var e=c[b];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(a,e.key,e)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}();jL.defineEnumerableProperties=function(a,b){for(var c in b){var d=b[c];d.configurable=d.enumerable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,c,d)}return a};
jL.defaults=function(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f&&f.configurable&&void 0===a[e]&&Object.defineProperty(a,e,f)}return a};jL.defineProperty=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a};
jL["extends"]=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};jL.get=function kL(a,b,c){null===a&&(a=Function.prototype);var e=Object.getOwnPropertyDescriptor(a,b);if(void 0===e){if(a=Object.getPrototypeOf(a),null!==a)return kL(a,b,c)}else{if("value"in e)return e.value;b=e.get;return void 0===b?void 0:b.call(c)}};
jL.inherits=function(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)};jL["instanceof"]=function(a,b){return null!=b&&"undefined"!==typeof Symbol&&b[Symbol.Xh]?b[Symbol.Xh](a):a instanceof b};
jL.interopRequireDefault=function(a){return a&&a.__esModule?a:{"default":a}};jL.interopRequireWildcard=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);b["default"]=a;return b};jL.newArrowCheck=function(a,b){if(a!==b)throw new TypeError("Cannot instantiate an arrow function");};jL.objectDestructuringEmpty=function(a){if(null==a)throw new TypeError("Cannot destructure undefined");};
jL.objectWithoutProperties=function(a,b){var c={},d;for(d in a)0<=b.indexOf(d)||Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=a[d]);return c};jL.possibleConstructorReturn=function(a,b){if(!a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?a:b};jL.selfGlobal="undefined"===typeof global?self:global;
jL.set=function lL(a,b,c,d){var f=Object.getOwnPropertyDescriptor(a,b);void 0===f?(a=Object.getPrototypeOf(a),null!==a&&lL(a,b,c,d)):"value"in f&&f.writable?f.value=c:(b=f.set,void 0!==b&&b.call(d,c));return c};
jL.slicedToArray=function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var c=[],d=!0,e=!1,f=void 0;try{for(var g=a[Symbol.iterator](),h;!(d=(h=g.next()).done)&&(c.push(h.value),!b||c.length!==b);d=!0);}catch(l){e=!0,f=l}finally{try{if(!d&&g["return"])g["return"]()}finally{if(e)throw f;}}return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");};
jL.slicedToArrayLoose=function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var c=[];a=a[Symbol.iterator]();for(var d;!(d=a.next()).done&&(c.push(d.value),!b||c.length!==b););return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");};jL.taggedTemplateLiteral=function(a,b){return Object.freeze(Object.defineProperties(a,{raw:{value:Object.freeze(b)}}))};jL.taggedTemplateLiteralLoose=function(a,b){a.raw=b;return a};
jL.temporalRef=function(a,b,c){if(a===c)throw new ReferenceError(b+" is not defined - temporal dead zone");return a};jL.temporalUndefined={};jL.toArray=function(a){return Array.isArray(a)?a:Array.from(a)};jL.toConsumableArray=function(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)};Di("shadow.js.babel",jL);var rL=ir(40,{});var pL=ir(52,{});var sL=ir(79,{});var qL=ir(87,{});var tL=Xi(re.se(function(a){return["/solitaire",u.ga(a)].join("")},new X(null,22,5,Y,"/ /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /assets/images/back.jpeg /assets/images/clubs.svg /assets/images/diamonds.svg /assets/images/hearts.svg /assets/images/spades.svg /assets/images/icon192.png /assets/images/icon512.png /shared.js /app.js".split(" "),
null)));(function(){self.addEventListener("install",function(a){var b=rL.cacheNames.runtime;return a.waitUntil(caches.open(b).then(function(){return function(a){return a.addAll(tL)}}(b)))});var a=new qL.CacheFirst;pL.registerRoute(function(a){return I.se(a.request.destination,"image")},a);a=new qL.StaleWhileRevalidate;pL.setDefaultHandler(a);sL.precacheAndRoute([{url:"/solitaire/",revision:"4ce76e31cb25e8a6a788761eb9bdc14fdcc8b1ca15340f2287aabd69aba3110b"}]);a=new pL.NavigationRoute(sL.createHandlerBoundToURL("/solitaire/"));
return pL.registerRoute(a)})();