importScripts("shared.js");
(function(){
shadow$provide[14]=function(E,l,O,g){E=function(h){function n(q,x,w){Object.defineProperty(q,x,{value:w,enumerable:!0,configurable:!0,writable:!0});return q[x]}function v(q,x,w,K){x=Object.create((x&&x.prototype instanceof p?x:p).prototype);K=new M(K||[]);x._invoke=G(q,w,K);return x}function t(q,x,w){try{return{type:"normal",arg:q.call(x,w)}}catch(K){return{type:"throw",arg:K}}}function p(){}function B(){}function C(){}function Q(q){["next","throw","return"].forEach(function(x){n(q,x,function(w){return this._invoke(x,
w)})})}function A(q,x){function w(F,T,Y,ka){F=t(q[F],q,T);if("throw"===F.type)ka(F.arg);else{var la=F.arg;return(F=la.value)&&"object"===typeof F&&aa.call(F,"__await")?x.resolve(F.__await).then(function(sa){w("next",sa,Y,ka)},function(sa){w("throw",sa,Y,ka)}):x.resolve(F).then(function(sa){la.value=sa;Y(la)},function(sa){return w("throw",sa,Y,ka)})}}var K;this._invoke=function(F,T){function Y(){return new x(function(ka,la){w(F,T,ka,la)})}return K=K?K.then(Y,Y):Y()}}function G(q,x,w){var K=va;return function(F,
T){if(K===Ba)throw Error("Generator is already running");if(K===Pa){if("throw"===F)throw T;return V()}w.method=F;for(w.arg=T;;){if(F=w.delegate)if(F=J(F,w)){if(F===ta)continue;return F}if("next"===w.method)w.sent=w._sent=w.arg;else if("throw"===w.method){if(K===va)throw K=Pa,w.arg;w.dispatchException(w.arg)}else"return"===w.method&&w.abrupt("return",w.arg);K=Ba;F=t(q,x,w);if("normal"===F.type){K=w.done?Pa:ua;if(F.arg===ta)continue;return{value:F.arg,done:w.done}}"throw"===F.type&&(K=Pa,w.method="throw",
w.arg=F.arg)}}}function J(q,x){var w=q.iterator[x.method];if(w===ia){x.delegate=null;if("throw"===x.method){if(q.iterator["return"]&&(x.method="return",x.arg=ia,J(q,x),"throw"===x.method))return ta;x.method="throw";x.arg=new TypeError("The iterator does not provide a 'throw' method")}return ta}w=t(w,q.iterator,x.arg);if("throw"===w.type)return x.method="throw",x.arg=w.arg,x.delegate=null,ta;w=w.arg;if(!w)return x.method="throw",x.arg=new TypeError("iterator result is not an object"),x.delegate=null,
ta;if(w.done)x[q.resultName]=w.value,x.next=q.nextLoc,"return"!==x.method&&(x.method="next",x.arg=ia);else return w;x.delegate=null;return ta}function U(q){var x={tryLoc:q[0]};1 in q&&(x.catchLoc=q[1]);2 in q&&(x.finallyLoc=q[2],x.afterLoc=q[3]);this.tryEntries.push(x)}function Z(q){var x=q.completion||{};x.type="normal";delete x.arg;q.completion=x}function M(q){this.tryEntries=[{tryLoc:"root"}];q.forEach(U,this);this.reset(!0)}function P(q){if(q){var x=q[pa];if(x)return x.call(q);if("function"===
typeof q.next)return q;if(!isNaN(q.length)){var w=-1;x=function F(){for(;++w<q.length;)if(aa.call(q,w))return F.value=q[w],F.done=!1,F;F.value=ia;F.done=!0;return F};return x.next=x}}return{next:V}}function V(){return{value:ia,done:!0}}var ma=Object.prototype,aa=ma.hasOwnProperty,ia,N="function"===typeof Symbol?Symbol:{},pa=N.iterator||"@@iterator",oa=N.asyncIterator||"@@asyncIterator",ra=N.toStringTag||"@@toStringTag";try{n({},"")}catch(q){n=function(x,w,K){return x[w]=K}}h.wrap=v;var va="suspendedStart",
ua="suspendedYield",Ba="executing",Pa="completed",ta={};N={};n(N,pa,function(){return this});var qa=Object.getPrototypeOf;(qa=qa&&qa(qa(P([]))))&&qa!==ma&&aa.call(qa,pa)&&(N=qa);var Fa=C.prototype=p.prototype=Object.create(N);B.prototype=C;n(Fa,"constructor",C);n(C,"constructor",B);B.displayName=n(C,ra,"GeneratorFunction");h.isGeneratorFunction=function(q){return(q="function"===typeof q&&q.constructor)?q===B||"GeneratorFunction"===(q.displayName||q.name):!1};h.mark=function(q){Object.setPrototypeOf?
Object.setPrototypeOf(q,C):(q.__proto__=C,n(q,ra,"GeneratorFunction"));q.prototype=Object.create(Fa);return q};h.awrap=function(q){return{__await:q}};Q(A.prototype);n(A.prototype,oa,function(){return this});h.AsyncIterator=A;h.async=function(q,x,w,K,F){void 0===F&&(F=Promise);var T=new A(v(q,x,w,K),F);return h.isGeneratorFunction(x)?T:T.next().then(function(Y){return Y.done?Y.value:T.next()})};Q(Fa);n(Fa,ra,"Generator");n(Fa,pa,function(){return this});n(Fa,"toString",function(){return"[object Generator]"});
h.keys=function(q){var x=[],w;for(w in q)x.push(w);x.reverse();return function F(){for(;x.length;){var T=x.pop();if(T in q)return F.value=T,F.done=!1,F}F.done=!0;return F}};h.values=P;M.prototype={constructor:M,reset:function(q){this.next=this.prev=0;this.sent=this._sent=ia;this.done=!1;this.delegate=null;this.method="next";this.arg=ia;this.tryEntries.forEach(Z);if(!q)for(var x in this)"t"===x.charAt(0)&&aa.call(this,x)&&!isNaN(+x.slice(1))&&(this[x]=ia)},stop:function(){this.done=!0;var q=this.tryEntries[0].completion;
if("throw"===q.type)throw q.arg;return this.rval},dispatchException:function(q){function x(la,sa){T.type="throw";T.arg=q;w.next=la;sa&&(w.method="next",w.arg=ia);return!!sa}if(this.done)throw q;for(var w=this,K=this.tryEntries.length-1;0<=K;--K){var F=this.tryEntries[K],T=F.completion;if("root"===F.tryLoc)return x("end");if(F.tryLoc<=this.prev){var Y=aa.call(F,"catchLoc"),ka=aa.call(F,"finallyLoc");if(Y&&ka){if(this.prev<F.catchLoc)return x(F.catchLoc,!0);if(this.prev<F.finallyLoc)return x(F.finallyLoc)}else if(Y){if(this.prev<
F.catchLoc)return x(F.catchLoc,!0)}else if(ka){if(this.prev<F.finallyLoc)return x(F.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(q,x){for(var w=this.tryEntries.length-1;0<=w;--w){var K=this.tryEntries[w];if(K.tryLoc<=this.prev&&aa.call(K,"finallyLoc")&&this.prev<K.finallyLoc){var F=K;break}}F&&("break"===q||"continue"===q)&&F.tryLoc<=x&&x<=F.finallyLoc&&(F=null);w=F?F.completion:{};w.type=q;w.arg=x;return F?(this.method="next",this.next=F.finallyLoc,ta):
this.complete(w)},complete:function(q,x){if("throw"===q.type)throw q.arg;"break"===q.type||"continue"===q.type?this.next=q.arg:"return"===q.type?(this.rval=this.arg=q.arg,this.method="return",this.next="end"):"normal"===q.type&&x&&(this.next=x);return ta},finish:function(q){for(var x=this.tryEntries.length-1;0<=x;--x){var w=this.tryEntries[x];if(w.finallyLoc===q)return this.complete(w.completion,w.afterLoc),Z(w),ta}},"catch":function(q){for(var x=this.tryEntries.length-1;0<=x;--x){var w=this.tryEntries[x];
if(w.tryLoc===q){q=w.completion;if("throw"===q.type){var K=q.arg;Z(w)}return K}}throw Error("illegal catch attempt");},delegateYield:function(q,x,w){this.delegate={iterator:P(q),resultName:x,nextLoc:w};"next"===this.method&&(this.arg=ia);return ta}};return h}("object"===typeof O?O.exports:{});try{regeneratorRuntime=E}catch(h){"object"===typeof globalThis?globalThis.regeneratorRuntime=E:Function("r","regeneratorRuntime \x3d r")(E)}};
shadow$provide[15]=function(E,l,O,g){try{self["workbox:core:6.4.0"]&&_()}catch(h){}};
shadow$provide[16]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.logger=void 0;l(15);g.logger=null};
shadow$provide[17]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.messages=void 0;l(15);g.messages={"invalid-value":({paramName:h,validValueDescription:n,value:v})=>{if(!h||!n)throw Error("Unexpected input to 'invalid-value' error.");return`The '${h}' parameter was given a value with an `+`unexpected value. ${n} Received a value of `+`${JSON.stringify(v)}.`},"not-an-array":({moduleName:h,className:n,funcName:v,paramName:t})=>{if(!(h&&n&&v&&t))throw Error("Unexpected input to 'not-an-array' error.");
return`The parameter '${t}' passed into `+`'${h}.${n}.${v}()' must be an array.`},"incorrect-type":({expectedType:h,paramName:n,moduleName:v,className:t,funcName:p})=>{if(!(h&&n&&v&&p))throw Error("Unexpected input to 'incorrect-type' error.");return`The parameter '${n}' passed into `+`'${v}.${t?`${t}.`:""}`+`${p}()' must be of type ${h}.`},"incorrect-class":({expectedClassName:h,paramName:n,moduleName:v,className:t,funcName:p,isReturnValueProblem:B})=>{if(!h||!v||!p)throw Error("Unexpected input to 'incorrect-class' error.");
t=t?`${t}.`:"";return B?"The return value from "+`'${v}.${t}${p}()' `+`must be an instance of class ${h}.`:`The parameter '${n}' passed into `+`'${v}.${t}${p}()' `+`must be an instance of class ${h}.`},"missing-a-method":({expectedMethod:h,paramName:n,moduleName:v,className:t,funcName:p})=>{if(!(h&&n&&v&&t&&p))throw Error("Unexpected input to 'missing-a-method' error.");return`${v}.${t}.${p}() expected the `+`'${n}' parameter to expose a '${h}' method.`},"add-to-cache-list-unexpected-type":({entry:h})=>
"An unexpected entry was passed to 'workbox-precaching.PrecacheController.addToCacheList()' The entry "+`'${JSON.stringify(h)}' isn't supported. You must supply an array of `+"strings with one or more characters, objects with a url property or Request objects.","add-to-cache-list-conflicting-entries":({firstEntry:h,secondEntry:n})=>{if(!h||!n)throw Error("Unexpected input to 'add-to-cache-list-duplicate-entries' error.");return"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${h} but different revision details. Workbox is `+"unable to cache and version the asset correctly. Please remove one of the entries."},"plugin-error-request-will-fetch":({thrownErrorMessage:h})=>{if(!h)throw Error("Unexpected input to 'plugin-error-request-will-fetch', error.");return"An error was thrown by a plugins 'requestWillFetch()' method. "+`The thrown error message was: '${h}'.`},"invalid-cache-name":({cacheNameId:h,value:n})=>{if(!h)throw Error("Expected a 'cacheNameId' for error 'invalid-cache-name'");
return"You must provide a name containing at least one character for "+`setCacheDetails({${h}: '...'}). Received a value of `+`'${JSON.stringify(n)}'`},"unregister-route-but-not-found-with-method":({method:h})=>{if(!h)throw Error("Unexpected input to 'unregister-route-but-not-found-with-method' error.");return"The route you're trying to unregister was not  previously "+`registered for the method type '${h}'.`},"unregister-route-route-not-registered":()=>"The route you're trying to unregister was not previously registered.",
"queue-replay-failed":({name:h})=>`Replaying the background sync queue '${h}' failed.`,"duplicate-queue-name":({name:h})=>`The Queue name '${h}' is already being used. `+"All instances of backgroundSync.Queue must be given unique names.","expired-test-without-max-age":({methodName:h,paramName:n})=>`The '${h}()' method can only be used when the `+`'${n}' is used in the constructor.`,"unsupported-route-type":({moduleName:h,className:n,funcName:v,paramName:t})=>`The supplied '${t}' parameter was an unsupported type. `+
`Please check the docs for ${h}.${n}.${v} for `+"valid input types.","not-array-of-class":({value:h,expectedClass:n,moduleName:v,className:t,funcName:p,paramName:B})=>`The supplied '${B}' parameter must be an array of `+`'${n}' objects. Received '${JSON.stringify(h)},'. `+`Please check the call to ${v}.${t}.${p}() `+"to fix the issue.","max-entries-or-age-required":({moduleName:h,className:n,funcName:v})=>"You must define either config.maxEntries or config.maxAgeSeconds"+`in ${h}.${n}.${v}`,"statuses-or-headers-required":({moduleName:h,
className:n,funcName:v})=>"You must define either config.statuses or config.headers"+`in ${h}.${n}.${v}`,"invalid-string":({moduleName:h,funcName:n,paramName:v})=>{if(!v||!h||!n)throw Error("Unexpected input to 'invalid-string' error.");return`When using strings, the '${v}' parameter must start with `+"'http' (for cross-origin matches) or '/' (for same-origin matches). "+`Please see the docs for ${h}.${n}() for `+"more info."},"channel-name-required":()=>"You must provide a channelName to construct a BroadcastCacheUpdate instance.",
"invalid-responses-are-same-args":()=>"The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.","expire-custom-caches-only":()=>"You must provide a 'cacheName' property when using the expiration plugin with a runtime caching strategy.","unit-must-be-bytes":({normalizedRangeHeader:h})=>{if(!h)throw Error("Unexpected input to 'unit-must-be-bytes' error.");return"The 'unit' portion of the Range header must be set to 'bytes'. "+`The Range header provided was "${h}"`},
"single-range-only":({normalizedRangeHeader:h})=>{if(!h)throw Error("Unexpected input to 'single-range-only' error.");return"Multiple ranges are not supported. Please use a  single start value, and optional end value. The Range header provided was "+`"${h}"`},"invalid-range-values":({normalizedRangeHeader:h})=>{if(!h)throw Error("Unexpected input to 'invalid-range-values' error.");return"The Range header is missing both start and end values. At least one of those values is needed. The Range header provided was "+
`"${h}"`},"no-range-header":()=>"No Range header was found in the Request provided.","range-not-satisfiable":({size:h,start:n,end:v})=>`The start (${n}) and end (${v}) values in the Range are `+`not satisfiable by the cached response, which is ${h} bytes.`,"attempt-to-cache-non-get-request":({url:h,method:n})=>`Unable to cache '${h}' because it is a '${n}' request and `+"only 'GET' requests can be cached.","cache-put-with-no-response":({url:h})=>`There was an attempt to cache '${h}' but the response was not `+
"defined.","no-response":({url:h,error:n})=>{h=`The strategy could not generate a response for '${h}'.`;n&&(h+=` The underlying error is ${n}.`);return h},"bad-precaching-response":({url:h,status:n})=>`The precaching request for '${h}' failed`+(n?` with an HTTP status of ${n}.`:"."),"non-precached-url":({url:h})=>`createHandlerBoundToURL('${h}') was called, but that URL is `+"not precached. Please pass in a URL that is precached instead.","add-to-cache-list-conflicting-integrities":({url:h})=>"Two of the entries passed to 'workbox-precaching.PrecacheController.addToCacheList()' had the URL "+
`${h} with different integrity values. Please remove one of them.`,"missing-precache-entry":({cacheName:h,url:n})=>`Unable to find a precached response in ${h} for ${n}.`,"cross-origin-copy-response":({origin:h})=>"workbox-core.copyResponse() can only be used with same-origin "+`responses. It was passed a response with origin ${h}.`}};
shadow$provide[18]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.messageGenerator=void 0;l(17);l(15);g.messageGenerator=(h,...n)=>{0<n.length&&(h+=` :: ${JSON.stringify(n)}`);return h}};
shadow$provide[19]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.WorkboxError=void 0;var h=l(18);l(15);class n extends Error{constructor(v,t){super((0,h.messageGenerator)(v,t));this.name=v;this.details=t}}g.WorkboxError=n};
shadow$provide[20]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.assert=void 0;l(19);l(15);g.assert=null};
shadow$provide[21]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.quotaErrorCallbacks=void 0;l(15);E=new Set;g.quotaErrorCallbacks=E};
shadow$provide[22]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.registerQuotaErrorCallback=function(n){h.quotaErrorCallbacks.add(n)};l(16);l(20);var h=l(21);l(15)};
shadow$provide[23]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.cacheNames=void 0;l(15);const h={googleAnalytics:"googleAnalytics",precache:"precache-v2",prefix:"workbox",runtime:"runtime",suffix:"undefined"!==typeof registration?registration.scope:""},n=t=>[h.prefix,t,h.suffix].filter(p=>p&&0<p.length).join("-"),v=t=>{for(const p of Object.keys(h))t(p)};g.cacheNames={updateDetails:t=>{v(p=>{"string"===typeof t[p]&&(h[p]=t[p])})},getGoogleAnalyticsName:t=>t||n(h.googleAnalytics),
getPrecacheName:t=>t||n(h.precache),getPrefix:()=>h.prefix,getRuntimeName:t=>t||n(h.runtime),getSuffix:()=>h.suffix}};
shadow$provide[24]=function(E,l,O,g){function h(n,v){n=new URL(n);for(const t of v)n.searchParams.delete(t);return n.href}Object.defineProperty(g,"__esModule",{value:!0});g.cacheMatchIgnoreParams=async function(n,v,t,p){const B=h(v.url,t);if(v.url===B)return n.match(v,p);const C=Object.assign(Object.assign({},p),{ignoreSearch:!0});v=await n.keys(v,C);for(const Q of v)if(v=h(Q.url,t),B===v)return n.match(Q,p)};l(15)};
shadow$provide[25]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.canConstructReadableStream=function(){if(void 0===h)try{new ReadableStream({start(){}}),h=!0}catch(n){h=!1}return h};l(15);let h};
shadow$provide[26]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.canConstructResponseFromBodyStream=function(){if(void 0===h){const n=new Response("");if("body"in n)try{new Response(n.body),h=!0}catch(v){h=!1}h=!1}return h};l(15);let h};
shadow$provide[27]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.dontWaitFor=function(h){void h.then(()=>{})};l(15)};
shadow$provide[28]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.Deferred=void 0;l(15);class h{constructor(){this.promise=new Promise((n,v)=>{this.resolve=n;this.reject=v})}}g.Deferred=h};
shadow$provide[29]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.executeQuotaErrorCallbacks=async function(){for(const n of h.quotaErrorCallbacks)await n()};l(16);var h=l(21);l(15)};
shadow$provide[30]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.getFriendlyURL=void 0;l(15);g.getFriendlyURL=h=>(new URL(String(h),location.href)).href.replace(new RegExp(`^${location.origin}`),"")};
shadow$provide[31]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.timeout=function(h){return new Promise(n=>setTimeout(n,h))};l(15)};
shadow$provide[32]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.resultingClientExists=async function(n){if(n){for(var v=await self.clients.matchAll({type:"window"}),t=new Set(v.map(C=>C.id)),p,B=performance.now();2E3>performance.now()-B;){v=await self.clients.matchAll({type:"window"});if(p=v.find(C=>n?C.id===n:!t.has(C.id)))break;await (0,h.timeout)(100)}return p}};var h=l(31);l(15)};
shadow$provide[33]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.waitUntil=function(h,n){n=n();h.waitUntil(n);return n};l(15)};
shadow$provide[34]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});Object.defineProperty(g,"assert",{enumerable:!0,get:function(){return h.assert}});Object.defineProperty(g,"cacheNames",{enumerable:!0,get:function(){return n.cacheNames}});Object.defineProperty(g,"cacheMatchIgnoreParams",{enumerable:!0,get:function(){return v.cacheMatchIgnoreParams}});Object.defineProperty(g,"canConstructReadableStream",{enumerable:!0,get:function(){return t.canConstructReadableStream}});Object.defineProperty(g,
"canConstructResponseFromBodyStream",{enumerable:!0,get:function(){return p.canConstructResponseFromBodyStream}});Object.defineProperty(g,"dontWaitFor",{enumerable:!0,get:function(){return B.dontWaitFor}});Object.defineProperty(g,"Deferred",{enumerable:!0,get:function(){return C.Deferred}});Object.defineProperty(g,"executeQuotaErrorCallbacks",{enumerable:!0,get:function(){return Q.executeQuotaErrorCallbacks}});Object.defineProperty(g,"getFriendlyURL",{enumerable:!0,get:function(){return A.getFriendlyURL}});
Object.defineProperty(g,"logger",{enumerable:!0,get:function(){return G.logger}});Object.defineProperty(g,"resultingClientExists",{enumerable:!0,get:function(){return J.resultingClientExists}});Object.defineProperty(g,"timeout",{enumerable:!0,get:function(){return U.timeout}});Object.defineProperty(g,"waitUntil",{enumerable:!0,get:function(){return Z.waitUntil}});Object.defineProperty(g,"WorkboxError",{enumerable:!0,get:function(){return M.WorkboxError}});var h=l(20),n=l(23),v=l(24),t=l(25),p=l(26),
B=l(27),C=l(28),Q=l(29),A=l(30),G=l(16),J=l(32),U=l(31),Z=l(33),M=l(19);l(15)};
shadow$provide[35]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.cacheNames=void 0;var h=l(23);l(15);g.cacheNames={get googleAnalytics(){return h.cacheNames.getGoogleAnalyticsName()},get precache(){return h.cacheNames.getPrecacheName()},get prefix(){return h.cacheNames.getPrefix()},get runtime(){return h.cacheNames.getRuntimeName()},get suffix(){return h.cacheNames.getSuffix()}}};
shadow$provide[36]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.copyResponse=async function(v,t){var p=null;v.url&&(p=(new URL(v.url)).origin);if(p!==self.location.origin)throw new n.WorkboxError("cross-origin-copy-response",{origin:p});v=v.clone();p={headers:new Headers(v.headers),status:v.status,statusText:v.statusText};t=t?t(p):p;v=(0,h.canConstructResponseFromBodyStream)()?v.body:await v.blob();return new Response(v,t)};var h=l(26),n=l(19);l(15)};
shadow$provide[37]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.clientsClaim=function(){self.addEventListener("activate",()=>self.clients.claim())};l(15)};
shadow$provide[38]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.setCacheNameDetails=function(n){h.cacheNames.updateDetails(n)};l(20);var h=l(23);l(19);l(15)};
shadow$provide[39]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.skipWaiting=function(){void self.skipWaiting()};l(16);l(15)};
shadow$provide[40]=function(E,l,O,g){l(15)};
shadow$provide[41]=function(E,l,O,g){function h(G){if("function"!==typeof WeakMap)return null;var J=new WeakMap,U=new WeakMap;return(h=function(Z){return Z?U:J})(G)}Object.defineProperty(g,"__esModule",{value:!0});var n={registerQuotaErrorCallback:!0,_private:!0,cacheNames:!0,copyResponse:!0,clientsClaim:!0,setCacheNameDetails:!0,skipWaiting:!0};Object.defineProperty(g,"registerQuotaErrorCallback",{enumerable:!0,get:function(){return v.registerQuotaErrorCallback}});Object.defineProperty(g,"cacheNames",
{enumerable:!0,get:function(){return t.cacheNames}});Object.defineProperty(g,"copyResponse",{enumerable:!0,get:function(){return p.copyResponse}});Object.defineProperty(g,"clientsClaim",{enumerable:!0,get:function(){return B.clientsClaim}});Object.defineProperty(g,"setCacheNameDetails",{enumerable:!0,get:function(){return C.setCacheNameDetails}});Object.defineProperty(g,"skipWaiting",{enumerable:!0,get:function(){return Q.skipWaiting}});g._private=void 0;var v=l(22);E=function(G,J){if(!J&&G&&G.__esModule)return G;
if(null===G||"object"!==typeof G&&"function"!==typeof G)return{default:G};if((J=h(J))&&J.has(G))return J.get(G);var U={},Z=Object.defineProperty&&Object.getOwnPropertyDescriptor,M;for(M in G)if("default"!==M&&Object.prototype.hasOwnProperty.call(G,M)){var P=Z?Object.getOwnPropertyDescriptor(G,M):null;P&&(P.get||P.set)?Object.defineProperty(U,M,P):U[M]=G[M]}U.default=G;J&&J.set(G,U);return U}(l(34));g._private=E;var t=l(35),p=l(36),B=l(37),C=l(38),Q=l(39);l(15);var A=l(40);Object.keys(A).forEach(function(G){"default"!==
G&&"__esModule"!==G&&(Object.prototype.hasOwnProperty.call(n,G)||G in g&&g[G]===A[G]||Object.defineProperty(g,G,{enumerable:!0,get:function(){return A[G]}}))})};
shadow$provide[42]=function(E,l,O,g){try{self["workbox:routing:6.4.0"]&&_()}catch(h){}};
shadow$provide[43]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.validMethods=g.defaultMethod=void 0;l(42);g.defaultMethod="GET";g.validMethods="DELETE GET HEAD PATCH POST PUT".split(" ")};
shadow$provide[44]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.normalizeHandler=void 0;l(20);l(42);g.normalizeHandler=h=>h&&"object"===typeof h?h:{handle:h}};
shadow$provide[45]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.Route=void 0;l(20);var h=l(43),n=l(44);l(42);class v{constructor(t,p,B=h.defaultMethod){this.handler=(0,n.normalizeHandler)(p);this.match=t;this.method=B}setCatchHandler(t){this.catchHandler=(0,n.normalizeHandler)(t)}}g.Route=v};
shadow$provide[46]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.NavigationRoute=void 0;l(20);l(16);E=l(45);l(42);class h extends E.Route{constructor(n,{allowlist:v=[/./],denylist:t=[]}={}){super(p=>this._match(p),n);this._allowlist=v;this._denylist=t}_match({url:n,request:v}){if(v&&"navigate"!==v.mode)return!1;const t=n.pathname+n.search;for(const p of this._denylist)if(p.test(t))return!1;return this._allowlist.some(p=>p.test(t))?!0:!1}}g.NavigationRoute=h};
shadow$provide[47]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.RegExpRoute=void 0;l(20);l(16);E=l(45);l(42);class h extends E.Route{constructor(n,v,t){super(({url:p})=>{const B=n.exec(p.href);if(B&&(p.origin===location.origin||0===B.index))return B.slice(1)},v,t)}}g.RegExpRoute=h};
shadow$provide[48]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.Router=void 0;l(20);l(30);var h=l(43);l(16);var n=l(44),v=l(19);l(42);class t{constructor(){this._routes=new Map;this._defaultHandlerMap=new Map}get routes(){return this._routes}addFetchListener(){self.addEventListener("fetch",p=>{var {request:B}=p;(B=this.handleRequest({request:B,event:p}))&&p.respondWith(B)})}addCacheListener(){self.addEventListener("message",p=>{if(p.data&&"CACHE_URLS"===p.data.type){var {payload:B}=
p.data;B=Promise.all(B.urlsToCache.map(C=>{"string"===typeof C&&(C=[C]);C=new Request(...C);return this.handleRequest({request:C,event:p})}));p.waitUntil(B);p.ports&&p.ports[0]&&void B.then(()=>p.ports[0].postMessage(!0))}})}handleRequest({request:p,event:B}){const C=new URL(p.url,location.href);if(C.protocol.startsWith("http")){var {params:Q,route:A}=this.findMatchingRoute({event:B,request:p,sameOrigin:C.origin===location.origin,url:C}),G=A&&A.handler,J=p.method;!G&&this._defaultHandlerMap.has(J)&&
(G=this._defaultHandlerMap.get(J));if(G){try{var U=G.handle({url:C,request:p,event:B,params:Q})}catch(M){U=Promise.reject(M)}var Z=A&&A.catchHandler;U instanceof Promise&&(this._catchHandler||Z)&&(U=U.catch(async M=>{if(Z)try{return await Z.handle({url:C,request:p,event:B,params:Q})}catch(P){P instanceof Error&&(M=P)}if(this._catchHandler)return this._catchHandler.handle({url:C,request:p,event:B});throw M;}));return U}}}findMatchingRoute({url:p,sameOrigin:B,request:C,event:Q}){var A=this._routes.get(C.method)||
[];for(const G of A)if(A=G.match({url:p,sameOrigin:B,request:C,event:Q}))return p=A,Array.isArray(p)&&0===p.length?p=void 0:A.constructor===Object&&0===Object.keys(A).length?p=void 0:"boolean"===typeof A&&(p=void 0),{route:G,params:p};return{}}setDefaultHandler(p,B=h.defaultMethod){this._defaultHandlerMap.set(B,(0,n.normalizeHandler)(p))}setCatchHandler(p){this._catchHandler=(0,n.normalizeHandler)(p)}registerRoute(p){this._routes.has(p.method)||this._routes.set(p.method,[]);this._routes.get(p.method).push(p)}unregisterRoute(p){if(!this._routes.has(p.method))throw new v.WorkboxError("unregister-route-but-not-found-with-method",
{method:p.method});const B=this._routes.get(p.method).indexOf(p);if(-1<B)this._routes.get(p.method).splice(B,1);else throw new v.WorkboxError("unregister-route-route-not-registered");}}g.Router=t};
shadow$provide[49]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.getOrCreateDefaultRouter=void 0;var h=l(48);l(42);let n;g.getOrCreateDefaultRouter=()=>{n||(n=new h.Router,n.addFetchListener(),n.addCacheListener());return n}};
shadow$provide[50]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.registerRoute=function(p,B,C){if("string"===typeof p){const Q=new URL(p,location.href);p=new n.Route(({url:A})=>A.href===Q.href,B,C)}else if(p instanceof RegExp)p=new v.RegExpRoute(p,B,C);else if("function"===typeof p)p=new n.Route(p,B,C);else if(!(p instanceof n.Route))throw new h.WorkboxError("unsupported-route-type",{moduleName:"workbox-routing",funcName:"registerRoute",paramName:"capture"});(0,t.getOrCreateDefaultRouter)().registerRoute(p);
return p};l(16);var h=l(19),n=l(45),v=l(47),t=l(49);l(42)};
shadow$provide[51]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.setCatchHandler=function(n){(0,h.getOrCreateDefaultRouter)().setCatchHandler(n)};var h=l(49);l(42)};
shadow$provide[52]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.setDefaultHandler=function(n){(0,h.getOrCreateDefaultRouter)().setDefaultHandler(n)};var h=l(49);l(42)};
shadow$provide[53]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});Object.defineProperty(g,"NavigationRoute",{enumerable:!0,get:function(){return h.NavigationRoute}});Object.defineProperty(g,"RegExpRoute",{enumerable:!0,get:function(){return n.RegExpRoute}});Object.defineProperty(g,"registerRoute",{enumerable:!0,get:function(){return v.registerRoute}});Object.defineProperty(g,"Route",{enumerable:!0,get:function(){return t.Route}});Object.defineProperty(g,"Router",{enumerable:!0,
get:function(){return p.Router}});Object.defineProperty(g,"setCatchHandler",{enumerable:!0,get:function(){return B.setCatchHandler}});Object.defineProperty(g,"setDefaultHandler",{enumerable:!0,get:function(){return C.setDefaultHandler}});var h=l(46),n=l(47),v=l(50),t=l(45),p=l(48),B=l(51),C=l(52);l(42)};
shadow$provide[54]=function(E,l,O,g){try{self["workbox:precaching:6.4.0"]&&_()}catch(h){}};
shadow$provide[55]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.createCacheKey=function(n){if(!n)throw new h.WorkboxError("add-to-cache-list-unexpected-type",{entry:n});if("string"===typeof n)return n=new URL(n,location.href),{cacheKey:n.href,url:n.href};const {revision:v,url:t}=n;if(!t)throw new h.WorkboxError("add-to-cache-list-unexpected-type",{entry:n});if(!v)return n=new URL(t,location.href),{cacheKey:n.href,url:n.href};n=new URL(t,location.href);const p=new URL(t,location.href);
n.searchParams.set("__WB_REVISION__",v);return{cacheKey:n.href,url:p.href}};var h=l(19);l(54)};
shadow$provide[56]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheInstallReportPlugin=void 0;l(54);class h{constructor(){this.updatedURLs=[];this.notUpdatedURLs=[];this.handlerWillStart=async({request:n,state:v})=>{v&&(v.originalRequest=n)};this.cachedResponseWillBeUsed=async({event:n,state:v,cachedResponse:t})=>{"install"===n.type&&v&&v.originalRequest&&v.originalRequest instanceof Request&&(n=v.originalRequest.url,t?this.notUpdatedURLs.push(n):this.updatedURLs.push(n));
return t}}}g.PrecacheInstallReportPlugin=h};
shadow$provide[57]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheCacheKeyPlugin=void 0;l(54);class h{constructor({precacheController:n}){this.cacheKeyWillBeUsed=async({request:v,params:t})=>(t=(null===t||void 0===t?void 0:t.cacheKey)||this._precacheController.getCacheKeyForURL(v.url))?new Request(t,{headers:v.headers}):v;this._precacheController=n}}g.PrecacheCacheKeyPlugin=h};
shadow$provide[58]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.printCleanupDetails=function(n){const v=n.length;if(0<v){h.logger.groupCollapsed("During precaching cleanup, "+`${v} cached `+`request${1===v?" was":"s were"} deleted.`);h.logger.groupCollapsed("Deleted Cache Requests");for(const t of n)h.logger.log(t);h.logger.groupEnd();h.logger.groupEnd()}};var h=l(16);l(54)};
shadow$provide[59]=function(E,l,O,g){function h(v,t){if(0!==t.length){n.logger.groupCollapsed(v);for(const p of t)n.logger.log(p);n.logger.groupEnd()}}Object.defineProperty(g,"__esModule",{value:!0});g.printInstallDetails=function(v,t){var p=v.length;const B=t.length;if(p||B)p=`Precaching ${p} file${1===p?"":"s"}.`,0<B&&(p+=` ${B} `+`file${1===B?" is":"s are"} already cached.`),n.logger.groupCollapsed(p),h("View newly precached URLs.",v),h("View previously precached URLs.",t),n.logger.groupEnd()};
var n=l(16);l(54)};
shadow$provide[60]=function(E,l,O,g){try{self["workbox:strategies:6.4.0"]&&_()}catch(h){}};
shadow$provide[61]=function(E,l,O,g){function h(A){return"string"===typeof A?new Request(A):A}Object.defineProperty(g,"__esModule",{value:!0});g.StrategyHandler=void 0;l(20);var n=l(24),v=l(28),t=l(29),p=l(30);l(16);var B=l(31),C=l(19);l(60);class Q{constructor(A,G){this._cacheKeys={};Object.assign(this,G);this.event=G.event;this._strategy=A;this._handlerDeferred=new v.Deferred;this._extendLifetimePromises=[];this._plugins=[...A.plugins];this._pluginStateMap=new Map;for(const J of this._plugins)this._pluginStateMap.set(J,
{});this.event.waitUntil(this._handlerDeferred.promise)}async fetch(A){const {event:G}=this;A=h(A);if("navigate"===A.mode&&G instanceof FetchEvent&&G.preloadResponse){var J=await G.preloadResponse;if(J)return J}J=this.hasCallback("fetchDidFail")?A.clone():null;try{for(var U of this.iterateCallbacks("requestWillFetch"))A=await U({request:A.clone(),event:G})}catch(Z){if(Z instanceof Error)throw new C.WorkboxError("plugin-error-request-will-fetch",{thrownErrorMessage:Z.message});}U=A.clone();try{let Z;
Z=await fetch(A,"navigate"===A.mode?void 0:this._strategy.fetchOptions);for(const M of this.iterateCallbacks("fetchDidSucceed"))Z=await M({event:G,request:U,response:Z});return Z}catch(Z){throw J&&await this.runCallbacks("fetchDidFail",{error:Z,event:G,originalRequest:J.clone(),request:U.clone()}),Z;}}async fetchAndCachePut(A){const G=await this.fetch(A),J=G.clone();void this.waitUntil(this.cachePut(A,J));return G}async cacheMatch(A){A=h(A);const {cacheName:G,matchOptions:J}=this._strategy;A=await this.getCacheKey(A,
"read");var U=Object.assign(Object.assign({},J),{cacheName:G});U=await caches.match(A,U);for(const Z of this.iterateCallbacks("cachedResponseWillBeUsed"))U=await Z({cacheName:G,matchOptions:J,cachedResponse:U,request:A,event:this.event})||void 0;return U}async cachePut(A,G){A=h(A);await (0,B.timeout)(0);A=await this.getCacheKey(A,"write");if(!G)throw new C.WorkboxError("cache-put-with-no-response",{url:(0,p.getFriendlyURL)(A.url)});G=await this._ensureResponseSafeToCache(G);if(!G)return!1;const {cacheName:J,
matchOptions:U}=this._strategy,Z=await self.caches.open(J),M=this.hasCallback("cacheDidUpdate"),P=M?await (0,n.cacheMatchIgnoreParams)(Z,A.clone(),["__WB_REVISION__"],U):null;try{await Z.put(A,M?G.clone():G)}catch(V){if(V instanceof Error)throw"QuotaExceededError"===V.name&&await (0,t.executeQuotaErrorCallbacks)(),V;}for(const V of this.iterateCallbacks("cacheDidUpdate"))await V({cacheName:J,oldResponse:P,newResponse:G.clone(),request:A,event:this.event});return!0}async getCacheKey(A,G){const J=`${A.url} | ${G}`;
if(!this._cacheKeys[J]){for(const U of this.iterateCallbacks("cacheKeyWillBeUsed"))A=h(await U({mode:G,request:A,event:this.event,params:this.params}));this._cacheKeys[J]=A}return this._cacheKeys[J]}hasCallback(A){for(const G of this._strategy.plugins)if(A in G)return!0;return!1}async runCallbacks(A,G){for(const J of this.iterateCallbacks(A))await J(G)}*iterateCallbacks(A){for(const G of this._strategy.plugins)if("function"===typeof G[A]){const J=this._pluginStateMap.get(G);yield(U=>{U=Object.assign(Object.assign({},
U),{state:J});return G[A](U)})}}waitUntil(A){this._extendLifetimePromises.push(A);return A}async doneWaiting(){let A;for(;A=this._extendLifetimePromises.shift();)await A}destroy(){this._handlerDeferred.resolve(null)}async _ensureResponseSafeToCache(A){let G=!1;for(const J of this.iterateCallbacks("cacheWillUpdate"))if(A=await J({request:this.request,response:A,event:this.event})||void 0,G=!0,!A)break;G||A&&200!==A.status&&(A=void 0);return A}}g.StrategyHandler=Q};
shadow$provide[62]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.Strategy=void 0;var h=l(23),n=l(19);l(16);l(30);var v=l(61);l(60);class t{constructor(p={}){this.cacheName=h.cacheNames.getRuntimeName(p.cacheName);this.plugins=p.plugins||[];this.fetchOptions=p.fetchOptions;this.matchOptions=p.matchOptions}handle(p){[p]=this.handleAll(p);return p}handleAll(p){p instanceof FetchEvent&&(p={event:p,request:p.request});var B=p.event;const C="string"===typeof p.request?new Request(p.request):
p.request,Q=new v.StrategyHandler(this,{event:B,request:C,params:"params"in p?p.params:void 0});p=this._getResponse(Q,C,B);B=this._awaitComplete(p,Q,C,B);return[p,B]}async _getResponse(p,B,C){await p.runCallbacks("handlerWillStart",{event:C,request:B});let Q=void 0;try{if(Q=await this._handle(B,p),!Q||"error"===Q.type)throw new n.WorkboxError("no-response",{url:B.url});}catch(A){if(A instanceof Error)for(const G of p.iterateCallbacks("handlerDidError"))if(Q=await G({error:A,event:C,request:B}))break;
if(!Q)throw A;}for(const A of p.iterateCallbacks("handlerWillRespond"))Q=await A({event:C,request:B,response:Q});return Q}async _awaitComplete(p,B,C,Q){let A,G;try{A=await p}catch(J){}try{await B.runCallbacks("handlerDidRespond",{event:Q,request:C,response:A}),await B.doneWaiting()}catch(J){J instanceof Error&&(G=J)}await B.runCallbacks("handlerDidComplete",{event:Q,request:C,response:A,error:G});B.destroy();if(G)throw G;}}g.Strategy=t};
shadow$provide[63]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheStrategy=void 0;var h=l(36),n=l(23);l(30);l(16);var v=l(19);E=l(62);l(54);class t extends E.Strategy{constructor(p={}){p.cacheName=n.cacheNames.getPrecacheName(p.cacheName);super(p);this._fallbackToNetwork=!1===p.fallbackToNetwork?!1:!0;this.plugins.push(t.copyRedirectedCacheableResponsesPlugin)}async _handle(p,B){const C=await B.cacheMatch(p);return C?C:B.event&&"install"===B.event.type?await this._handleInstall(p,
B):await this._handleFetch(p,B)}async _handleFetch(p,B){var C=B.params||{};if(this._fallbackToNetwork){C=C.integrity;var Q=p.integrity;const A=!Q||Q===C;Q=await B.fetch(new Request(p,{integrity:Q||C}));C&&A&&(this._useDefaultCacheabilityPluginIfNeeded(),await B.cachePut(p,Q.clone()))}else throw new v.WorkboxError("missing-precache-entry",{cacheName:this.cacheName,url:p.url});return Q}async _handleInstall(p,B){this._useDefaultCacheabilityPluginIfNeeded();const C=await B.fetch(p);if(!await B.cachePut(p,
C.clone()))throw new v.WorkboxError("bad-precaching-response",{url:p.url,status:C.status});return C}_useDefaultCacheabilityPluginIfNeeded(){let p=null,B=0;for(const [C,Q]of this.plugins.entries())Q!==t.copyRedirectedCacheableResponsesPlugin&&(Q===t.defaultPrecacheCacheabilityPlugin&&(p=C),Q.cacheWillUpdate&&B++);0===B?this.plugins.push(t.defaultPrecacheCacheabilityPlugin):1<B&&null!==p&&this.plugins.splice(p,1)}}g.PrecacheStrategy=t;t.defaultPrecacheCacheabilityPlugin={async cacheWillUpdate({response:p}){return!p||
400<=p.status?null:p}};t.copyRedirectedCacheableResponsesPlugin={async cacheWillUpdate({response:p}){return p.redirected?await (0,h.copyResponse)(p):p}}};
shadow$provide[64]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheController=void 0;l(20);var h=l(23);l(16);var n=l(19),v=l(33),t=l(55),p=l(56),B=l(57);l(58);l(59);var C=l(63);l(54);class Q{constructor({cacheName:A,plugins:G=[],fallbackToNetwork:J=!0}={}){this._urlsToCacheKeys=new Map;this._urlsToCacheModes=new Map;this._cacheKeysToIntegrities=new Map;this._strategy=new C.PrecacheStrategy({cacheName:h.cacheNames.getPrecacheName(A),plugins:[...G,new B.PrecacheCacheKeyPlugin({precacheController:this})],
fallbackToNetwork:J});this.install=this.install.bind(this);this.activate=this.activate.bind(this)}get strategy(){return this._strategy}precache(A){this.addToCacheList(A);this._installAndActiveListenersAdded||(self.addEventListener("install",this.install),self.addEventListener("activate",this.activate),this._installAndActiveListenersAdded=!0)}addToCacheList(A){const G=[];for(const J of A){"string"===typeof J?G.push(J):J&&void 0===J.revision&&G.push(J.url);const {cacheKey:U,url:Z}=(0,t.createCacheKey)(J);
A="string"!==typeof J&&J.revision?"reload":"default";if(this._urlsToCacheKeys.has(Z)&&this._urlsToCacheKeys.get(Z)!==U)throw new n.WorkboxError("add-to-cache-list-conflicting-entries",{firstEntry:this._urlsToCacheKeys.get(Z),secondEntry:U});if("string"!==typeof J&&J.integrity){if(this._cacheKeysToIntegrities.has(U)&&this._cacheKeysToIntegrities.get(U)!==J.integrity)throw new n.WorkboxError("add-to-cache-list-conflicting-integrities",{url:Z});this._cacheKeysToIntegrities.set(U,J.integrity)}this._urlsToCacheKeys.set(Z,
U);this._urlsToCacheModes.set(Z,A);0<G.length&&(A="Workbox is precaching URLs without revision "+`info: ${G.join(", ")}\nThis is generally NOT safe. `+"Learn more at https://bit.ly/wb-precache",console.warn(A))}}install(A){return(0,v.waitUntil)(A,async()=>{const G=new p.PrecacheInstallReportPlugin;this.strategy.plugins.push(G);for(const [M,P]of this._urlsToCacheKeys){var J=this._cacheKeysToIntegrities.get(P);const V=this._urlsToCacheModes.get(M);J=new Request(M,{integrity:J,cache:V,credentials:"same-origin"});
await Promise.all(this.strategy.handleAll({params:{cacheKey:P},request:J,event:A}))}const {updatedURLs:U,notUpdatedURLs:Z}=G;return{updatedURLs:U,notUpdatedURLs:Z}})}activate(A){return(0,v.waitUntil)(A,async()=>{const G=await self.caches.open(this.strategy.cacheName),J=await G.keys(),U=new Set(this._urlsToCacheKeys.values()),Z=[];for(const M of J)U.has(M.url)||(await G.delete(M),Z.push(M.url));return{deletedURLs:Z}})}getURLsToCacheKeys(){return this._urlsToCacheKeys}getCachedURLs(){return[...this._urlsToCacheKeys.keys()]}getCacheKeyForURL(A){A=
new URL(A,location.href);return this._urlsToCacheKeys.get(A.href)}getIntegrityForCacheKey(A){return this._cacheKeysToIntegrities.get(A)}async matchPrecache(A){if(A=this.getCacheKeyForURL(A instanceof Request?A.url:A))return(await self.caches.open(this.strategy.cacheName)).match(A)}createHandlerBoundToURL(A){const G=this.getCacheKeyForURL(A);if(!G)throw new n.WorkboxError("non-precached-url",{url:A});return J=>{J.request=new Request(A);J.params=Object.assign({cacheKey:G},J.params);return this.strategy.handle(J)}}}
g.PrecacheController=Q};
shadow$provide[65]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.getOrCreatePrecacheController=void 0;var h=l(64);l(54);let n;g.getOrCreatePrecacheController=()=>{n||(n=new h.PrecacheController);return n}};
shadow$provide[66]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.addPlugins=function(n){(0,h.getOrCreatePrecacheController)().strategy.plugins.push(...n)};var h=l(65);l(54)};
shadow$provide[67]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.removeIgnoredSearchParams=function(h,n=[]){for(const v of[...h.searchParams.keys()])n.some(t=>t.test(v))&&h.searchParams.delete(v);return h};l(54)};
shadow$provide[68]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.generateURLVariations=function*(n,{ignoreURLParametersMatching:v=[/^utm_/,/^fbclid$/],directoryIndex:t="index.html",cleanURLs:p=!0,urlManipulation:B}={}){n=new URL(n,location.href);n.hash="";yield n.href;v=(0,h.removeIgnoredSearchParams)(n,v);yield v.href;if(t&&v.pathname.endsWith("/")){const C=new URL(v.href);C.pathname+=t;yield C.href}p&&(t=new URL(v.href),t.pathname+=".html",yield t.href);if(B){B=B({url:n});
for(const C of B)yield C.href}};var h=l(67);l(54)};
shadow$provide[69]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheRoute=void 0;l(16);l(30);E=l(45);var h=l(68);l(54);class n extends E.Route{constructor(v,t){super(({request:p})=>{var B=v.getURLsToCacheKeys();for(const C of(0,h.generateURLVariations)(p.url,t))if(p=B.get(C))return B=v.getIntegrityForCacheKey(p),{cacheKey:p,integrity:B}},v.strategy)}}g.PrecacheRoute=n};
shadow$provide[70]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.addRoute=function(t){const p=(0,n.getOrCreatePrecacheController)();t=new v.PrecacheRoute(p,t);(0,h.registerRoute)(t)};var h=l(50),n=l(65),v=l(69);l(54)};
shadow$provide[71]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.deleteOutdatedCaches=void 0;l(54);g.deleteOutdatedCaches=async(h,n="-precache-")=>{const v=(await self.caches.keys()).filter(t=>t.includes(n)&&t.includes(self.registration.scope)&&t!==h);await Promise.all(v.map(t=>self.caches.delete(t)));return v}};
shadow$provide[72]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.cleanupOutdatedCaches=function(){self.addEventListener("activate",v=>{const t=h.cacheNames.getPrecacheName();v.waitUntil((0,n.deleteOutdatedCaches)(t).then(p=>{}))})};var h=l(23);l(16);var n=l(71);l(54)};
shadow$provide[73]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.createHandlerBoundToURL=function(n){return(0,h.getOrCreatePrecacheController)().createHandlerBoundToURL(n)};var h=l(65);l(54)};
shadow$provide[74]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.getCacheKeyForURL=function(n){return(0,h.getOrCreatePrecacheController)().getCacheKeyForURL(n)};var h=l(65);l(54)};
shadow$provide[75]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.matchPrecache=function(n){return(0,h.getOrCreatePrecacheController)().matchPrecache(n)};var h=l(65);l(54)};
shadow$provide[76]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.precache=function(n){(0,h.getOrCreatePrecacheController)().precache(n)};var h=l(65);l(54)};
shadow$provide[77]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.precacheAndRoute=function(v,t){(0,n.precache)(v);(0,h.addRoute)(t)};var h=l(70),n=l(76);l(54)};
shadow$provide[78]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.PrecacheFallbackPlugin=void 0;var h=l(65);l(54);class n{constructor({fallbackURL:v,precacheController:t}){this.handlerDidError=()=>this._precacheController.matchPrecache(this._fallbackURL);this._fallbackURL=v;this._precacheController=t||(0,h.getOrCreatePrecacheController)()}}g.PrecacheFallbackPlugin=n};
shadow$provide[79]=function(E,l,O,g){l(54)};
shadow$provide[80]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});var h={addPlugins:!0,addRoute:!0,cleanupOutdatedCaches:!0,createHandlerBoundToURL:!0,getCacheKeyForURL:!0,matchPrecache:!0,precache:!0,precacheAndRoute:!0,PrecacheController:!0,PrecacheRoute:!0,PrecacheStrategy:!0,PrecacheFallbackPlugin:!0};Object.defineProperty(g,"addPlugins",{enumerable:!0,get:function(){return n.addPlugins}});Object.defineProperty(g,"addRoute",{enumerable:!0,get:function(){return v.addRoute}});
Object.defineProperty(g,"cleanupOutdatedCaches",{enumerable:!0,get:function(){return t.cleanupOutdatedCaches}});Object.defineProperty(g,"createHandlerBoundToURL",{enumerable:!0,get:function(){return p.createHandlerBoundToURL}});Object.defineProperty(g,"getCacheKeyForURL",{enumerable:!0,get:function(){return B.getCacheKeyForURL}});Object.defineProperty(g,"matchPrecache",{enumerable:!0,get:function(){return C.matchPrecache}});Object.defineProperty(g,"precache",{enumerable:!0,get:function(){return Q.precache}});
Object.defineProperty(g,"precacheAndRoute",{enumerable:!0,get:function(){return A.precacheAndRoute}});Object.defineProperty(g,"PrecacheController",{enumerable:!0,get:function(){return G.PrecacheController}});Object.defineProperty(g,"PrecacheRoute",{enumerable:!0,get:function(){return J.PrecacheRoute}});Object.defineProperty(g,"PrecacheStrategy",{enumerable:!0,get:function(){return U.PrecacheStrategy}});Object.defineProperty(g,"PrecacheFallbackPlugin",{enumerable:!0,get:function(){return Z.PrecacheFallbackPlugin}});
var n=l(66),v=l(70),t=l(72),p=l(73),B=l(74),C=l(75),Q=l(76),A=l(77),G=l(64),J=l(69),U=l(63),Z=l(78);l(54);var M=l(79);Object.keys(M).forEach(function(P){"default"!==P&&"__esModule"!==P&&(Object.prototype.hasOwnProperty.call(h,P)||P in g&&g[P]===M[P]||Object.defineProperty(g,P,{enumerable:!0,get:function(){return M[P]}}))})};
shadow$provide[81]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.messages=void 0;var h=l(16),n=l(30);l(60);g.messages={strategyStart:(v,t)=>`Using ${v} to respond to '${(0,n.getFriendlyURL)(t.url)}'`,printFinalResponse:v=>{v&&(h.logger.groupCollapsed("View the final response here."),h.logger.log(v||"[No response returned]"),h.logger.groupEnd())}}};
shadow$provide[82]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.CacheFirst=void 0;l(20);l(16);var h=l(19);E=l(62);l(81);l(60);class n extends E.Strategy{async _handle(v,t){let p=await t.cacheMatch(v),B=void 0;if(!p)try{p=await t.fetchAndCachePut(v)}catch(C){C instanceof Error&&(B=C)}if(!p)throw new h.WorkboxError("no-response",{url:v.url,error:B});return p}}g.CacheFirst=n};
shadow$provide[83]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.CacheOnly=void 0;l(20);l(16);var h=l(19);E=l(62);l(81);l(60);class n extends E.Strategy{async _handle(v,t){t=await t.cacheMatch(v);if(!t)throw new h.WorkboxError("no-response",{url:v.url});return t}}g.CacheOnly=n};
shadow$provide[84]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.cacheOkAndOpaquePlugin=void 0;l(60);g.cacheOkAndOpaquePlugin={cacheWillUpdate:async({response:h})=>200===h.status||0===h.status?h:null}};
shadow$provide[85]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.NetworkFirst=void 0;l(20);l(16);var h=l(19),n=l(84);E=l(62);l(81);l(60);class v extends E.Strategy{constructor(t={}){super(t);this.plugins.some(p=>"cacheWillUpdate"in p)||this.plugins.unshift(n.cacheOkAndOpaquePlugin);this._networkTimeoutSeconds=t.networkTimeoutSeconds||0}async _handle(t,p){var B=[];const C=[];let Q;if(this._networkTimeoutSeconds){const {id:G,promise:J}=this._getTimeoutPromise({request:t,logs:B,
handler:p});Q=G;C.push(J)}const A=this._getNetworkPromise({timeoutId:Q,request:t,logs:B,handler:p});C.push(A);B=await p.waitUntil((async()=>await p.waitUntil(Promise.race(C))||await A)());if(!B)throw new h.WorkboxError("no-response",{url:t.url});return B}_getTimeoutPromise({request:t,handler:p}){let B;return{promise:new Promise(C=>{B=setTimeout(async()=>{C(await p.cacheMatch(t))},1E3*this._networkTimeoutSeconds)}),id:B}}async _getNetworkPromise({timeoutId:t,request:p,handler:B}){let C,Q;try{Q=await B.fetchAndCachePut(p)}catch(A){A instanceof
Error&&(C=A)}t&&clearTimeout(t);if(C||!Q)Q=await B.cacheMatch(p);return Q}}g.NetworkFirst=v};
shadow$provide[86]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.NetworkOnly=void 0;l(20);l(16);var h=l(31),n=l(19);E=l(62);l(81);l(60);class v extends E.Strategy{constructor(t={}){super(t);this._networkTimeoutSeconds=t.networkTimeoutSeconds||0}async _handle(t,p){let B=void 0,C;try{const Q=[p.fetch(t)];if(this._networkTimeoutSeconds){const A=(0,h.timeout)(1E3*this._networkTimeoutSeconds);Q.push(A)}C=await Promise.race(Q);if(!C)throw Error("Timed out the network response after "+
`${this._networkTimeoutSeconds} seconds.`);}catch(Q){Q instanceof Error&&(B=Q)}if(!C)throw new n.WorkboxError("no-response",{url:t.url,error:B});return C}}g.NetworkOnly=v};
shadow$provide[87]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});g.StaleWhileRevalidate=void 0;l(20);l(16);var h=l(19),n=l(84);E=l(62);l(81);l(60);class v extends E.Strategy{constructor(t={}){super(t);this.plugins.some(p=>"cacheWillUpdate"in p)||this.plugins.unshift(n.cacheOkAndOpaquePlugin)}async _handle(t,p){const B=p.fetchAndCachePut(t).catch(()=>{});p=await p.cacheMatch(t);let C;if(!p)try{p=await B}catch(Q){Q instanceof Error&&(C=Q)}if(!p)throw new h.WorkboxError("no-response",
{url:t.url,error:C});return p}}g.StaleWhileRevalidate=v};
shadow$provide[88]=function(E,l,O,g){Object.defineProperty(g,"__esModule",{value:!0});Object.defineProperty(g,"CacheFirst",{enumerable:!0,get:function(){return h.CacheFirst}});Object.defineProperty(g,"CacheOnly",{enumerable:!0,get:function(){return n.CacheOnly}});Object.defineProperty(g,"NetworkFirst",{enumerable:!0,get:function(){return v.NetworkFirst}});Object.defineProperty(g,"NetworkOnly",{enumerable:!0,get:function(){return t.NetworkOnly}});Object.defineProperty(g,"StaleWhileRevalidate",{enumerable:!0,
get:function(){return p.StaleWhileRevalidate}});Object.defineProperty(g,"Strategy",{enumerable:!0,get:function(){return B.Strategy}});Object.defineProperty(g,"StrategyHandler",{enumerable:!0,get:function(){return C.StrategyHandler}});var h=l(82),n=l(83),v=l(85),t=l(86),p=l(87),B=l(62),C=l(61);l(60)};
'use strict';$APP.ir(14,{});var rL=$APP.ir(41,{});var pL=$APP.ir(53,{});var sL=$APP.ir(80,{});var qL=$APP.ir(88,{});var tL=$APP.Xi($APP.re.se(function(a){return["/solitaire",$APP.u.ga(a)].join("")},new $APP.X(null,22,5,$APP.Y,"/ /assets/re-com/css/bootstrap.css /assets/re-com/css/material-design-iconic-font.min.css /assets/re-com/css/re-com.css /assets/re-com/css/chosen-sprite.png /assets/re-com/css/chosen-sprite@2x.png /assets/re-com/fonts/Material-Design-Iconic-Font.eot /assets/re-com/fonts/Material-Design-Iconic-Font.svg /assets/re-com/fonts/Material-Design-Iconic-Font.ttf /assets/re-com/fonts/Material-Design-Iconic-Font.woff /assets/re-com/fonts/Material-Design-Iconic-Font.woff2 /assets/re-com/scripts/detect-element-resize.js /assets/css/app.css /assets/images/back.jpeg /assets/images/clubs.svg /assets/images/diamonds.svg /assets/images/hearts.svg /assets/images/spades.svg /assets/images/icon192.png /assets/images/icon512.png /shared.js /app.js".split(" "),
null)));self.addEventListener("install",function(a){return a.waitUntil(caches.open(rL.cacheNames.runtime).then(function(b){return b.addAll(tL)}))});self.addEventListener("message",function(a){a=null==a?null:a.data;return $APP.I.se(null==a?null:a.type,"SKIP_WAITING")?self.skipWaiting():null});pL.registerRoute(function(a){return $APP.I.se(a.request.destination,"image")},new qL.CacheFirst);pL.setDefaultHandler(new qL.StaleWhileRevalidate);sL.precacheAndRoute([{url:"/solitaire/",revision:"6d4ac8474ba89a0a07d14a82e71997d848f3f3bb3f3aeb94eff69abeea6f91e1"}]);
pL.registerRoute(new pL.NavigationRoute(sL.createHandlerBoundToURL("/solitaire/")));
}).call(this);